
si.galli.k =...
    [1.8
    2
    2
    1.8
    2
    1
    1.5
    4
    4
    4.8
    4
    ];
    
si.galli.tf = ...
    [0.1
    0.13
    0.2
    1.27
    0.52
    0.4
    0.5
    1.2
    1.6
    3.6
    80
    ];

si.galli.tf = si.galli.tf*1000;


semilogx(...
    si.galli.tf(1), si.galli.k(1),'.',...
    si.galli.tf(2), si.galli.k(2),'.',...
    si.galli.tf(3), si.galli.k(3),'.',...
    si.galli.tf(4), si.galli.k(4),'.',...
    si.galli.tf(5), si.galli.k(5),'.',...
    si.galli.tf(6), si.galli.k(6),'.',...
    si.galli.tf(7), si.galli.k(7),'.',...
    si.galli.tf(8), si.galli.k(8),'.',...
    si.galli.tf(9), si.galli.k(9),'.',...
    si.galli.tf(10), si.galli.k(10),'.',...
    si.galli.tf(11), si.galli.k(11),'.'...
    )
xlabel('tf (nm)')
ylabel('k(tf) (W/m-K)')

legend(...
    'Wada and Kamijoh (1996)',...
    'Zink, Pietri, Hellman (2006)',...
    'Yang, Cahill, et al (2010)',...
    'Zink, Pietri, Hellman (2006)',...
    'Cahill, Katiyar, Abelson (1994)',...
    'Kuo, Li, Schmid (1992)',...
    'Moon, Hatano, et al (2002)',...
    'Wieczorek, Goldsmid, Paul (1989)',...
    'Yang, Cahill, et al (2010)',...
    'Wieczorek, Goldsmid, Paul (1989)',...
    'Liu, Feldman, et al (2009)')



% si.malen.k = ...
%     [
%     1.7
%     1.0
%     0.9
%     ];
%     
% si.malen.tf = ...
%     [
%     10^(-0.2)
%     10^(-1)
%     10^(-1.5)
%     ];
% 
% semilogx(...
%     si.malen.tf,si.malen.k,'.',...
%     si.galli.tf, si.galli.k,'.','MarkerSize',15)
% xlabel('tf (\mu m)')
% ylabel('k(tf) W/m-K')
% 
% axis(...
%     [...
%     min([si.galli.tf;si.malen.tf]) ...
%     max([si.galli.tf;si.malen.tf]) ...
%     0 ...
%     max([si.galli.k;si.malen.k])...
%     ]...
%     );
% 
% legend('malen','galli')

