clear



%--------------------------------------------------------------------------
%c=0.0
%--------------------------------------------------------------------------
ipt = 1;
%af
str.af = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/work/';
af(ipt).af=m_af_load(str.af);
%vcnmd
str.nmd = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/';
vcnmd(ipt).nmd = load([str.nmd 'NMDdata.mat']);
vcnmd(ipt).sed = load([str.nmd 'SEDdata.mat']);
vcnmd(ipt).sed = nmd_convert_data(vcnmd(ipt).nmd,vcnmd(ipt).sed);
%gnmd
str.nmd = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD_AF/1/work/';
% gnmd(ipt).nmd = load([str.nmd 'NMDdata.mat']);
% gnmd(ipt).sed = load([str.nmd 'SEDavg.mat']);
%vcald
str.alloy = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/';
% alloy(ipt).alloy = load([str.alloy 'ALLOY.mat']);
str.ald = '/home/jason/disorder2/lj/ald/m1/10x/Data_fullBZ.xls';
vcald(ipt).ald = m_joe_read_data([str.ald]);
vcald(ipt).sedald = m_joe_ald2nmd( vcnmd(ipt).nmd , vcald(ipt).ald );

loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life.*vcnmd(ipt).sed.groupvel(:,1),'.',...
    vcald(ipt).ald.freq*0.97,...
    vcald(ipt).ald.life.*vcald(ipt).ald.vel(:,1),'.',...
    af(ipt).af.freq,af(ipt).af.Di(:,2),'.'...
    )
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%c=0.05
%--------------------------------------------------------------------------
ipt = 2;
%af
str.af = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/work/';
af(ipt).af=m_af_load(str.af);
%vcnmd
str.nmd = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/';
vcnmd(ipt).nmd = load([str.nmd 'NMDdata_modify.mat']);
vcnmd(ipt).sed = load([str.nmd 'SEDdata_modify.mat']);
% vcnmd(ipt).sed = nmd_convert_data(vcnmd(ipt).nmd,vcnmd(ipt).sed);
%gnmd
str.nmd = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD_AF/1/work/';
gnmd(ipt).nmd = load([str.nmd 'NMDdata.mat']);
gnmd(ipt).sed = load([str.nmd 'SEDdata.mat']);
%vcald
str.alloy = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/';
alloy(ipt).alloy = load([str.alloy 'ALLOY.mat']);
str.ald = '/home/jason/disorder2/lj/ald/m1.1/10x/Data_fullBZ.xls';
vcald(ipt).ald = m_joe_read_data([str.ald]);
vcald(ipt).sedald = m_joe_ald2nmd( vcnmd(ipt).nmd , vcald(ipt).ald );

af(ipt).cond =...
    m_af_cond(...
    af(ipt).af.freq,...
    af(ipt).af.Di(:,2)*vcnmd(ipt).nmd.LJ.sigma^2/vcnmd(ipt).nmd.LJ.tau,...
    af(ipt).af.VOLUME*vcnmd(ipt).nmd.LJ.sigma^3);

vcnmd(ipt).cond =...
    m_ald_cond(...
    vcnmd(ipt).sed.life*vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(ipt).sed.groupvel(:,1)*vcnmd(ipt).nmd.LJ.sigma/vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(ipt).nmd.VOLUME);

af(ipt).cond_scaled =...
    m_af_cond(...
    af(ipt).af.freq,...
    af(ipt).af.Di(:,2)*vcnmd(ipt).nmd.LJ.sigma^2/vcnmd(ipt).nmd.LJ.tau*...
    (vcnmd(ipt).cond / af(ipt).cond),...
    af(ipt).af.VOLUME*vcnmd(ipt).nmd.LJ.sigma^3);


loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    alloy(ipt).alloy.freq'*0.97,...
    alloy(ipt).alloy.life(:,1),'.',...
    vcald(ipt).sedald.freq*0.97,...
    vcald(ipt).sedald.life,'.'...
    )

loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life),'.'...
    )



NUM_BINS = 14;
[af(ipt).freq_bins af(ipt).cond_freq] =...
    m_af_cond_freq(...
    af(1).af.freq,...
    af(1).af.Di(:,2)*(vcnmd(ipt).cond / af(ipt).cond),...
    af(1).af.VOLUME,NUM_BINS)
[vcnmd(ipt).freq_bins vcnmd(ipt).cond_freq] =...
    m_ald_cond_freq(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,...
    vcnmd(ipt).sed.groupvel(:,1),...
    vcnmd(1).nmd.VOLUME/vcnmd(1).nmd.LJ.sigma^3,NUM_BINS)
[vcald(ipt).freq_bins vcald(ipt).cond_freq] =...
    m_ald_cond_freq(...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.life,...
    vcald(ipt).sedald.vel(:,1),...
    vcnmd(1).nmd.VOLUME/vcnmd(1).nmd.LJ.sigma^3,...
    NUM_BINS)

loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    alloy(ipt).alloy.freq'*0.97,...
    alloy(ipt).alloy.life(:,1),'.',...
    vcald(ipt).sedald.freq*0.97,...
    vcald(ipt).sedald.life,'.'...
    )

loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life),'.'...
    )
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------



%--------------------------------------------------------------------------
%amor
%--------------------------------------------------------------------------
%af
str.af = '/home/jason/disorder2/lj/amor/10x/work/';
af(5).af=m_af_load(str.af);

af(5).cond =...
    m_af_cond(...
    af(5).af.freq,...
    af(5).af.Di(:,2)*vcnmd(1).nmd.LJ.sigma^2/vcnmd(1).nmd.LJ.tau,...
    af(5).af.VOLUME*vcnmd(1).nmd.LJ.sigma^3)

loglog(...
    af(5).af.freq/sqrt(1.1),af(5).af.Di(:,2)/sqrt(1.1),'.',...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life.*vcnmd(ipt).sed.groupvel(:,1),'.',...
    af(2).af.freq,af(2).af.Di(:,2)*(vcnmd(ipt).cond / af(ipt).cond),'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life).*vcald(1).sedald.vel(:,1),'.'...
    )


% loglog(...
%     af(1).af.freq,af(1).af.Di(:,2),'.',...
%     af(2).af.freq,af(2).af.Di(:,2),'.',...
%     af(3).af.freq,af(3).af.Di(:,2),'.',...
%     af(4).af.freq,af(4).af.Di(:,2),'.',...
%     af(5).af.freq/sqrt(2),af(5).af.Di(:,2)/sqrt(2),'.'...
%     )





