clear

VIRTUAL_MASS = 1.0800;
constant = m_constant;
%--------------------------------------------------------------------------
%c=0.0
%--------------------------------------------------------------------------
ipt=2;
%vcnmd
str.nmd = '/home/jason/disorder2/si/alloy/0.05/8x/';
vcnmd(ipt).nmd = load([str.nmd 'nmd.mat']);
vcnmd(ipt).sed = load([str.nmd 'SEDdata.mat']);
%vcald
str.alloy = '/home/jason/disorder2/si/alloy/0.05/8x/';
alloy(ipt).alloy = load([str.alloy 'ALLOY.mat']);
str.ald = '/home/jason/disorder2/si/ald/conv/8x/Data_fullBZ.xls';
vcald(ipt).ald = m_joe_read_data_si([str.ald]);
vcald(ipt).sedald =...
    m_joe_ald2nmd_si(...
    vcnmd(2).nmd.NUM_KPTS, vcnmd(2).nmd.kptmodelist ,...
    vcnmd(2).nmd.NUM_MODES , vcald(ipt).ald )

% vcnmd(ipt).sound =...
%     (2/3)*14192.20  + (1/3)*26531.88;
% vcnmd(ipt).sound =...
%     (2/3)*4.48797 + (1/3)*8.39012;
vcnmd(ipt).sound =8433;


loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life),'.'...
    )

NUM_BINS = 15;

[vcnmd(ipt).sed.dosx vcnmd(ipt).sed.dosy] =...
    m_dos(vcnmd(ipt).sed.freq, NUM_BINS , 1)

subplot(4,1,1),...
loglog(vcald(ipt).sedald.freq,vcald(ipt).sedald.vel(:,1).^2,'.')
subplot(4,1,2),...
loglog(...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life),'.',...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    vcnmd(ipt).sed.freq,...
    2*pi./vcnmd(ipt).sed.freq...
    )
subplot(4,1,3),...
loglog(...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life).*vcald(ipt).sedald.vel(:,1).^2,'.',...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life.*vcnmd(ipt).sed.vel(:,1).^2,'.',...
    vcald(ipt).sedald.freq*0.97,...
    ones(length(vcald(ipt).sedald.freq),1)*...
    vcnmd(ipt).sound*(vcnmd(2).nmd.x0.alat/2)*(1/3)*constant.ang2m...
    )
subplot(4,1,4),...
    semilogx(vcnmd(ipt).sed.dosx,vcnmd(ipt).sed.dosy,'.')

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

vcnmd(ipt).cond =...
    m_ald_cond(...
    vcnmd(ipt).sed.life*vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(ipt).sed.groupvel(:,1)*vcnmd(ipt).nmd.LJ.sigma/vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(ipt).nmd.VOLUME);

af(ipt).cond_scaled =...
    m_af_cond(...
    af(ipt).af.freq,...
    af(ipt).af.Di(:,2)*vcnmd(ipt).nmd.LJ.sigma^2/vcnmd(ipt).nmd.LJ.tau*...
    (vcnmd(ipt).cond / af(ipt).cond),...
    af(ipt).af.VOLUME*vcnmd(ipt).nmd.LJ.sigma^3);


loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    alloy(ipt).alloy.freq'*0.97,...
    alloy(ipt).alloy.life(:,1),'.',...
    vcald(ipt).sedald.freq*0.97,...
    vcald(ipt).sedald.life,'.'...
    )

loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life,'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life),'.'...
    )



NUM_BINS = 30;
[af(ipt).freq_bins af(ipt).cond_freq] =...
    m_af_cond_freq(...
    af(ipt).af.freq,...
    af(ipt).af.Di(:,2)*vcnmd(ipt).nmd.LJ.sigma^2/vcnmd(ipt).nmd.LJ.tau*...
    (vcnmd(ipt).cond / af(ipt).cond),...
    af(ipt).af.VOLUME*vcnmd(ipt).nmd.LJ.sigma^3,NUM_BINS);
[vcnmd(ipt).freq_bins vcnmd(ipt).cond_freq] =...
    m_ald_cond_freq(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life*vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(ipt).sed.groupvel(:,1)*vcnmd(ipt).nmd.LJ.sigma/vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(1).nmd.VOLUME,NUM_BINS)
[vcald(ipt).freq_bins vcald(ipt).cond_freq] =...
    m_ald_cond_freq(...
    vcald(ipt).sedald.freq,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life)*vcnmd(ipt).nmd.LJ.tau,...
    vcald(ipt).sedald.vel(:,1)*vcnmd(ipt).nmd.LJ.sigma/vcnmd(ipt).nmd.LJ.tau,...
    vcnmd(1).nmd.VOLUME,...
    NUM_BINS)

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------





ipt=2;
[Iald Jald] =...
    find(...
    vcald(ipt).sedald.freq*0.97 < 5.801 &...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life).*vcald(1).sedald.vel(:,1).^2 < 0.1 );
vcald(1).sedald.vel(Iald,1) = 0;
1./(1./alloy(ipt).alloy.life(Iald,1) +...
    1./vcald(ipt).sedald.life(Iald))


subplot(2,1,1),...
loglog(...
    vcnmd(ipt).sed.freq,...
    vcnmd(ipt).sed.life.*vcnmd(ipt).sed.vel(:,1).^2,'.',...
    vcald(ipt).sedald.freq*0.97,...
    1./(1./alloy(ipt).alloy.life(:,1) +...
    1./vcald(ipt).sedald.life).*vcald(ipt).sedald.vel(:,1).^2,'.',...
    vcald(ipt).sedald.freq*0.97,...
    ones(length(vcald(ipt).sedald.freq),1)*...
    vcnmd(ipt).sound*(vcnmd(2).nmd.x0.alat/2)*(1/3)*constant.ang2m...
    )
subplot(2,1,2),...
    semilogx(...
    vcnmd(ipt).freq_bins,vcnmd(ipt).cond_freq,...
    vcald(ipt).freq_bins,vcald(ipt).cond_freq...
    )





