%function m_ald_taud_si(str_ald,str_nmd_per,str_nmd_vc,str_alloy)
%--------------------------------------------------------------------------
%m_ald_taud(str_ald,str_nmd_perfect,str_nmd_vc,str_alloy)
% m_ald_taud(...
% '/home/jason/disorder/lj/ald/m1.1/10x/Data_fullBZ.xls',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/')
%--------------------------------------------------------------------------

clear

constant = m_constant;
bin_size = 35;

%--------------------------------------------------------------------------
%ALLOY
%-------------------------------------------------------------------------- 
sys_size_ald = [6 10 16 20 24];
for ipt=1:length(sys_size_ald)
    sys_size_ald(ipt)
%ald
str_ald =...
    ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
ald(sys_size_ald(ipt)) = m_joe_read_data_si([str_ald 'Data_fullBZ.xls']);
sedald(sys_size_ald(ipt)) = load([str_ald 'sedald.mat']);
%nmd
str_nmd = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
nmd(sys_size_ald(ipt)).nmd = load([str_nmd 'nmd.mat']);
%alloy
str_nmd_per = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
alloy_05(sys_size_ald(ipt)) = load([str_nmd_per 'ALLOY.mat']);
str_nmd_per = ['/home/jason/disorder2/si/alloy/0.5/' int2str(sys_size_ald(ipt)) 'x/'];
alloy_5(sys_size_ald(ipt)) = load([str_nmd_per 'ALLOY.mat']);
%plot
loglog(...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(ipt)).freq,alloy_05(sys_size_ald(ipt)).life,'.',...
    alloy_5(sys_size_ald(ipt)).freq,alloy_5(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(:)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(:)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(:)),'.'...
    )
%cond
cond.sedald(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life,...
    sedald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald(ipt) = m_ald_cond(...
    ald(sys_size_ald(ipt)).life,...
    ald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald_correct(ipt) =...
    cond.ald(ipt)*...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24))

error(ipt) =...
    cond.sedald(ipt)/cond.ald(ipt)/...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24));

cond.alloy_05(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life),...
    sedald(sys_size_ald(ipt)).vel(:,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));

cond.alloy_5(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life),...
    sedald(sys_size_ald(ipt)).vel(:,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
end

plot(...
    ...
    sys_size_ald , cond.ald,'.',...
    sys_size_ald , cond.ald_correct,'.',...
    sys_size_ald , cond.sedald,'.',...
    sys_size_ald , cond.alloy_05,'.',...
    sys_size_ald , cond.alloy_5,'.'...
    ...
    )

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%--------------------------------------------------------------------------
%ALD
%-------------------------------------------------------------------------- 

sys_size_ald = [6 10 16 20 24 28 32 38];
for ipt=6:length(sys_size_ald)
    sys_size_ald(ipt)
str_ald =...
    ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
ald(sys_size_ald(ipt)) = m_joe_read_data_si([str_ald 'Data_fullBZ.xls']);
sedald(sys_size_ald(ipt)) = load([str_ald 'sedald.mat']);
str_nmd = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
nmd(sys_size_ald(ipt)).nmd = load([str_nmd 'nmd.mat']);
% sedald(sys_size_ald(ipt)) =...
%     m_joe_ald2nmd_si(...
%     nmd(sys_size_ald(ipt)).nmd.NUM_KPTS, nmd(sys_size_ald(ipt)).nmd.kptmodelist ,...
%     nmd(sys_size_ald(ipt)).nmd.NUM_MODES , ald(sys_size_ald(ipt)) );
% save_struct = sedald(sys_size_ald(ipt));
% str_sedald =...
%     ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
% save([str_sedald,'sedald.mat'], '-struct', 'save_struct');
loglog(...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(4)).freq,alloy_05(sys_size_ald(4)).life,'.',...
    alloy_5(sys_size_ald(4)).freq,alloy_5(sys_size_ald(4)).life,'.'...
    )
%cond
cond.sedald(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life,...
    sedald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald(ipt) = m_ald_cond(...
    ald(sys_size_ald(ipt)).life,...
    ald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald_correct(ipt) =...
    cond.ald(ipt)*...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24))
error(ipt) =...
    cond.sedald(ipt)/cond.ald(ipt)/...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24));

%alloy05
data.freq_05(1:15)=[ 1.089E12 2.178E12 3.266E12 4.355E12 5.444E12 6.533E12 ...
    1.05*1.089E12 1.05*2.178E12 1.05*3.266E12 1.05*4.355E12 1.05*5.444E12 1.05*6.533E12 ...
    (2.178E12 + 1.089E12)/2 1.1*(2.178E12 + 1.089E12)/2 0.9*(2.178E12 + 1.089E12)/2 ];
data.life_05(1:15)=0.3*[ 0.3*3.202E-7 0.5*2.001E-8 0.5*3.953E-9 1.251E-9 5.12E-10 2.47E-10 ...
    0.5*1.42E-07 8.895E-9 1.757E-9 1.5*5.55E-10 2.27E-10 1.10E-10 ...
    0.3*(3.202E-7+2.001E-8)/5 0.5*1.1*(3.202E-7+2.001E-8)/5 0.5*0.9*(3.202E-7+2.001E-8)/5 ];
data.freq_05(16:30) = 1.09*data.freq_05(1:15); 
data.freq_05(31:45) = 0.91*data.freq_05(1:15);
data.freq_05(46:60) = 1.04*data.freq_05(1:15); 
data.freq_05(61:75) = 0.96*data.freq_05(1:15);
data.life_05(16:30) = 1.05*data.life_05(1:15); 
data.life_05(31:45) = 0.96*data.life_05(1:15);
data.life_05(46:60) = 1.11*data.life_05(1:15); 
data.life_05(61:75) = 0.91*data.life_05(1:15);
data.freq_5 = data.freq_05/sqrt(1.8/1.08); data.life_5 = data.life_05/sqrt(1.8/1.08);

loglog(...
    data.freq_05,data.life_05,'.',...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(4)).freq,alloy_05(sys_size_ald(4)).life,'.',...
    alloy_5(sys_size_ald(4)).freq,alloy_5(sys_size_ald(4)).life,'.',...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    4.5e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    4e40*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    8e40*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4)...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
loglog(...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e15*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-2),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    1./(...
    1./( 2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4) ) + ...
    1./( 2e15*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-2) ) )...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%-------------------------------------------------------------------------- 
%0.05
%-------------------------------------------------------------------------- 
[Iunique Junique] = unique(alloy_05(sys_size_ald(4)).freq);
yi =...
    interp1(...
    [data.freq_05';alloy_05(sys_size_ald(4)).freq(Junique)],...
    [data.life_05';alloy_05(sys_size_ald(4)).life(Junique)],...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),...
    'nearest');
alloy_05(sys_size_ald(ipt)).life = yi;
Ialloy05 = find( isnan(yi)==0 );
cond.alloy_05(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life(Ialloy05)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
loglog(...
    data.freq_05,data.life_05,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),sedald(sys_size_ald(ipt)).life/sqrt(1.08),'.',...
    alloy_05(24).freq,alloy_05(24).life,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),alloy_05(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life(Ialloy05)),'.'...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%-------------------------------------------------------------------------- 
%0.5
%-------------------------------------------------------------------------- 
[Iunique Junique] = unique(alloy_5(sys_size_ald(4)).freq);
yi =...
    interp1(...
    [data.freq_5';alloy_5(sys_size_ald(4)).freq(Junique)],...
    [data.life_5';alloy_5(sys_size_ald(4)).life(Junique)],...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),...
    'nearest');
alloy_5(sys_size_ald(ipt)).life = yi;
Ialloy5 = find( isnan(yi)==0 );
cond.alloy_5(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
loglog(...
    data.freq_5,data.life_5,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),sedald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_5(24).freq,alloy_5(24).life,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),alloy_5(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),'.'...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
end
plot([sys_size_ald 200],[error 1.0],'.')
pause
semilogy(...
    ...
    1./sys_size_ald , cond.ald,'.',...
    1./sys_size_ald , cond.ald_correct,'.',...
    1./sys_size_ald , cond.sedald,'.',...
    1./sys_size_ald , cond.alloy_05,'.',...
    1./sys_size_ald , cond.alloy_5,'.'...
    ...
    )
pause

gk = m_si_cond_alloy_gk_results;

%--------------------------------------------------------------------------
pause
pause
pause
pause
pause
pause
pause
pause
pause
%-------------------------------------------------------------------------- 
% 
% %--------------------------------------------------------------------------
% %interp
% %-------------------------------------------------------------------------- 
% sys_size_ald = [10 16 20 24 28 32 38 42 46 50 54 58 62 66];
% for ipt = 8:length(sys_size_ald)
% str_ald = ['/home/jason/disorder2/si/ald/conv/' int2str(ipt) 'x/Data_fullBZ.xls'];
% hld(ipt) = m_joe_read_data_si_hld(str_ald);
% str_nmd = ['/home/jason/disorder2/si/alloy/0.05/' int2str(ipt) 'x/'];
% nmd(ipt) = load([str_nmd 'nmd.mat']);
% %sedald(ipt) = m_joe_ald2nmd_si( NUM_KPTS, kptmodelist , NUM_MODES , ald );
% end
% 
% %--------------------------------------------------------------------------
% pause
% pause
% pause
% pause
% pause
% pause
% pause
% pause
% pause
% pause
% %-------------------------------------------------------------------------- 
% 
% 
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% ipt1 = 7; ipt2 = 10; ipt3 = 4;
% [Isort1,Jsort1] = sort(ald(ipt1).freq);
% [Isort2,Jsort2] = sort(hld(ipt2).freq);
% Iinterp1 = find( hld(ipt2).freq <= ald(ipt1).freq(Jsort1(4)) );
% Iinterp2 = find( hld(ipt2).freq >= ald(ipt1).freq(Jsort1(4)) );
% ald(ipt1).freq(Jsort1(1:15))
% ald(ipt1).life(Jsort1(1:15))
% pause
% scale = 2.0;
% hld(ipt2).life_cutoff(1:15) =...
%     1.0e-07 *scale*[
%     0
%     0
%     0
%     0.1551
%     0.1551
%     0.0791
%     0.0791
%     0.1551
%     0.1551
%     0.1551
%     0.0791
%     0.0791
%     0.1551
%     0.0791
%     0.0791];
% hld(ipt2).freq_cutoff(1:15) =...
%     1.0e12 *[
%     0
%     0
%     0
%     1.3127
%     1.3127
%     1.1390
%     1.1390
%     1.3127
%     1.3127
%     1.3127
%     1.1390
%     1.1390
%     1.3127
%     1.1390
%     1.1390];
% 
% data.freq = [hld(ipt2).freq_cutoff(4:15)';...
%     ald(ipt1).freq(Jsort1(4:end))];
% data.life = [hld(ipt2).life_cutoff(4:15)';ald(ipt1).life(Jsort1(4:end))];
% 
% [B,Iunique,J] = unique(data.freq);
% 
% yi =...
%     interp1(...
%     data.freq(Iunique),...
%     data.life(Iunique),...
%     hld(ipt2).freq(Jsort2(4:end)),...
%     'nearest');
% 
% hld(ipt2).life = ones(1,length(hld(ipt2).freq));
% hld(ipt2).life(1:3) = 0;
% hld(ipt2).life(4:length(hld(ipt2).life)) = yi';
% hld(ipt2).life(1:15) = hld(ipt2).life_cutoff(1:15)
% 
% loglog(...
%     hld(ipt2).freq(Jsort2),hld(ipt).life,'.',...
%     ald(ipt1).freq,ald(ipt1).life,'.',...
%     alloy_05(ipt3).freq,alloy_05(ipt3).life,'.',...
%     alloy_5(ipt3).freq,alloy_5(ipt3).life,'.'...
%     )



    


% hld(ipt2).vel = hld(ipt2).vel(Jsort2,:);

% VOLUME(1) = ((5.43E-10)^3)*(10^3);
% VOLUME(2) = ((5.43E-10)^3)*(16^3);
% VOLUME(3) = ((5.43E-10)^3)*(20^3);
% VOLUME(4) = ((5.43E-10)^3)*(24^3);
% VOLUME(5) = ((5.43E-10)^3)*(28^3);
% VOLUME(6) = ((5.43E-10)^3)*(32^3);
% VOLUME(7) = ((5.43E-10)^3)*(38^3);
% 
% VOLUME(10) = ((5.43E-10)^3)*(50^3);
% 
% cond = m_ald_cond(hld(ipt).life',hld(ipt).vel(:,1),VOLUME(10))
% 
% cond = m_ald_cond(ald(1).life,ald(1).vel(:,1),VOLUME(1))
% cond = m_ald_cond(ald(2).life,ald(2).vel(:,1),VOLUME(2))
% cond = m_ald_cond(ald(3).life,ald(3).vel(:,1),VOLUME(3))
% cond = m_ald_cond(ald(4).life,ald(4).vel(:,1),VOLUME(4))
% cond = m_ald_cond(ald(5).life,ald(5).vel(:,1),VOLUME(5))
% cond = m_ald_cond(ald(6).life,ald(6).vel(:,1),VOLUME(6))
% cond = m_ald_cond(ald(7).life,ald(7).vel(:,1),VOLUME(7))

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 



















% 
% 
% 
% %--------------------------------------------------------------------------
% %0.05
% %-------------------------------------------------------------------------- 
% sys_size = '22x';
% ipt = 1;
% str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
% str_alloy = ['/home/jason/disorder2/si/alloy/0.001/' sys_size '/'];
% str_nmd_per = ['/home/jason/disorder2/si/alloy/0.001/' sys_size '/'];
% ald = m_joe_read_data_si(str_ald);
% nmd_per(ipt)=load(strcat(str_nmd_per,'nmd.mat'));
% sedald(ipt) = m_joe_ald2nmd_si( nmd_per(ipt) , ald );
% sedald = m_joe_ald2nmd_si( NUM_KPTS, kptmodelist , NUM_MODES , ald )
% alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));
% 
% cond(ipt).nmd_per =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [nmd_freq(ipt).bins nmd_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% cond(ipt).ald =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [ald_freq(ipt).bins ald_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% loglog(...
%     sedald(ipt).freq*sqrt(nmd_per(ipt).x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm),'.',...
%     alloy(ipt).freq,...
%     alloy(ipt).life,'.',...
%     alloy(ipt).freq,...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E42*alloy(ipt).freq.^(-4)...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% %--------------------------------------------------------------------------
% %0.01
% %-------------------------------------------------------------------------- 
% ipt = 2;
% str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
% str_alloy = ['/home/jason/disorder2/si/alloy/0.01/' sys_size '/'];
% str_nmd_per = ['/home/jason/disorder2/si/alloy/0.01/' sys_size '/'];
% ald = m_joe_read_data_si(str_ald);
% nmd_per(ipt)=load(strcat(str_nmd_per,'nmd.mat'));
% sedald(ipt) = m_joe_ald2nmd_si( nmd_per(ipt) , ald );
% alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));
% 
% cond(ipt).nmd_per =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [nmd_freq(ipt).bins nmd_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% cond(ipt).ald =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [ald_freq(ipt).bins ald_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% loglog(...
%     sedald(ipt).freq*sqrt(nmd_per(ipt).x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm),'.',...
%     alloy(ipt).freq,...
%     alloy(ipt).life,'.',...
%     alloy(ipt).freq,...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E42*alloy(ipt).freq.^(-4)...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
%  
% %--------------------------------------------------------------------------
% %0.05
% %-------------------------------------------------------------------------- 
% ipt = 3;
% str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
% str_alloy = ['/home/jason/disorder2/si/alloy/0.05/' sys_size '/'];
% str_nmd_per = ['/home/jason/disorder2/si/alloy/0.05/' sys_size '/'];
% ald = m_joe_read_data_si(str_ald);
% nmd_per(ipt)=load(strcat(str_nmd_per,'nmd.mat'));
% sedald(ipt) = m_joe_ald2nmd_si( nmd_per(ipt) , ald );
% alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));
% 
% cond(ipt).nmd_per =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [nmd_freq(ipt).bins nmd_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% cond(ipt).ald =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [ald_freq(ipt).bins ald_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% loglog(...
%     sedald(ipt).freq*sqrt(nmd_per(ipt).x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm),'.',...
%     alloy(ipt).freq,...
%     alloy(ipt).life,'.',...
%     alloy(ipt).freq,...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E42*alloy(ipt).freq.^(-4)...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% %--------------------------------------------------------------------------
% %0.15
% %-------------------------------------------------------------------------- 
% ipt = 4;
% str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
% str_alloy = ['/home/jason/disorder2/si/alloy/0.15/' sys_size '/'];
% str_nmd_per = ['/home/jason/disorder2/si/alloy/0.15/' sys_size '/'];
% ald = m_joe_read_data_si(str_ald);
% nmd_per(ipt)=load(strcat(str_nmd_per,'nmd.mat'));
% sedald(ipt) = m_joe_ald2nmd_si( nmd_per(ipt) , ald );
% alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));
% 
% cond(ipt).nmd_per =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [nmd_freq(ipt).bins nmd_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% cond(ipt).ald =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [ald_freq(ipt).bins ald_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% loglog(...
%     sedald(ipt).freq*sqrt(nmd_per(ipt).x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm),'.',...
%     alloy(ipt).freq,...
%     alloy(ipt).life,'.',...
%     alloy(ipt).freq,...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E42*alloy(ipt).freq.^(-4)...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% %--------------------------------------------------------------------------
% %0.5
% %-------------------------------------------------------------------------- 
% ipt = 5;
% str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
% str_alloy = ['/home/jason/disorder2/si/alloy/0.5/' sys_size '/'];
% str_nmd_per = ['/home/jason/disorder2/si/alloy/0.5/' sys_size '/'];
% ald = m_joe_read_data_si(str_ald);
% nmd_per(ipt)=load(strcat(str_nmd_per,'nmd.mat'));
% sedald(ipt) = m_joe_ald2nmd_si( nmd_per(ipt) , ald );
% alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));
% 
% cond(ipt).nmd_per =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [nmd_freq(ipt).bins nmd_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% cond(ipt).ald =...
%     m_ald_cond(...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3)
% [ald_freq(ipt).bins ald_cond(ipt).freq] =...
%     m_ald_cond_freq(...
%     sedald(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),...
%     sedald(ipt).vel(:,1)/sqrt(nmd_per(ipt).x0.vm),...
%     nmd_per(ipt).x0.VOLUME*constant.ang2m^3,...
%     bin_size);
% loglog(...
%     sedald(ipt).freq*sqrt(nmd_per(ipt).x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm),'.',...
%     alloy(ipt).freq,...
%     alloy(ipt).life,'.',...
%     alloy(ipt).freq,...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(ipt).x0.vm),...
%     1E42*alloy(ipt).freq.^(-4)...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% subplot(2,1,1),...
%     plot(...
%     nmd_freq(1).bins,nmd_cond(1).freq/sum(nmd_cond(1).freq),...
%     ald_freq(1).bins,ald_cond(1).freq/sum(ald_cond(1).freq),...
%     ald_freq(5).bins,ald_cond(5).freq/sum(ald_cond(5).freq)...
%     )
% subplot(2,1,2),...
%     plot(...
%     nmd_freq(1).bins,cumtrapz(nmd_cond(1).freq)/sum(nmd_cond(1).freq),...
%     ald_freq(1).bins,cumtrapz(ald_cond(1).freq)/sum(ald_cond(1).freq),...
%     ald_freq(5).bins,cumtrapz(ald_cond(5).freq)/sum(ald_cond(5).freq)...
%     )
% 
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% ipt=1;
% subplot(2,1,1),...
%     loglog(...
%     sedald(ipt).freq/sqrt(nmd_per(1).x0.vm),sedald(ipt).life/sqrt(nmd_per(1).x0.vm),'.',...
%     alloy(ipt).freq,alloy(ipt).life,'.',...
%     alloy(ipt).freq,(1./( (1./(sedald(ipt).life/sqrt(nmd_per(ipt).x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) )),'.',...
%     alloy(5).freq,alloy(5).life,'.',...
%     alloy(5).freq,(1./( (1./(sedald(5).life/sqrt(nmd_per(5).x0.vm))) +...
%     (1./alloy(5).life(:,1)) )),'.',...
%     alloy(ipt).freq/sqrt(nmd_per(1).x0.vm),1E17*alloy(ipt).freq.^(-2),...
%     alloy(ipt).freq/sqrt(nmd_per(1).x0.vm),1E42*alloy(ipt).freq.^(-4)...
%     )
% subplot(2,1,2),...
%     semilogx(...
%     nmd_freq(1).bins,cumtrapz(nmd_cond(1).freq)/sum(nmd_cond(1).freq),...
%     ald_freq(1).bins,cumtrapz(ald_cond(1).freq)/sum(ald_cond(1).freq),...
%     ald_freq(5).bins,cumtrapz(ald_cond(5).freq)/sum(ald_cond(5).freq)...
%     )



































% m_si_cond_alloy_tau_intk_createfigure(X1, Y1, X2, YMatrix1, X3, YMatrix2,...
%     X4, YMatrix3, X5, YMatrix4, X6, Y2)
% 
% m_si_cond_alloy_tau_intk_createfigure(...
%     sedald(ipt).freq*sqrt(nmd_per.x0.vm),...
%     sedald(ipt).life/sqrt(nmd_per.x0.vm),...
%     alloy(ipt).freq,...
%     [alloy(ipt).life ...
%     (1./( (1./(sedald(ipt).life/sqrt(nmd_per.x0.vm))) +...
%     (1./alloy(ipt).life(:,1)) ))],... 
%     alloy(5).freq,... 
%     [alloy(5).life ...
%     (1./( (1./(sedald(5).life/sqrt(nmd_per.x0.vm))) +...
%     (1./alloy(5).life(:,1)) ))],...
%     alloy(ipt).freq/sqrt(nmd_per.x0.vm),...
%     [1E17*alloy(ipt).freq.^(-2) ...
%     1E42*alloy(ipt).freq.^(-4)],...
%     nmd_freq(1).bins,...
%     
%     )


% 
% sed_per.ald
% alloy
% 
% loglog(...
%     sed_per.ald.freq,sed_per.ald.life,'.',...
%     sed_per.ald.freq,...
%     1./( (1./sed_per.ald.life) + (1./alloy.life(:,1)) ),'.',...
%     alloy.freq,alloy.life(:,1),'.'...
%     )
% 
% size(alloy.life)
% size(sed_per.ald.life)
% 
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% loglog(...
%     sed_vc.freq,sed_vc.life,'.',...
%     sed_per.ald.freq,...
%     1./( (1./sed_per.ald.life) + (1./alloy.life(:,1)) ),'.'...
%     )
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% cond_sed_per =...
%     m_ald_cond(...
%     sed_per.life*lj.tau,...
%     sed_per.groupvel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME)
% 
% [sed_per_freq_bins sed_per_cond_freq] =...
%     m_ald_cond_freq(...
%     sed_per.freq,sed_per.life*lj.tau,...
%     sed_per.groupvel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME,20)
% 
% subplot(2,1,1),...
%     loglog(sed_per_freq_bins,sed_per_cond_freq)
% size(sed_per_freq_bins)
% size(sed_per_cond_freq)
% hold on
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% cond_sed_vc =...
%     m_ald_cond(...
%     sed_vc.life*lj.tau,...
%     sed_vc.groupvel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME)
% 
% [sed_vc_freq_bins sed_vc_cond_freq] =...
%     m_ald_cond_freq(...
%     sed_vc.freq,sed_vc.life*lj.tau,...
%     sed_vc.groupvel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME,20)
% 
% subplot(2,1,1),...
%     loglog(sed_vc_freq_bins,sed_vc_cond_freq)
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% cond_ald =...
%     m_ald_cond(...
%     (1./( (1./sed_per.ald.life) + (1./alloy.life(:,1)) ))*lj.tau,...
%     sed_per.ald.vel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME)
% [ald_freq_bins ald_cond_freq] =...
%     m_ald_cond_freq(...
%     sed_per.ald.freq,...
%     (1./( (1./sed_per.ald.life) + (1./alloy.life(:,1)) ))*lj.tau,...
%     sed_per.ald.vel(:,1)*(lj.sigma/lj.tau),...
%     nmd_per.VOLUME,20)
% 
% subplot(2,1,1),...
%     loglog(ald_freq_bins,ald_cond_freq)
% %--------------------------------------------------------------------------
% pause
% %-------------------------------------------------------------------------- 
% 
% subplot(2,1,2),...
%     loglog(...
%     sed_vc.freq,sed_vc.life,'.',...
%     sed_per.ald.freq,sed_per.ald.life,'.',...
%     0.97*sed_per.ald.freq,...
%     1./( (1./sed_per.ald.life) + (1./alloy.life(:,1)) ),'.',...
%     sed_per.ald.freq , 2*pi./sed_per.ald.freq...
%     )
% 
% hold off




%end
