%function m_ald_taud(str_ald,str_nmd_per,str_nmd_vc,str_alloy)
%--------------------------------------------------------------------------
%m_ald_taud(str_ald,str_nmd_perfect,str_nmd_vc,str_alloy)
% m_ald_taud(...
% '/home/jason/disorder/lj/ald/m1.1/10x/Data_fullBZ.xls',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/')
%--------------------------------------------------------------------------
clear

ipt=1;
str(1).conc = '0.05'; str(2).conc = '0.15'; str(3).conc = '0.5'; 

str_ald = '/home/jason/disorder2/lj/ald/m2/10x/Data_fullBZ.xls';
str_nmd_per = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/';
str_nmd_vc = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/';
str_alloy = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/';

lj = m_lj; constant = m_constant;
bin_size = 25;
ald(ipt) = m_joe_read_data(str_ald);

nmd_per(ipt)=load(strcat(str_nmd_per,'NMDdata.mat'));
sed_per_load=load(strcat(str_nmd_per,'SEDdata.mat'));
sed_per(ipt) = nmd_convert_data(nmd_per(ipt),sed_per_load);
nmd_vc(ipt)=load(strcat(str_nmd_vc,'NMDdata.mat'));
sed_vc(ipt)=load(strcat(str_nmd_vc,'SEDdata.mat'));
sed_vc(ipt) = nmd_convert_data(nmd_vc(ipt),sed_vc(ipt))

sedald(ipt) = m_joe_ald2nmd( nmd_per(ipt) , ald(ipt) );
alloy(ipt) = load(strcat(str_alloy,'ALLOY.mat'));


loglog(...
    sedald(ipt).freq,sedald(ipt).life,'.',...
    sed_vc(ipt).freq,sed_vc(ipt).life,'.',...
    sedald(ipt).freq,...
    1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ),'.',...
    alloy(ipt).freq,alloy(ipt).life(:,1),'.'...
    )
pause
cond_sed_per =...
    m_ald_cond(...
    sed_per(ipt).life*lj.tau,...
    sed_per(ipt).groupvel(:,1)*(lj.sigma/lj.tau),...
    nmd_per(ipt).VOLUME)

[sed_per_freq(ipt).bins sed_per_cond(ipt).freq] =...
    m_ald_cond_freq(...
    sed_per(ipt).freq,sed_per(ipt).life*lj.tau,...
    sed_per(ipt).groupvel(:,1)*(lj.sigma/lj.tau),...
    nmd_per(ipt).VOLUME,bin_size)

subplot(2,1,1),...
    semilogx(sed_per_freq(ipt).bins,sed_per_cond(ipt).freq)
subplot(2,1,2),...
    semilogx(...
    sed_per_freq(ipt).bins,...
    cumtrapz(sed_per_cond(ipt).freq)/sum(sed_per_cond(ipt).freq)...
    )
pause
subplot(2,1,1),...
    loglog(sed_per(ipt).freq,sed_per(ipt).life,'.')
subplot(2,1,2),...
    semilogx(...
    sed_per_freq(ipt).bins,...
    cumtrapz(sed_per_cond(ipt).freq)/sum(sed_per_cond(ipt).freq)...
    )

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

loglog(...
    sedald(ipt).freq,sedald(ipt).life,'.',...
    sed_vc(ipt).freq,sed_vc(ipt).life,'.',...
    sedald(ipt).freq,...
    1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ),'.',...
    alloy(ipt).freq,alloy(ipt).life(:,1),'.'...
    )
pause
cond_sed_vc =...
    m_ald_cond(...
    sed_vc(ipt).life*lj.tau,...
    sed_vc(ipt).groupvel(:,1)*(lj.sigma/lj.tau),...
    nmd_per(ipt).VOLUME)

[sed_vc_freq(ipt).bins sed_vc_cond(ipt).freq] =...
    m_ald_cond_freq(...
    sed_vc(ipt).freq,sed_vc(ipt).life*lj.tau,...
    sed_vc(ipt).groupvel(:,1)*(lj.sigma/lj.tau),...
    nmd_per(ipt).VOLUME,bin_size)

subplot(2,1,1),...
    semilogx(sed_vc_freq(ipt).bins,sed_vc_cond(ipt).freq)
subplot(2,1,2),...
    semilogx(...
    sed_vc_freq(ipt).bins,...
    cumtrapz(sed_vc_cond(ipt).freq)/sum(sed_vc_cond(ipt).freq)...
    )
pause
subplot(2,1,1),...
    loglog(sed_vc(ipt).freq,sed_vc(ipt).life,'.')
subplot(2,1,2),...
    semilogx(...
    sed_vc_freq(ipt).bins,...
    cumtrapz(sed_vc_cond(ipt).freq)/sum(sed_vc_cond(ipt).freq)...
    )

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

loglog(...
    sedald(ipt).freq,sedald(ipt).life,'.',...
    sed_vc(ipt).freq,sed_vc(ipt).life,'.',...
    sedald(ipt).freq,...
    1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ),'.',...
    alloy(ipt).freq,alloy(ipt).life(:,1),'.'...
    )
pause

cond_ald =...
    m_ald_cond(...
    (1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ))*lj.tau,...
    sedald(ipt).vel(:,1)*(lj.sigma/lj.tau),...
    nmd_per.VOLUME)
[ald_freq(ipt).bins ald_cond(ipt).freq] =...
    m_ald_cond_freq(...
    sedald(ipt).freq,...
    (1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ))*lj.tau,...
    sedald(ipt).vel(:,1)*(lj.sigma/lj.tau),...
    nmd_per(ipt).VOLUME,bin_size)

subplot(2,1,1),...
    semilogx(ald_freq(ipt).bins,ald_cond(ipt).freq)
subplot(2,1,2),...
    semilogx(...
    ald_freq(ipt).bins,...
    cumtrapz(ald_cond(ipt).freq)/sum(ald_cond(ipt).freq)...
    )
pause
subplot(2,1,1),...
    loglog(sedald(ipt).freq,...
    1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ),'.')
subplot(2,1,2),...
    semilogx(...
    ald_freq(ipt).bins,...
    cumtrapz(ald_cond(ipt).freq)/sum(ald_cond(ipt).freq)...
    )

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

subplot(2,1,1),...
    loglog(...
    sed_vc(ipt).freq,sed_vc(ipt).life,'.',...
    sedald(ipt).freq,...
    1./( (1./sedald(ipt).life) + (1./alloy(ipt).life(:,1)) ),'.'...
    )
subplot(2,1,2),...
    semilogx(...
    sed_vc_freq(ipt).bins,...
    cumtrapz(sed_vc_cond(ipt).freq)/sum(sed_vc_cond(ipt).freq),...
    ald_freq(ipt).bins,...
    cumtrapz(ald_cond(ipt).freq)/sum(ald_cond(ipt).freq)...
    )


%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 




subplot(2,1,1),...
    semilogx(sed_per_freq(ipt).bins,sed_per_cond(ipt).freq/sum(sed_per_cond(ipt).freq),...
    sed_vc_freq(ipt).bins,sed_vc_cond(ipt).freq/sum(sed_vc_cond(ipt).freq),...
    ald_freq(ipt).bins,ald_cond(ipt).freq/sum(ald_cond(ipt).freq) )
subplot(2,1,2),...
    semilogx(...
    sed_per_freq(ipt).bins,...
    cumtrapz(sed_per_cond(ipt).freq)/sum(sed_per_cond(ipt).freq),...
    sed_vc_freq(ipt).bins,...
    cumtrapz(sed_vc_cond(ipt).freq)/sum(sed_vc_cond(ipt).freq),...
    ald_freq(ipt).bins,...
    cumtrapz(ald_cond(ipt).freq)/sum(ald_cond(ipt).freq)...
    )



hold on
subplot(2,1,1),...
    semilogx(...
    sed_vc_freq(ipt).bins,sed_vc_cond(ipt).freq...
    )
subplot(2,1,2),...
    semilogx(...
    sed_vc_freq(ipt).bins,...
    cumtrapz(sed_vc_cond(ipt).freq)/sum(sed_vc_cond(ipt).freq)...
    )

subplot(2,1,1),...
    semilogx(ald_freq(ipt).bins,ald_cond(ipt).freq)
subplot(2,1,2),...
    semilogx(...
    ald_freq(ipt).bins,...
    cumtrapz(ald_cond(ipt).freq)/sum(ald_cond(ipt).freq)...
    )
hold off



%end