function m_alloy_dos_vc_gamma_compare_createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-Sep-2012 20:42:31

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.600000000000002 0.452222222222222 2.85555555555556 3.145],...
    'FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'DisplayName','$VC$');

% Create plot
plot(X2,Y2,'Parent',axes1,'DisplayName','supercell');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',15);

% Create ylabel
ylabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',15);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Visible','off','Units','inches',...
    'Position',[0.758333333333337 0.7 0.530555555555552 0.470833333333332]);

