clear

str_alloy = '/home/jason/disorder2/si/alloy/0.05/12x/';

alloy(1) = load([str_alloy 'ALLOY.mat']);
alloy(2) = load([str_alloy 'ALLOY_orig_pkheight_0.45.mat']);


loglog(...
    alloy(1).freq,alloy(1).life,'.',...
    alloy(2).freq,alloy(2).life,'.',...
    linspace(min(alloy(1).freq),max(alloy(1).freq)),...
    1E41*linspace(min(alloy(1).freq),max(alloy(1).freq)).^(-4)...
    )

pause

plot(...
    alloy(1).freq,alloy(1).life./alloy(2).life,'.'...
    )

