clear
constant = m_constant;
str.main = '/home/jason/disorder2/si/alloy/0.05/24x/';
NUM_BINS = 1000; BROADEN = 1000;
m1 = 1; m2=2.6; c = 0.05; vm = (1-c)*m1 + c*m2;
%si
nmd =...
    load([str.main 'nmd.mat']);
% sed =...
%     load(['/home/jason/disorder2/si/alloy/0.5/20x/' 'SEDdata.mat']);
alloy =...
    load([str.main 'ALLOY.mat']);
g(1) =...
    (1-c)*((1 - (m1/vm) )^1) + c*((1 - (m2/vm) )^1);
g(2) =...
    (1-c)*((1 - (m1/vm) )^2) + c*((1 - (m2/vm) )^2);
g(3) =...
    (1-c)*((1 - (m1/vm) )^3) + c*((1 - (m2/vm) )^3);
g(4) =...
    (1-c)*((1 - (m1/vm) )^4) + c*((1 - (m2/vm) )^4);
tamura =...
    m_alloy_tamura_highorder_Iw(...
    g,nmd.freq*constant.s2ps,nmd.x0.NUM_UCELL_COPIES,NUM_BINS,BROADEN);
[tamura.dosx tamura.dosy] = m_dos(nmd.freq*constant.s2ps, 17 , 1);
subplot(4,1,1),...
semilogx(...
    tamura.dosx,tamura.dosy,'.'...
    )
subplot(4,1,2),...
loglog(...
    tamura.freq_range,abs(tamura.dw),'.'...
    )
subplot(4,1,3),...
loglog(...    
    tamura.freq_range,tamura.life,'.',...
    alloy.freq*constant.s2ps,alloy.life/constant.s2ps,'.'...
    )
subplot(4,1,4),...
loglog(...    
    tamura.freq_range,abs(tamura.g3Iwg2),'.',...
    tamura.freq_range,abs(tamura.g4Iwg2),'.'...
    )
save( [ str.main 'tamura_' int2str(BROADEN) '.mat' ], '-struct', 'tamura');

%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------
