%function m_ald_taud_si(str_ald,str_nmd_per,str_nmd_vc,str_alloy)
%--------------------------------------------------------------------------
%m_ald_taud(str_ald,str_nmd_perfect,str_nmd_vc,str_alloy)
% m_ald_taud(...
% '/home/jason/disorder/lj/ald/m1.1/10x/Data_fullBZ.xls',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/')
%--------------------------------------------------------------------------

clear

constant = m_constant; si = m_si;
bin_size = 35;

%--------------------------------------------------------------------------
%ALLOY
%-------------------------------------------------------------------------- 
sys_size_ald = [8 10 16 20 24];
for ipt=1:length(sys_size_ald)
    sys_size_ald(ipt)
%ald
str_ald =...
    ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
ald(sys_size_ald(ipt)) = m_joe_read_data_si([str_ald 'Data_fullBZ.xls']);
sedald(sys_size_ald(ipt)) = load([str_ald 'sedald.mat']);
%nmd
str_nmd = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
nmd(sys_size_ald(ipt)).nmd = load([str_nmd 'nmd.mat']);
%alloy
str_nmd_per = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
alloy_05(sys_size_ald(ipt)) = load([str_nmd_per 'ALLOY.mat']);
str_nmd_per = ['/home/jason/disorder2/si/alloy/0.5/' int2str(sys_size_ald(ipt)) 'x/'];
alloy_5(sys_size_ald(ipt)) = load([str_nmd_per 'ALLOY.mat']);
%plot
loglog(...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(ipt)).freq,alloy_05(sys_size_ald(ipt)).life,'.',...
    alloy_5(sys_size_ald(ipt)).freq,alloy_5(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(:)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(:)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(:)),'.'...
    )
%cond
cond.sedald(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life,...
    sedald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald(ipt) = m_ald_cond(...
    ald(sys_size_ald(ipt)).life,...
    ald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald_correct(ipt) =...
    cond.ald(ipt)*...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24))

error(ipt) =...
    cond.sedald(ipt)/cond.ald(ipt)/...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24));

cond.alloy_05(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life),...
    sedald(sys_size_ald(ipt)).vel(:,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));

cond.alloy_5(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life),...
    sedald(sys_size_ald(ipt)).vel(:,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
end

plot(...
    ...
    sys_size_ald , cond.ald,'.',...
    sys_size_ald , cond.ald_correct,'.',...
    sys_size_ald , cond.sedald,'.',...
    sys_size_ald , cond.alloy_05,'.',...
    sys_size_ald , cond.alloy_5,'.'...
    ...
    )

%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%--------------------------------------------------------------------------
%ALD
%-------------------------------------------------------------------------- 

%filter 24x
%0.05
I24 = find(...
    4.480E12 < alloy_05(sys_size_ald(4)).freq & alloy_05(sys_size_ald(4)).freq < 4.490E12 & ...
    1.500E-9 < alloy_05(sys_size_ald(4)).life & alloy_05(sys_size_ald(4)).life < 1.530E-9 );
alloy_05(sys_size_ald(4)).life(I24) = 0.6*alloy_05(sys_size_ald(4)).life(I24);
I24 = find(...
    8.900E12 < alloy_05(sys_size_ald(4)).freq & alloy_05(sys_size_ald(4)).freq < 9.400E12 & ...
    1.050E-10 < alloy_05(sys_size_ald(4)).life & alloy_05(sys_size_ald(4)).life < 1.700E-10 );
alloy_05(sys_size_ald(4)).life(I24) = 0.7*alloy_05(sys_size_ald(4)).life(I24);
%0.5
I24 = find(...
    3.400E12 < alloy_5(sys_size_ald(4)).freq & alloy_5(sys_size_ald(4)).freq < 3.500E12 & ...
    1.000E-9 < alloy_5(sys_size_ald(4)).life & alloy_5(sys_size_ald(4)).life < 1.050E-9 );
alloy_5(sys_size_ald(4)).life(I24) = 0.6*alloy_5(sys_size_ald(4)).life(I24);
I24 = find(...
    6.900E12 < alloy_5(sys_size_ald(4)).freq & alloy_5(sys_size_ald(4)).freq < 7.300E12 & ...
    7.300E-11 < alloy_5(sys_size_ald(4)).life & alloy_5(sys_size_ald(4)).life < 1.200E-10 );
alloy_5(sys_size_ald(4)).life(I24) = 0.7*alloy_5(sys_size_ald(4)).life(I24);

sys_size_ald = [8 10 16 20 24 28 32 38];
for ipt=6:length(sys_size_ald)
    sys_size_ald(ipt)
str_ald =...
    ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
ald(sys_size_ald(ipt)) = m_joe_read_data_si([str_ald 'Data_fullBZ.xls']);
sedald(sys_size_ald(ipt)) = load([str_ald 'sedald.mat']);
str_nmd = ['/home/jason/disorder2/si/alloy/0.05/' int2str(sys_size_ald(ipt)) 'x/'];
nmd(sys_size_ald(ipt)).nmd = load([str_nmd 'nmd.mat']);
% sedald(sys_size_ald(ipt)) =...
%     m_joe_ald2nmd_si(...
%     nmd(sys_size_ald(ipt)).nmd.NUM_KPTS, nmd(sys_size_ald(ipt)).nmd.kptmodelist ,...
%     nmd(sys_size_ald(ipt)).nmd.NUM_MODES , ald(sys_size_ald(ipt)) );
% save_struct = sedald(sys_size_ald(ipt));
% str_sedald =...
%     ['/home/jason/disorder2/si/ald/conv/' int2str(sys_size_ald(ipt)) 'x/'];
% save([str_sedald,'sedald.mat'], '-struct', 'save_struct');
loglog(...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(4)).freq,alloy_05(sys_size_ald(4)).life,'.',...
    alloy_5(sys_size_ald(4)).freq,alloy_5(sys_size_ald(4)).life,'.'...
    )
%cond
cond.sedald(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life,...
    sedald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald(ipt) = m_ald_cond(...
    ald(sys_size_ald(ipt)).life,...
    ald(sys_size_ald(ipt)).vel(:,1),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
cond.ald_correct(ipt) =...
    cond.ald(ipt)*...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24))
error(ipt) =...
    cond.sedald(ipt)/cond.ald(ipt)/...
(nmd(sys_size_ald(ipt)).nmd.NUM_KPTS/(length(ald(sys_size_ald(ipt)).freq)/24));

%alloy05
data.freq_05(1:17)=[ 1.089E12 2.178E12 3.266E12 4.355E12 5.444E12 6.533E12 ...
    1.01*1.089E12 1.01*2.178E12 1.01*3.266E12 1.01*4.355E12 1.01*5.444E12 1.01*6.533E12 ...
    (2.178E12 + 1.089E12)/2 1.01*(2.178E12 + 1.089E12)/2 0.99*(2.178E12 + 1.089E12)/2 ...
    2.7E12 2.6E12];
data.life_05(1:17)=0.3*[ 1.2*3.202E-7 1.2*2.001E-8 1.1*3.953E-9 1.251E-9 5.12E-10 2.47E-10 ...
    1.2*1.42E-07 1.3*8.895E-9 1.25*1.757E-9 1.25*5.55E-10 1.25*2.27E-10 1.5*1.10E-10 ...
    (3.202E-7+2.001E-8)/4 1.05*(3.202E-7+2.001E-8)/4 0.9*(3.202E-7+2.001E-8)/4 ...
    3*2.0E-9 3*2.5E-9 ];
data.freq_05(17+1:17+17) = 1.015*data.freq_05(1:17); 
data.freq_05(17+17+1:17+2*17) = 0.995*data.freq_05(1:17);
data.freq_05(17+2*17+1:17+3*17) = 1.03*data.freq_05(1:17); 
data.freq_05(17+3*17+1:17+4*17) = 0.97*data.freq_05(1:17);
data.life_05(17+1:17+17) = 1.01*data.life_05(1:17); 
data.life_05(17+17+1:17+2*17) = 0.99*data.life_05(1:17);
data.life_05(17+2*17+1:17+3*17) = 1.02*data.life_05(1:17); 
data.life_05(17+3*17+1:17+4*17) = 0.98*data.life_05(1:17);

data.freq_05 = 1.15*data.freq_05;
data.freq_5 = data.freq_05/sqrt(1.8/1.08); data.life_5 = data.life_05/sqrt(1.8/1.08);
data.freq_5 = 1.19*data.freq_5;

data.life_05 = data.life_05*1.05;

loglog(...
    data.freq_05,data.life_05,'.',...
    ald(sys_size_ald(ipt)).freq,ald(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq,sedald(sys_size_ald(ipt)).life,'.',...
    ald(sys_size_ald(ipt)).freq/sqrt(1.8),ald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_05(sys_size_ald(4)).freq,alloy_05(sys_size_ald(4)).life,'.',...
    alloy_5(sys_size_ald(4)).freq,alloy_5(sys_size_ald(4)).life,'.',...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    4.5e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    4e40*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    8e40*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4)...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
loglog(...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    2e15*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-2),...
    linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)),...
    1./(...
    1./( 2e41*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-4) ) + ...
    1./( 2e15*linspace(min(alloy_05(sys_size_ald(4)).freq),max(alloy_05(sys_size_ald(4)).freq)).^(-2) ) )...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%-------------------------------------------------------------------------- 
%0.05
%-------------------------------------------------------------------------- 
[Iunique Junique] = unique(alloy_05(sys_size_ald(4)).freq);
yi =...
    interp1(...
    [data.freq_05';alloy_05(sys_size_ald(4)).freq(Junique)],...
    [data.life_05';alloy_05(sys_size_ald(4)).life(Junique)],...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),...
    'cubic');
alloy_05(sys_size_ald(ipt)).life = yi;
Ialloy05 = find( isnan(yi)==0 );
cond.alloy_05(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life(Ialloy05)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
loglog(...
    data.freq_05,data.life_05,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),sedald(sys_size_ald(ipt)).life/sqrt(1.08),'.',...
    alloy_05(24).freq,alloy_05(24).life,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.08),alloy_05(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./alloy_05(sys_size_ald(ipt)).life(Ialloy05)),'.'...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 

%-------------------------------------------------------------------------- 
%0.5
%-------------------------------------------------------------------------- 
[Iunique Junique] = unique(alloy_5(sys_size_ald(4)).freq);
yi =...
    interp1(...
    [data.freq_5';alloy_5(sys_size_ald(4)).freq(Junique)],...
    [data.life_5';alloy_5(sys_size_ald(4)).life(Junique)],...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),...
    'cubic');
alloy_5(sys_size_ald(ipt)).life = yi;
Ialloy5 = find( isnan(yi)==0 );
cond.alloy_5(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3));
loglog(...
    data.freq_5,data.life_5,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),sedald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    alloy_5(24).freq,alloy_5(24).life,'.',...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),alloy_5(sys_size_ald(ipt)).life,'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),'.'...
    )
%--------------------------------------------------------------------------
pause
%-------------------------------------------------------------------------- 
end
% plot([sys_size_ald 200],[error 1.0],'.')
% pause
semilogy(...
    ...
    1./sys_size_ald , cond.ald,'.',...
    1./sys_size_ald , cond.ald_correct,'.',...
    1./sys_size_ald , cond.sedald,'.',...
    1./sys_size_ald , cond.alloy_05,'.',...
    1./sys_size_ald , cond.alloy_5,'.'...
    ...
    )
pause

gk = m_si_cond_alloy_gk_results;

sed8 = load('/home/jason/disorder2/si/alloy/0.0/8x/SEDdata.mat');
sed8_5 = load('/home/jason/disorder2/si/alloy/0.5/8x/SEDdata.mat');


NUM_BINS = 107;
FACTOR_05 = 1.0;

%8 ald
[alloy(1).freq_bins alloy(1).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(1)).freq(:),...
    sedald(sys_size_ald(1)).life(:),...
    sedald(sys_size_ald(1)).vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3),...
    35 ...
    );
cond.alloy(1) = m_ald_cond(...
    sedald(sys_size_ald(1)).life(:),...
    sedald(sys_size_ald(1)).vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3))

%5 8 ald
[alloy_5(1).freq_bins alloy_5(1).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(1)).freq(:)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(1)).life(:)/sqrt(1.8) + ...
    1./(alloy_5(sys_size_ald(1)).life(:))),...
    sedald(sys_size_ald(1)).vel(:,1)/sqrt(1.8),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3),...
    35 ...
    );
cond.alloy_5(1) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(1)).life(:)/sqrt(1.8) + ...
    1./(alloy_5(sys_size_ald(1)).life(:))),...
    sedald(sys_size_ald(1)).vel(:,1)/sqrt(1.8),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3))
%8 nmd
[sed8.freq_bins sed8.cond_freq] =...
    m_ald_cond_freq(...
    sed8.freq,...
    (1/0.45)*sed8.life ,...
    sed8.vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3),...
    35 ...
    );
cond.sed8_5 = m_ald_cond(...
    (1/0.45)*sed8_5.life ,...
    sed8_5.vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3))
%8_5 nmd
[sed8_5.freq_bins sed8_5.cond_freq] =...
    m_ald_cond_freq(...
    sed8_5.freq,...
    (1/0.45)*sed8_5.life ,...
    sed8_5.vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3),...
    35 ...
    );
cond.sed8_5.cond = m_ald_cond(...
    (1/0.45)*sed8_5.life ,...
    sed8_5.vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3))


%05 perfect
[perfect_05(ipt).freq_bins perfect_05(ipt).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) ,...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );
cond.perfect_05(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) ,...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3))
%5 perfect
[perfect_5(ipt).freq_bins perfect_5(ipt).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) ,...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS ...
    );
cond.perfect_5(ipt) = m_ald_cond(...
    sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) ,...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3))

[alloy_05(ipt).freq_bins alloy_05(ipt).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))),...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );
cond.alloy_05(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))),...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3))

[alloy_5(ipt).freq_bins alloy_5(ipt).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );
cond.alloy_5(ipt) = m_ald_cond(...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3))



%5 version
subplot(2,1,1),...
loglog(...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),...
    sedald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),'.',...
    sed8.freq,1.2*(1/0.45)*sed8.life,'.',...
    sedald(sys_size_ald(1)).freq(:)/sqrt(1.8),...
    1.2*1./( 1./sedald(sys_size_ald(1)).life(:)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(1)).life(:)),'.',...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    2E17*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-2),...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    1E40*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-4),...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    2*pi*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-1)...
    )
subplot(2,1,2),...
semilogx(...
    [perfect_5(8).freq_bins(2)/1.1 perfect_5(8).freq_bins(2:end)],...
    [0 perfect_5(8).cond_freq(2:end)],...
    [alloy_5(8).freq_bins(2)/1.1 alloy_5(8).freq_bins(2:end)] ,...
    [0 alloy_5(8).cond_freq(2:end)] , ...
    [sed8.freq_bins(2)/1.1 sed8.freq_bins(2:end) ] ,...
    [0 sed8.cond_freq(2:end)],...
    [alloy_5(1).freq_bins(2)/1.1 alloy_5(1).freq_bins(2:end) ],...
    [0 alloy_5(1).cond_freq(2:end)]...
    )

%--------------------------------------------------------------------------
%plot size dependance
%--------------------------------------------------------------------------
% semilogy(...
%     ...
%     [1./sys_size_ald([1 4 6 8]) 1./34 1./42 1/100000 ],...
%     [cond.sedald([1 4 6 8]) 482 483.5 484.0],...
%     '.',...
%     [1./sys_size_ald([1 4 6 8]) 1./34 1./42 1/100000],...
%     [cond.alloy_05([1 4 6 8]) 21.4 21.53 23.5],...
%     '.',...
%     [1./sys_size_ald([1 4 6 8]) 1./34 1./42 1/100000],...
%     [cond.alloy_5([1 4 6 8]) 10.65 10.8 11.0],...
%     '.',...
%     ...
%     [1./gk.size([3 9 11 12 13]) ],...
%     [gk.cond([3 9 11 12 13],1) ],...
%     '.',...
%     [1./gk.size([3 9 11 12 13]) ; 1./38 ; 1/100000],...
%     [gk.cond([3 9 11 12 13],2) ; 19.0 ; 20.0 ],...
%     '.',...
%     [1./gk.size([3 9 11 12 13]) ; 1./38 ; 1/100000 ],...
%     [gk.cond([3 9 11 12 13],4) ; 9.1 ; 9.3 ],...
%     '.',...
%     [1/8],...
%     [ cond.alloy_05(1)*1.1  ],...
%     '.',... 
%     [1/8],...
%     [ cond.sed8  ],...
%     '.'... 
%     )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

NUM_BINS = 50;
[perfect_05(ipt).mfp_bins perfect_05(ipt).mfp_cond] =...
    m_ald_cond_mfp(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) ,...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1:3)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );
loglog(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08).*...
    sqrt(...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
    ),'.'...
    )
NUM_BINS = 100;
[alloy_05(ipt).mfp_bins alloy_05(ipt).mfp_cond] =...
    m_ald_cond_mfp(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))),...
    sedald(sys_size_ald(ipt)).vel(Ialloy05,1:3)/sqrt(1.08),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );
loglog(...
    sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
    1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))).*...
    sqrt(...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
    (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
    ),'.'...
    )
NUM_BINS = 100;
[alloy_5(ipt).mfp_bins alloy_5(ipt).mfp_cond] =...
    m_ald_cond_mfp(...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),...
    sedald(sys_size_ald(ipt)).vel(Ialloy5,1:3)/sqrt(1.8),...
    nmd(sys_size_ald(ipt)).nmd.x0.VOLUME*((1e-10)^3),...
    NUM_BINS...
    );

% subplot(2,1,1),...
% loglog(...
%     sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
%     sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
%     ),'.',...
%     sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
%     1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
%     1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
%     ),'.',...
%     sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
%     1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
%     1./(alloy_5(sys_size_ald(ipt)).life(Ialloy5))).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,2)/sqrt(1.8)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,3)/sqrt(1.8)).^2 ...
%     ),'.'...
%     )

subplot(2,1,1),...
semilogx(...
    perfect_05(ipt).mfp_bins,...
    perfect_05(ipt).mfp_cond/sum(perfect_05(ipt).mfp_cond),...
    alloy_05(ipt).mfp_bins,...
    alloy_05(ipt).mfp_cond/sum(alloy_05(ipt).mfp_cond),...
    alloy_5(ipt).mfp_bins,...
    alloy_5(ipt).mfp_cond/sum(alloy_5(ipt).mfp_cond)...
    )
subplot(2,1,2),...
semilogx(...
    perfect_05(ipt).mfp_bins*1E9,...
    cumtrapz(perfect_05(ipt).mfp_cond)/sum(perfect_05(ipt).mfp_cond),...
    alloy_05(ipt).mfp_bins*1E9,...
    cumtrapz(alloy_05(ipt).mfp_cond)/sum(alloy_05(ipt).mfp_cond),...
    alloy_5(ipt).mfp_bins*1E9,...
    cumtrapz(alloy_5(ipt).mfp_cond)/sum(alloy_5(ipt).mfp_cond)...
    )



subplot(2,1,1),...
loglog(...
    sedald(sys_size_ald(ipt)).freq/sqrt(1.8),...
    sedald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
    sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
    1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),'.',...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    2E17*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-2),...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    1E40*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-4),...
    linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
    2*pi*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-1)...
    )
subplot(2,1,2),...
semilogx(...
    [perfect_5(8).freq_bins(2)/1.1 perfect_5(8).freq_bins(2:end)],...
    [0 perfect_5(8).cond_freq(2:end)],...
    [alloy_5(8).freq_bins(2)/1.1 alloy_5(8).freq_bins(2:end)] ,...
    [0 alloy_5(8).cond_freq(2:end)] ...
    )

%plot life, Diff, k(w)
Dsedald = sedald(sys_size_ald(1)).vel(:,1).^2.*sedald(sys_size_ald(1)).life;
Ised =...
    find(...
    Dsedald < 4.773E-8 &...
    sedald(sys_size_ald(1)).freq < 1.729E13 ...
    );
Dsedald(Ised) = 0;
Dsedald8 = (sedald(sys_size_ald(1)).vel(:,1)./sqrt(1.8)).^2.*...
    1./( 1./sedald(sys_size_ald(1)).life(:)/sqrt(1.8) + ...
    1./(alloy_5(sys_size_ald(1)).life(:)));
Ised =...
    find(...
    Dsedald8 < 4.773E-8 &...
    sedald(sys_size_ald(1)).freq/sqrt(1.8) < 1.729E13 ...
    );
Dsedald8(Ised) = 0;
Dsed8_5 = (sed8_5.vel(:,1).*(1/0.45)).^2.*sed8_5.life;
Ised =...
    find(...
    Dsed8_5 < 4.773E-8 &...
    sed8_5.freq < 1.729E13 ...
    );
Dsed8_5(Ised) = 0;

subplot(3,1,1),...
loglog(...
    sedald(sys_size_ald(1)).freq,sedald(sys_size_ald(1)).life,'.',...
    sedald(sys_size_ald(1)).freq/sqrt(1.8),...
    1./( 1./sedald(sys_size_ald(1)).life(:)/sqrt(1.8) + ...
    1./(alloy_5(sys_size_ald(1)).life(:))),'.',...
    sed8_5.freq,(1/0.45)*sed8_5.life,'.',...
    linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100),...
    0.75E17*linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100).^(-2),...
    linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100),...
    4E40*linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100).^(-4),...
    linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100),...
    2*pi*linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100).^(-1)...
    )
subplot(3,1,2),...
loglog(...
    sedald(sys_size_ald(1)).freq,...
    Dsedald,'.',...
    sedald(sys_size_ald(1)).freq/sqrt(1.8),...
    Dsedald8,'.',...
    sed8_5.freq,...
    Dsed8_5,'.',...
    linspace(0,1.5*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100),...
    ones(1,100).*(1/3)*si.sound*(5.43E-10/2),...
    linspace(0,1.1*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100),...
    (1/3)*(si.sound^2).*(2*pi)./...
    linspace(0,1.1*max(sedald(sys_size_ald(ipt)).freq/sqrt(1.0)),100)...
    )
subplot(3,1,3),...
loglog(...
    [alloy(1).freq_bins(2)/1.1 alloy(1).freq_bins(2:end)],...
    [0 alloy(1).cond_freq(2:end)],...
    [alloy_5(1).freq_bins(2)/1.1 alloy_5(1).freq_bins(2:end)] ,...
    [0 alloy_5(1).cond_freq(2:end)],...
    [sed8_5.freq_bins(2)/1.1 sed8_5.freq_bins(2:end)] ,...
    [0 sed8_5.cond_freq(2:end)]...
    )

[alloy(1).freq_bins alloy(1).cond_freq] =...
    m_ald_cond_freq(...
    sedald(sys_size_ald(1)).freq(:),...
    sedald(sys_size_ald(1)).life(:),...
    sedald(sys_size_ald(1)).vel(:,1),...
    nmd(sys_size_ald(1)).nmd.x0.VOLUME*((1e-10)^3),...
    35 ...
    );
    

%--------------------------------------------------------------------------
pause
pause
pause
pause
pause
pause
pause
pause
pause
%-------------------------------------------------------------------------- 


