clear
lj = m_lj; constant = m_constant;

sed(1).sed =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/SEDdata.mat'...
);
nmd(1).nmd =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/NMDdata.mat'...
);
sed(1).sed = nmd_convert_data(nmd(1).nmd,sed(1).sed);
sed(2).sed =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/SEDdata_modify.mat'...
);
nmd(2).nmd =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/NMDdata_modify.mat'...
);
sed(3).sed =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD/1/work/SEDdata.mat'...
);
nmd(3).nmd =...
load(...
'/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD/1/work/NMDdata.mat'...
);


pause

%--------------------------------------------------------------------------
%0.0
%--------------------------------------------------------------------------
NUM_BINS=20;
[sed(1).freq_bins sed(1).freq_cond] =...
    m_ald_cond_freq(...
    sed(1).sed.freq/lj.tau,...
    sed(1).sed.life*lj.tau,...
    sed(1).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(1).nmd.VOLUME,...
    NUM_BINS...
    );
NUM_BINS=200;
[sed(1).mfp_bins sed(1).mfp_cond] =...
    m_ald_cond_mfp(...
    sed(1).sed.freq/lj.tau,...
    sed(1).sed.life*lj.tau,...
    sed(1).sed.groupvel(:,1:3)*lj.sigma/lj.tau,...
    nmd(1).nmd.VOLUME,...
    NUM_BINS...
    );
sed(1).cond =...
    m_ald_cond(...
    sed(1).sed.life*lj.tau,...
    sed(1).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(1).nmd.VOLUME...
    )
%--------------------------------------------------------------------------
%0.05
%--------------------------------------------------------------------------
NUM_BINS=20;
[sed(2).freq_bins sed(2).freq_cond] =...
    m_ald_cond_freq(...
    sed(2).sed.freq/lj.tau,...
    sed(2).sed.life*lj.tau,...
    sed(2).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(2).nmd.VOLUME,...
    NUM_BINS...
    );
NUM_BINS=200;
[sed(2).mfp_bins sed(2).mfp_cond] =...
    m_ald_cond_mfp(...
    sed(2).sed.freq/lj.tau,...
    sed(2).sed.life*lj.tau,...
    sed(2).sed.groupvel(:,1:3)*lj.sigma/lj.tau,...
    nmd(2).nmd.VOLUME,...
    NUM_BINS...
    );
sed(2).cond =...
    m_ald_cond(...
    sed(2).sed.life*lj.tau,...
    sed(2).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(2).nmd.VOLUME...
    )
%--------------------------------------------------------------------------
%0.5
%--------------------------------------------------------------------------
NUM_BINS=20;
[sed(3).freq_bins sed(3).freq_cond] =...
    m_ald_cond_freq(...
    sed(3).sed.freq/lj.tau,...
    sed(3).sed.life*lj.tau,...
    sed(3).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(3).nmd.VOLUME,...
    NUM_BINS...
    );
NUM_BINS=200;
[sed(3).mfp_bins sed(3).mfp_cond] =...
    m_ald_cond_mfp(...
    sed(3).sed.freq/lj.tau,...
    sed(3).sed.life*lj.tau,...
    sed(3).sed.groupvel(:,1:3)*lj.sigma/lj.tau,...
    nmd(3).nmd.VOLUME,...
    NUM_BINS...
    );
sed(3).cond =...
    m_ald_cond(...
    sed(3).sed.life*lj.tau,...
    sed(3).sed.groupvel(:,1)*lj.sigma/lj.tau,...
    nmd(3).nmd.VOLUME...
    )


subplot(2,1,1),...
loglog(...
    sed(1).sed.freq/lj.tau,sed(1).sed.life*lj.tau,'.',...
    sed(2).sed.freq/lj.tau,sed(2).sed.life*lj.tau,'.',...
    sed(3).sed.freq/lj.tau,sed(3).sed.life*lj.tau,'.',...
    linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100),...
    1E14*linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100).^(-2),...
    linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100),...
    1E39*linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100).^(-4),...
    linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100),...
    2*pi./linspace( min(sed(1).sed.freq/lj.tau), max(sed(1).sed.freq/lj.tau), 100)...
    )
subplot(2,1,2),...
semilogx(...
    sed(1).freq_bins,sed(1).freq_cond,...
    sed(2).freq_bins,sed(2).freq_cond,...
    sed(3).freq_bins,sed(3).freq_cond...
    )


semilogx(...
    sed(1).mfp_bins*1E9,cumtrapz(sed(1).mfp_cond)/sum(sed(1).mfp_cond),...
    sed(2).mfp_bins*1E9,cumtrapz(sed(2).mfp_cond)/sum(sed(2).mfp_cond),...
    sed(3).mfp_bins*1E9,cumtrapz(sed(3).mfp_cond)/sum(sed(3).mfp_cond)...
    )





% subplot(2,1,1),...
% loglog(...
%     sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
%     sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
%     ),'.',...
%     sedald(sys_size_ald(ipt)).freq(Ialloy05)/sqrt(1.08),...
%     1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy05)/sqrt(1.08) + ...
%     1./(FACTOR_05*alloy_05(sys_size_ald(ipt)).life(Ialloy05))).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,1)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,2)/sqrt(1.08)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy05,3)/sqrt(1.08)).^2 ...
%     ),'.',...
%     sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
%     1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
%     1./(alloy_5(sys_size_ald(ipt)).life(Ialloy5))).*...
%     sqrt(...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,1)/sqrt(1.8)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,2)/sqrt(1.8)).^2 +...
%     (sedald(sys_size_ald(ipt)).vel(Ialloy5,3)/sqrt(1.8)).^2 ...
%     ),'.'...
%     )

% subplot(2,1,1),...
% semilogx(...
%     perfect_05(ipt).mfp_bins,...
%     perfect_05(ipt).mfp_cond/sum(perfect_05(ipt).mfp_cond),...
%     alloy_05(ipt).mfp_bins,...
%     alloy_05(ipt).mfp_cond/sum(alloy_05(ipt).mfp_cond),...
%     alloy_5(ipt).mfp_bins,...
%     alloy_5(ipt).mfp_cond/sum(alloy_5(ipt).mfp_cond)...
%     )
% subplot(2,1,2),...
% semilogx(...
%     perfect_05(ipt).mfp_bins*1E9,...
%     cumtrapz(perfect_05(ipt).mfp_cond)/sum(perfect_05(ipt).mfp_cond),...
%     alloy_05(ipt).mfp_bins*1E9,...
%     cumtrapz(alloy_05(ipt).mfp_cond)/sum(alloy_05(ipt).mfp_cond),...
%     alloy_5(ipt).mfp_bins*1E9,...
%     cumtrapz(alloy_5(ipt).mfp_cond)/sum(alloy_5(ipt).mfp_cond)...
%     )
% 
% 
% 
% subplot(2,1,1),...
% loglog(...
%     sedald(sys_size_ald(ipt)).freq/sqrt(1.8),...
%     sedald(sys_size_ald(ipt)).life/sqrt(1.8),'.',...
%     sedald(sys_size_ald(ipt)).freq(Ialloy5)/sqrt(1.8),...
%     1./( 1./sedald(sys_size_ald(ipt)).life(Ialloy5)/sqrt(1.8) + ...
%     1./alloy_5(sys_size_ald(ipt)).life(Ialloy5)),'.',...
%     linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
%     2E17*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-2),...
%     linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
%     1E40*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-4),...
%     linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100),...
%     2*pi*linspace(0,max(sedald(sys_size_ald(ipt)).freq/sqrt(1.8)),100).^(-1)...
%     )
% subplot(2,1,2),...
% semilogx(...
%     [perfect_5(8).freq_bins(2)/1.1 perfect_5(8).freq_bins(2:end)],...
%     [0 perfect_5(8).cond_freq(2:end)],...
%     [alloy_5(8).freq_bins(2)/1.1 alloy_5(8).freq_bins(2:end)] ,...
%     [0 alloy_5(8).cond_freq(2:end)] ...
%     )