function m_ald_taud_si_c001_createfigure(X1, Y1, X2, YMatrix1, X3, YMatrix2)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1,X3,YMATRIX2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 26-Oct-2012 01:07:53

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'Units','inches',...
    'Position',[0.832 0.589111111111111 3.5 3.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[3852248420036.75 167420842786045]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[7.94328234724282e-14 6.15019504275219e-09]);
box(axes1,'on');
hold(axes1,'all');

% Create loglog
loglog(X1,Y1,'Parent',axes1,'Marker','o','LineStyle','none',...
    'DisplayName','$\tau_{pp}$');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X2,YMatrix1,'Parent',axes1,'LineStyle','none');
set(loglog1(1),'Marker','square','DisplayName','$\tau$');
set(loglog1(2),'Marker','diamond','DisplayName','$\tau_{d}$');

% Create multiple lines using matrix input to loglog
loglog2 = loglog(X3,YMatrix2,'Parent',axes1);
set(loglog2(1),'DisplayName','$\omega^{-2}$');
set(loglog2(2),'DisplayName','$\omega^{-4}$');

% Create xlabel
xlabel({'$\omega$ (rads/s)'},'Interpreter','latex');

% Create ylabel
ylabel({'$\tau$ (s)'},'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[3.27083333333334 2.81527777777778 0.894444444444444 1.28333333333333]);

