function m_book_cond_extrap_createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 28-Dec-2012 16:17:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[0.6 0.6 2.5 2]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.8 1.05]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',10,'Marker','square',...
    'LineStyle','none');
set(plot1(1),'Marker','o','DisplayName','GK c=0.0');
set(plot1(2),'DisplayName','NMD conv c=0.0');
set(plot1(3),'DisplayName','NMD prim c=0.0');

% Create xlabel
xlabel({'$1/N_0$'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'$k(N_0)/k_{bulk}$'},'Interpreter','latex','FontSize',12);

% Create axes
axes2 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[3.7 0.6 2.5 2]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 0.3]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'MarkerSize',10,'LineStyle','none');
set(plot2(1),'Marker','o','DisplayName','GK c=0.05');
set(plot2(2),'Marker','square','DisplayName','VC-NMD c=0.05');
set(plot2(3),'Marker','diamond','DisplayName','GK amor');

% Create xlabel
xlabel({'$1/N_0$'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','inches',...
    'Position',[0.734174311926626 0.731530958439345 1.53888888888889 0.569444444444445],...
    'FontSize',9);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'Units','inches',...
    'Position',[3.81944444444446 0.711111111111115 1.5361111111111 0.569444444444444],...
    'FontSize',9);

% Create ellipse
annotation(figure1,'ellipse',...
    [0.858142857142863 0.243305930710511 0.0326134453781511 0.0759248385202588],...
    'LineWidth',2,...
    'Units','inches');

