function m_book_lj_dos_createfigure(X1, Y1, X2)
%CREATEFIGURE(X1,Y1,X2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 25-Dec-2012 14:29:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[0.5 0.5 2.5 2]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 30]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',3,'DisplayName','DOS');

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',2,'LineStyle','-.',...
    'DisplayName','$B\omega^{2}$');

% Create xlabel
xlabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[1.93055555555556 0.606944444444448 0.938888888888889 0.573611111111111]);

