function m_book_lj_disp_dos_vg_prim_createfigure(X1, Y1, X2, X3, YMatrix1, X4, YMatrix2)
%CREATEFIGURE(X1,Y1,X2,X3,YMATRIX1,X4,YMATRIX2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  YMATRIX1:  matrix of y data
%  X4:  vector of x data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 30-Dec-2012 13:12:29

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','Position',[4.6 0.6 2 2.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.09]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1e-08 29.9999999]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','DOS');

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',1,'LineStyle','-.',...
    'DisplayName','$B\omega^2$');

% Create xlabel
xlabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes2 = axes('Parent',figure1,'Units','inches','Position',[2.6 0.6 2 2.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 0.9999999999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1e-08 29.999999]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X3,YMatrix1,'Parent',axes2);
set(plot1(1),'LineWidth',4,'DisplayName','TA');
set(plot1(2),'LineWidth',2,'LineStyle','--','DisplayName','LA');
set(plot1(3),'LineWidth',1,'Color',[0 0 1],'DisplayName','TA $v_g$');
set(plot1(4),'LineWidth',2,'LineStyle','-.','Color',[0 0.498039215686275 0],...
    'DisplayName','LA $v_g$');

% Create legend
legend1 = legend(axes2,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[2.69166666666668 2.39305555555557 0.786111111111097 0.618055555555548],...
    'FontSize',9);

% Create axes
axes3 = axes('Parent',figure1,'XDir','reverse','Units','inches',...
    'Position',[0.6 0.6 2 2.5]);
box(axes3,'on');
hold(axes3,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X4,YMatrix2,'Parent',axes3);
set(plot2(1),'LineWidth',4);
set(plot2(2),'LineWidth',1,'Color',[0 0 1]);
set(plot2(3),'LineWidth',2,'LineStyle','--','Color',[0 0.498039215686275 0]);
set(plot2(4),'LineWidth',2,'LineStyle','-.','Color',[0 0.498039215686275 0]);

% Create xlabel
xlabel({'$\mathbf{\kappa}$'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'$\omega , v_g$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend2 = legend(axes1,'show');
set(legend2,'Interpreter','latex','Units','inches',...
    'Position',[5.76666666666667 0.740277777777782 0.733333333333333 0.337499999999996],...
    'FontSize',9);

