function m_book_lj_disp_createfigure(X1, YMatrix1, YMatrix2)
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 25-Dec-2012 14:01:31

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[1.75 0.5 1.25 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1e-08 29.999999999]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'DisplayName','TA');
set(plot1(2),'LineStyle','--','DisplayName','LA');

% Create axes
axes2 = axes('Parent',figure1,'XDir','reverse','Units','inches',...
    'TickLength',[0.025 0.025],...
    'Position',[0.5 0.5 1.25 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 30]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'LineWidth',2);
set(plot2(1),'Color',[1 0 0],'DisplayName','TA');
set(plot2(2),'LineStyle','--',...
    'Color',[0 0.749019607843137 0.749019607843137],...
    'DisplayName','LA');

% Create ylabel
ylabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create xlabel
xlabel({'$\mathbf{\kappa}$'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes2,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[1.03611111111111 2.00208333333333 0.6 0.4],...
    'FontSize',9);

% Create legend
legend2 = legend(axes1,'show');
set(legend2,'Interpreter','latex','Units','inches',...
    'Position',[1.8625 2.00208333333333 0.6 0.4],...
    'FontSize',9);

% Create textbox
annotation(figure1,'textbox',...
    [0.146164835164835 0.235714285714287 0.0199890109890113 0.0452380952380975],...
    'Interpreter','latex',...
    'String',{'[100]'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1],...
    'Units','inches');

% Create textbox
annotation(figure1,'textbox',...
    [0.710835164835165 0.228979591836736 0.0722142857142857 0.0452380952380975],...
    'Interpreter','latex',...
    'String',{'[111]'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1],...
    'Units','inches');

