function cart = m_direct2cart( direct , latvec )

cart(:,1) = direct(:,1)*latvec(1,1) +...
        direct(:,2)*latvec(2,1) +...
        direct(:,3)*latvec(3,1) ;
cart(:,2) = direct(:,1)*latvec(1,2) +...
        direct(:,2)*latvec(2,2) +...
        direct(:,3)*latvec(3,2) ;
cart(:,3) = direct(:,1)*latvec(1,3) +...
        direct(:,2)*latvec(2,3) +...
        direct(:,3)*latvec(3,3) ;

end
