function m_dos_alloy_vc_gamma_createfigure(X1, Y1, X2, Y2, X3, X4, Y3, X5, X6, Y4, X7, Y5)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,X4,Y3,X5,X6,Y4,X7,Y5)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  X4:  vector of x data
%  Y3:  vector of y data
%  X5:  vector of x data
%  X6:  vector of x data
%  Y4:  vector of y data
%  X7:  vector of x data
%  Y5:  vector of y data

%  Auto-generated by MATLAB on 18-Nov-2012 00:36:10

% Create figure
figure1 = figure('XVisual',...
    '0x9c (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.634111111111111 4.43851307189543 3.5 2],...
    'LineWidth',2);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1e-08 24.9999999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.15999999]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2);

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2);

% Create axes
axes2 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.634111111111111 2.42981209150327 3.5 2],...
    'LineWidth',2);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1e-08 24.999999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 0.1599999]);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X3,Y1,'Parent',axes2,'LineWidth',2);

% Create plot
plot(X4,Y3,'Parent',axes2,'LineWidth',2);

% Create ylabel
ylabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes3 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.634111111111111 0.432222222222223 3.5 2],...
    'LineWidth',2);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 0.1599999]);
box(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X5,Y1,'Parent',axes3,'LineWidth',2,'DisplayName','VC');

% Create plot
plot(X6,Y4,'Parent',axes3,'LineWidth',2,'DisplayName','Gamma');

% Create plot
plot(X7,Y5,'Parent',axes3,'LineWidth',2,'DisplayName','amorphous');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes3,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[0.736111111111113 3.51111111111111 1.31666666666667 0.825],...
    'LineWidth',2);

