function m_dos_alloy_vc_gamma_createfigure(X1, YMatrix1, X2, Y1, X3, YMatrix2, X4, Y2, X5, YMatrix3, X6, Y3)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1,X3,YMATRIX2,X4,Y2,X5,YMATRIX3,X6,Y3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  X4:  vector of x data
%  Y2:  vector of y data
%  X5:  vector of x data
%  YMATRIX3:  matrix of y data
%  X6:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 13-Dec-2012 22:33:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[0.686666666666667 3.59069607843138 3.5 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1e-10 24.999999999]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(2),'LineStyle','-.');

% Create plot
plot(X2,Y1,'Parent',axes1,'LineWidth',2,'LineStyle','--');

% Create axes
axes2 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[0.686666666666667 2.08657026143791 3.5 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1e-09 24.99999999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 0.19999999]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix2,'Parent',axes2,'LineWidth',2);
set(plot2(1),'DisplayName','VC');
set(plot2(2),'LineStyle','-.','DisplayName','$B\omega^2$');

% Create plot
plot(X4,Y2,'Parent',axes2,'LineWidth',2,'LineStyle','--',...
    'DisplayName','Gamma');

% Create ylabel
ylabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes3 = axes('Parent',figure1,'Units','inches','TickLength',[0.025 0.025],...
    'Position',[0.686666666666667 0.593555555555556 3.5 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 0.1999999]);
box(axes3,'on');
hold(axes3,'all');

% Create multiple lines using matrix input to plot
plot3 = plot(X5,YMatrix3,'Parent',axes3,'LineWidth',2);
set(plot3(2),'LineStyle','-.');

% Create plot
plot(X6,Y3,'Parent',axes3,'LineWidth',2,'LineStyle','--');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes2,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[0.836111111111112 2.63888888888889 1.12777777777778 0.825]);

