function m_dos_alloy_vc_gamma_createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 27-Oct-2012 17:05:53

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.832 0.589111111111111 3.5 2]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 30]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','VC');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,'DisplayName','Gamma');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[2.45833333333334 0.684722222222226 1.77222222222222 0.551388888888889]);

