function m_dos_alloy_vc_gamma_3_createfigure(X1, Y1, X2, Y2, X3, X4, Y3, X5, X6, Y4)
%CREATEFIGURE(X1,Y1,X2,Y2,X3,X4,Y3,X5,X6,Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  X4:  vector of x data
%  Y3:  vector of y data
%  X5:  vector of x data
%  X6:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 27-Oct-2012 20:58:28

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.570555555555556 3.51111111111112 3.5 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1e-07 24.9999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.2]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','VC');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,'DisplayName','Gamma');

% Create axes
axes2 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.577777777777778 2.01111111111111 3.49277777777778 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[1e-06 24.999999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 0.199999]);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X3,Y1,'Parent',axes2,'LineWidth',2,'DisplayName','VC');

% Create plot
plot(X4,Y3,'Parent',axes2,'LineWidth',2,'DisplayName','Gamma');

% Create ylabel
ylabel({'DOS (arb. units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes3 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.570555555555556 0.507222222222222 3.5 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 0.199999]);
box(axes3,'on');
hold(axes3,'all');

% Create plot
plot(X5,Y1,'Parent',axes3,'LineWidth',2);

% Create plot
plot(X6,Y4,'Parent',axes3,'LineWidth',2);

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes2,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[0.680555555555559 2.85138888888889 1.12777777777778 0.551388888888889]);

% Create textbox
annotation(figure1,'textbox',...
    [0.801 0.878151260504202 0.115883116883117 0.0483193277310917],...
    'Interpreter','latex',...
    'String',{'c=0.05'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.796884425651868 0.310840336134451 0.115883116883117 0.0483193277310917],...
    'Interpreter','latex',...
    'String',{'c=0.5'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.802831605087419 0.591344537815125 0.115883116883117 0.0483193277310917],...
    'Interpreter','latex',...
    'String',{'c=0.15'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

