clear

con = m_constant; 

DSF(1).tran =...
    load(['/home/jason/disorder2/si/amor/normand/perf4096/anneal_1100K/emin/' ...
    'DSF_tran_b5.mat'])
DSF(1).long =...
    load(['/home/jason/disorder2/si/amor/normand/perf4096/anneal_1100K/emin/' ...
    'DSF_long_b5.mat'])

%perfect2
DISP(1).kpt = DSF(1).tran.kpt;
DISP(1).tran.freq = [8.54E12 ; 1.699E13 ; 2.56E13 ; 3.21E13 ; 3.74E13  ];
DISP(1).long.freq = [1.86E13 ; 3.84E13 ; 5.37E13 ; 6.52E13 ; 7.90E13  ];

%load disp
freq0.freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/freq.gout');
freq(1).freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/disp/1/freq.gout');
freq(2).freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/disp/2/freq.gout');
freq(3).freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/disp/3/freq.gout');
freq(4).freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/disp/4/freq.gout');
freq(5).freq =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/disp/5/freq.gout');


subplot(3,1,1),...
semilogx(...
    DSF(1).tran.SL(:,1),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,2),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,3),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,4),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,5),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,6),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,7),DSF(1).tran.freq_range,'.',...
    DSF(1).tran.SL(:,8),DSF(1).tran.freq_range,'.'...
    )
subplot(3,1,2),...
plot(...
    [0.0 ; DISP(1).kpt(:,1)],[0.0 ; DISP(1).tran.freq],'.',...
    [0.0 ; DISP(1).kpt(:,1)],[0.0 ; DISP(1).long.freq],'.' ...
    )
subplot(3,1,3),...
semilogx(...
    DSF(1).long.SL(:,1),DSF(1).long.freq_range,'.',...
    DSF(1).long.SL(:,2),DSF(1).long.freq_range,'.',...
    DSF(1).long.SL(:,3),DSF(1).long.freq_range,'.',...
    DSF(1).long.SL(:,4),DSF(1).long.freq_range,'.',...
    DSF(1).long.SL(:,5),DSF(1).long.freq_range,'.'...
    )


plot(...
    [0.0 ; DISP(1).kpt(:,1)],...
    [0.0 ; freq(1).freq(1) ; freq(2).freq(1) ; freq(3).freq(1) ; freq(4).freq(1) ; freq(5).freq(1) ] * con.c *2*pi ,'.',...
    [0.0 ; DISP(1).kpt(:,1)],...
    [0.0 ; freq(1).freq(2) ; freq(2).freq(2) ; freq(3).freq(2) ; freq(4).freq(2) ; freq(5).freq(2) ] * con.c *2*pi ,'.',...
    [0.0 ; DISP(1).kpt(:,1)],...
    [0.0 ; freq(1).freq(3) ; freq(2).freq(3) ; freq(3).freq(3) ; freq(4).freq(3) ; freq(5).freq(3) ] * con.c *2*pi ,'.',...
    [0.0 ; DISP(1).kpt(:,1)],...
    [freq0.freq(4) ; freq(1).freq(4) ; freq(2).freq(4) ; freq(3).freq(4) ; freq(4).freq(4) ; freq(5).freq(4) ] * con.c *2*pi ,'.', ...
    [0.0 ; DISP(1).kpt(:,1)],...
    [freq0.freq(5) ; freq(1).freq(5) ; freq(2).freq(5) ; freq(3).freq(5) ; freq(4).freq(5) ; freq(5).freq(5) ] * con.c *2*pi ,'.', ...
    [0.0 ; DISP(1).kpt(:,1)],...
    [freq0.freq(6) ; freq(1).freq(6) ; freq(2).freq(6) ; freq(3).freq(6) ; freq(4).freq(6) ; freq(5).freq(6) ] * con.c *2*pi ,'.' , ...
    [0.0 ; DISP(1).kpt(:,1)],...
    [freq0.freq(10) ; freq(1).freq(10) ; freq(2).freq(10) ; freq(3).freq(10) ; freq(4).freq(10) ; freq(5).freq(10) ] * con.c *2*pi ,'.' ...
)





