function m_dsf_plot_disp_100_111_createfigure(X1, Y1, X2, X3, X4, X5, X6, YMatrix1, X7, X8, X9, X10, X11, Y2, X12, X13, X14, X15, X16, YMatrix2, X17, Y3, X18, Y4, X19, Y5, X20, Y6, X21, Y7, YMatrix3, X22, Y8, X23, X24, X25, X26, YMatrix4, X27, Y9, X28, X29, X30, X31)
%CREATEFIGURE(X1,Y1,X2,X3,X4,X5,X6,YMATRIX1,X7,X8,X9,X10,X11,Y2,X12,X13,X14,X15,X16,YMATRIX2,X17,Y3,X18,Y4,X19,Y5,X20,Y6,X21,Y7,YMATRIX3,X22,Y8,X23,X24,X25,X26,YMATRIX4,X27,Y9,X28,X29,X30,X31)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  X3:  vector of x data
%  X4:  vector of x data
%  X5:  vector of x data
%  X6:  vector of x data
%  YMATRIX1:  matrix of y data
%  X7:  vector of x data
%  X8:  vector of x data
%  X9:  vector of x data
%  X10:  vector of x data
%  X11:  vector of x data
%  Y2:  vector of y data
%  X12:  vector of x data
%  X13:  vector of x data
%  X14:  vector of x data
%  X15:  vector of x data
%  X16:  vector of x data
%  YMATRIX2:  matrix of y data
%  X17:  vector of x data
%  Y3:  vector of y data
%  X18:  vector of x data
%  Y4:  vector of y data
%  X19:  vector of x data
%  Y5:  vector of y data
%  X20:  vector of x data
%  Y6:  vector of y data
%  X21:  vector of x data
%  Y7:  vector of y data
%  YMATRIX3:  matrix of y data
%  X22:  vector of x data
%  Y8:  vector of y data
%  X23:  vector of x data
%  X24:  vector of x data
%  X25:  vector of x data
%  X26:  vector of x data
%  YMATRIX4:  matrix of y data
%  X27:  vector of x data
%  Y9:  vector of y data
%  X28:  vector of x data
%  X29:  vector of x data
%  X30:  vector of x data
%  X31:  vector of x data

%  Auto-generated by MATLAB on 28-Oct-2012 14:56:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'XDir','reverse',...
    'Units','inches',...
    'Position',[2.73333333333334 3.77777777777778 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[100.001 300000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 28]);
box(axes1,'on');
hold(axes1,'all');

% Create semilogx
semilogx(X1,Y1,'Parent',axes1,'Marker','.','LineStyle','none');

% Create semilogx
semilogx(X2,Y1,'Parent',axes1,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X3,Y1,'Parent',axes1,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X4,Y1,'Parent',axes1,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X5,Y1,'Parent',axes1,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create axes
axes2 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'XDir','reverse',...
    'Units','inches',...
    'Position',[2.73366827697263 2.28229493464052 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[100.001 299900]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 28]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to semilogx
semilogx(X6,YMatrix1,'Parent',axes2,'Marker','.','LineStyle','none');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X7,YMatrix1,'Parent',axes2,'Marker','.',...
    'LineStyle','none');
set(semilogx1(3),'Color',[0 0 1]);

% Create multiple lines using matrix input to semilogx
semilogx2 = semilogx(X8,YMatrix1,'Parent',axes2,'Marker','.',...
    'LineStyle','none');
set(semilogx2(3),'Color',[0 0 1]);

% Create multiple lines using matrix input to semilogx
semilogx3 = semilogx(X9,YMatrix1,'Parent',axes2,'Marker','.',...
    'LineStyle','none');
set(semilogx3(3),'Color',[0 0 1]);

% Create multiple lines using matrix input to semilogx
semilogx4 = semilogx(X10,YMatrix1,'Parent',axes2,'Marker','.',...
    'LineStyle','none');
set(semilogx4(3),'Color',[0 0 1]);

% Create axes
axes3 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'XDir','reverse',...
    'Units','inches',...
    'Position',[2.73366827697263 0.776555555555557 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[100 300000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[1e-05 28]);
box(axes3,'on');
hold(axes3,'all');

% Create semilogx
semilogx(X11,Y2,'Parent',axes3,'Marker','.','LineStyle','none');

% Create semilogx
semilogx(X12,Y2,'Parent',axes3,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X13,Y2,'Parent',axes3,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X14,Y2,'Parent',axes3,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create semilogx
semilogx(X15,Y2,'Parent',axes3,'Marker','.','LineStyle','none',...
    'Color',[0 0 1]);

% Create xlabel
xlabel({'$S_T$'},'Interpreter','latex','FontSize',12);

% Create axes
axes4 = axes('Parent',figure1,'Units','inches',...
    'Position',[1.73111191626409 3.77777777777778 1 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[1e-05 5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0 28]);
box(axes4,'on');
hold(axes4,'all');

% Create multiple lines using matrix input to plot
plot(X16,YMatrix2,'Parent',axes4,'MarkerSize',10,'Marker','o','LineWidth',2,...
    'LineStyle','none');

% Create axes
axes5 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'Units','inches',...
    'Position',[0.477777777777778 3.77777777777777 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[100.001 40000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0 28]);
box(axes5,'on');
hold(axes5,'all');

% Create semilogx
semilogx(X17,Y3,'Parent',axes5,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X18,Y4,'Parent',axes5,'Marker','.','LineStyle','none');

% Create semilogx
semilogx(X19,Y5,'Parent',axes5,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X20,Y6,'Parent',axes5,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X21,Y7,'Parent',axes5,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create ylabel
ylabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes6 = axes('Parent',figure1,'Units','inches',...
    'Position',[1.73111191626409 2.28229493464052 1 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[1e-05 5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0 28]);
box(axes6,'on');
hold(axes6,'all');

% Create multiple lines using matrix input to plot
plot(X16,YMatrix3,'Parent',axes6,'MarkerSize',10,'Marker','o','LineWidth',2,...
    'LineStyle','none');

% Create axes
axes7 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'Units','inches',...
    'Position',[0.488888888888888 2.2822949346405 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[100.001 99999]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0 28]);
box(axes7,'on');
hold(axes7,'all');

% Create semilogx
semilogx(X22,Y8,'Parent',axes7,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X23,Y8,'Parent',axes7,'Marker','.','LineStyle','none');

% Create semilogx
semilogx(X24,Y8,'Parent',axes7,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X25,Y8,'Parent',axes7,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X26,Y8,'Parent',axes7,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create ylabel
ylabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create axes
axes8 = axes('Parent',figure1,'XTick',[1 2 3 4 5],'Units','inches',...
    'Position',[1.73111191626409 0.776555555555556 1 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[1e-05 5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[1e-06 28]);
box(axes8,'on');
hold(axes8,'all');

% Create multiple lines using matrix input to plot
plot(X16,YMatrix4,'Parent',axes8,'MarkerSize',10,'Marker','o','LineWidth',2,...
    'LineStyle','none');

% Create xlabel
xlabel({'$\mathbf{\kappa}$ ($2\pi N_0 /a$)'},'Interpreter','latex',...
    'FontSize',12);

% Create axes
axes9 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'Units','inches',...
    'Position',[0.484111111111111 0.776555555555556 1.25 1.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[100 100000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[0 28]);
box(axes9,'on');
hold(axes9,'all');

% Create semilogx
semilogx(X27,Y9,'Parent',axes9,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X28,Y9,'Parent',axes9,'Marker','.','LineStyle','none');

% Create semilogx
semilogx(X29,Y9,'Parent',axes9,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X30,Y9,'Parent',axes9,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create semilogx
semilogx(X31,Y9,'Parent',axes9,'Marker','.','LineStyle','none',...
    'Color',[0 0.498039215686275 0]);

% Create xlabel
xlabel({'$S_L$'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create textbox
annotation(figure1,'textbox',...
    [0.663239074550129 0.899799599198396 0.254498714652955 0.0460921843687332],...
    'Interpreter','latex',...
    'String',{'[111] c=0.05'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.665244215938302 0.623286573146289 0.254498714652955 0.0460921843687331],...
    'Interpreter','latex',...
    'String',{'[100] c=0.05'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.664678663239073 0.346773547094184 0.254498714652955 0.0460921843687331],...
    'Interpreter','latex',...
    'String',{'[100] c=0.5'},...
    'FontSize',12,...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

