function m_eig_3d_plot_createfigure(X1, Y1, U1, V1)
%CREATEFIGURE(X1,Y1,U1,V1)
%  X1:  quiver x
%  Y1:  quiver y
%  U1:  quiver u
%  V1:  quiver v

%  Auto-generated by MATLAB on 30-Oct-2012 17:46:31

% Create figure
figure1 = figure('XVisual',...
    '0x94 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'Position',[0.388888888888889 0.508444444444444 3.5 3.5],...
    'LineWidth',2);
box(axes1,'on');
hold(axes1,'all');

% Create quiver
quiver(X1,Y1,U1,V1,'LineWidth',2,'AutoScaleFactor',0.889999985694885,...
    'Parent',axes1,...
    'DisplayName','$(\hat e_x , \hat e_y)$');

% Create xlabel
xlabel({'x (LJ units)'},'Interpreter','latex');

% Create ylabel
ylabel({'y (LJ units)'},'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches');

