function sedald = m_joe_ald2nmd( nmd , ald )
%sedald = m_joe_ald2nmd( nmd , sed , ald )
%sort joe ald to my nmd



for ikpt = 1:nmd.NUM_KPTS
    
    nmd.kptmodelist( (ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES,1:3) = ...
        repmat(nmd.kptmaster(ikpt,:),nmd.NUM_MODES,1);
    
    I = find(...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,1))==abs(ald.kpt(:,1)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,2))==abs(ald.kpt(:,2)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,3))==abs(ald.kpt(:,3)) );
  
    if length(I)==0
        I = find(...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,1))==abs(ald.kpt(:,3)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,2))==abs(ald.kpt(:,1)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,3))==abs(ald.kpt(:,2)) );
    end
    if length(I)==0
        I = find(...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,1))==abs(ald.kpt(:,2)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,2))==abs(ald.kpt(:,3)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,3))==abs(ald.kpt(:,1)) );
    end
    if length(I)==0
        I = find(...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,1))==abs(ald.kpt(:,2)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,2))==abs(ald.kpt(:,1)) &...
        abs(nmd.kptmodelist((ikpt-1)*nmd.NUM_MODES+1,3))==abs(ald.kpt(:,3)) );
    end
%     I
%     ald.kpt(I(1:nmd.NUM_MODES),:)
%     sed.kpt((ikpt-1)*nmd.NUM_MODES+1,:)
%     flipdim(ald.life(I(1:nmd.NUM_MODES)),1)
%     sed.life((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES)
    
%     plot(...
%         flipdim(ald.life(I(1:nmd.NUM_MODES)),1),...
%         flipdim(ald.life(I(1:nmd.NUM_MODES)),1),...
%         flipdim(ald.life(I(1:nmd.NUM_MODES)),1),...
%         sed.life((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES),'.')

sedald.freq((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES,1) =...
    flipdim(ald.freq(I(1:nmd.NUM_MODES)),1);
sedald.life((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES,1) =...
    flipdim(ald.life(I(1:nmd.NUM_MODES)),1);
sedald.vel((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES,1:3) =...
    flipdim(ald.vel(I(1:nmd.NUM_MODES),1:3),1);

sedald.freq_shift((ikpt-1)*nmd.NUM_MODES+1:(ikpt)*nmd.NUM_MODES,1) =...
    flipdim(ald.freq_shift(I(1:nmd.NUM_MODES)),1);


%--------------------------------------------------------------------------
%pause
%-------------------------------------------------------------------------- 
end

end