clear

lj = m_lj; constant = m_constant;
    

ald = m_lj_cond_alloy_ald_results
gk = m_lj_cond_alloy_gk_results
vc = m_lj_cond_alloy_nmd_vc_results

subplot(2,1,1),...
semilogy(...
ald.conc,vc.extrap,'.',...
ald.conc,ald.extrap,'.',...
ald.conc,gk.extrap,'.',...
ald.conc,vc.high_scatter,'.'...
)
subplot(2,1,2),...
semilogy(...
ald.conc,vc.extrap_diff,'.',...
ald.conc,ald.extrap_diff,'.',...
ald.conc,gk.extrap,'.',...
ald.conc,vc.high_scatter,'.'...
)


% m_lj_cond_alloy_results_createfigure(...
% gk.conc,...
% [gk.extrap ald.extrap(:,1) vc.extrap(:,1) ald.perfect]...
% )
