clear
constant = m_constant;
size_big = 100000;

ald = m_lj_cond_alloy_ald_results
gk = m_lj_cond_alloy_gk_results
vc = m_lj_cond_alloy_nmd_vc_results

ald40 = m_lj_cond_alloy_ald_results_40K
gk40 = m_lj_cond_alloy_gk_results_40K

subplot(2,1,1),...
semilogy(...
    gk.conc, gk.extrap , '.',...
    ald.conc, vc.extrap,'.',...
    ald.conc, ald.extrap , '.',...
    ald.conc, vc.extrap_diff,'.',...
    ald.conc, ald.extrap_diff , '.',...
    ald.conc, ald.high_scatter , '.'...
    )
subplot(2,1,2),...
plot(...
    gk40.conc, gk40.extrap , '.',...
    ald40.conc, ald40.extrap , '.',...
    ald40.conc, ald40.extrap_diff , '.',...
    ald40.conc, ald40.high_scatter , '.'...
    )


