function m_lj_nmd_xcorr_compare_sed_createfigure(X1, YMatrix1, X2, Y1, X3, Y2)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1,X3,Y2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 26-Dec-2012 17:48:12

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'Units','inches',...
    'Position',[0.6 0.6 4 3.5]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[10 1000000]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',axes1,'LineStyle','none');
set(semilogy1(1),'Marker','o',...
    'Color',[0 0.749019607843137 0.749019607843137],...
    'DisplayName','$\nu=3$');
set(semilogy1(2),'Marker','square','DisplayName','$\nu=4$');

% Create semilogy
semilogy(X2,Y1,'Parent',axes1,'LineWidth',2,'Color',[0 0 1],...
    'DisplayName','$\nu=3$ fit');

% Create semilogy
semilogy(X3,Y2,'Parent',axes1,'LineWidth',2,'Color',[0 0.498039215686275 0],...
    'DisplayName','$\nu=4$ fit');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'SED (LJ units)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[1.77083333333333 0.724305555555559 1.16111111111111 1.05416666666667]);

% Create line
annotation(figure1,'line',[0.245412844036697 0.245412844036697],...
    [0.910616161616162 0.108585858585859]);

% Create line
annotation(figure1,'line',[0.704128440366973 0.705779816513767],...
    [0.742424242424243 0.111313131313135]);

% Create textbox
annotation(figure1,'textbox',...
    [0.6861376146789 0.070909090909091 0.00358715596330267 0.0303030303030305],...
    'Interpreter','latex',...
    'String',{'$\omega_0$'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.225770642201835 0.0681818181818182 0.00358715596330267 0.0303030303030305],...
    'Interpreter','latex',...
    'String',{'$\omega_0$'},...
    'FitBoxToText','off',...
    'EdgeColor',[1 1 1]);

