clear

lj = m_lj;
c = m_constant;

str_nmd = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/';

%nmd.nmdfit_o = load([str_nmd 'NMDfit_orig.mat']);
%nmd.sedfit_o = load([str_nmd 'SEDfit_orig.mat']);

nmd.nmddata_o = load([str_nmd 'NMDdata_orig.mat']);
nmd.seddata_o = load([str_nmd 'SEDdata_orig.mat']);

nmd.seddata_o = nmd_convert_data(nmd.nmddata_o,nmd.seddata_o);

nmd.nmddata = load([str_nmd 'NMDdata_new.mat']);
nmd.seddata = load([str_nmd 'SEDdata_new.mat']);

%nmd.seddata = nmd_convert_data(nmd.nmddata,nmd.seddata);

str_nmd2 = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/';

nmd2.nmddata = load([str_nmd2 'NMDdata.mat']);
nmd2.seddata = load([str_nmd2 'SEDdata.mat']);

nmd2.seddata = nmd_convert_data(nmd2.nmddata,nmd2.seddata);

str_nmd3 = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD_AF/1/work/';

nmd3.nmddata = load([str_nmd3 'NMDdata_modify.mat']);
nmd3.seddata = load([str_nmd3 'SEDdata_modify.mat']);

str_nmd4 = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD/1/work/';

nmd4.nmddata = load([str_nmd4 'NMDdata.mat']);
nmd4.seddata = load([str_nmd4 'SEDdata.mat']);

%amor
sed(4).sed =...
    load('/home/jason/disorder2/lj/amor/8x/XCORR_AF/2^19_2^16/SEDfit.mat');

[I,J] = find(...
    nmd.seddata.kpt(:,1)==1 & ...
    nmd.seddata.kpt(:,2)==0 & ...
    nmd.seddata.kpt(:,3)==0 )

loglog(...
    nmd2.seddata.freq,...
    nmd2.seddata.life,'.',...
    nmd3.seddata.HLDfreq,1.0*nmd3.seddata.life,'.',...
    nmd.seddata.freq,nmd.seddata.life,'.',...
    nmd.seddata.freq,...
    1E4./( (nmd.seddata.freq).^(4) ),...
    nmd.seddata.freq,...
    1E2./( (nmd.seddata.freq).^(2) ),...
    nmd.seddata.freq,...
    (2*pi)./( (nmd.seddata.freq).^(1) )...
    )

nmd.seddata.irrkpt.life(:,50)/lj.tau
nmd.seddata.life( I ) 

nmd.seddata.freq( I ) 
nmd.seddata.sedfreq( I ) 

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

loglog(...
    nmd2.seddata.freq,...
    nmd2.seddata.life,'.',...
    sed(4).sed.HLDfreq,sed(4).sed.life,'.',...
    nmd.seddata.freq,...
    2E2./( (nmd.seddata.freq).^(1.9) ),...
    sed(4).sed.HLDfreq,...
    (2*pi)./( (sed(4).sed.HLDfreq).^(1) )...
    )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------






























%100
kpt(1) = 50; mode(1) = 3; kpt(2) = 50; mode(2) = 4;
semilogy(...
    nmd2.seddata.omega(1:4000),nmd2.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),...
    nmd2.seddata.omega(1:4000),nmd2.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)),...
    nmd.seddata.omega(1:4000),nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),...
    0.98*nmd.seddata.omega(1:4000),nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)),...
    nmd4.seddata.omega(1:4000),nmd4.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),...
    nmd4.seddata.omega(1:4000),...
    smooth(nmd4.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)),20)...
    )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
















%NOT USED BELOW



%--------------------------------------------------------------------------
%define mode properties from NMD
%--------------------------------------------------------------------------

dt = 8*0.002; tf = 5000; N = ceil(tf/dt);
t = linspace(0,2*tf,N);
%get lifetimes
life(1) = 0.5*nmd.seddata.irrkpt.life(3,50)/lj.tau;
freq(1) = nmd.seddata.sedfreq( I(3) );
life(2) = nmd.seddata.irrkpt.life(4,50)/lj.tau;
freq(2) = nmd.seddata.sedfreq( I(4) ); 
life(3) = nmd.seddata.irrkpt.life(4,50)/lj.tau;
freq(3) = nmd.seddata.sedfreq( I(4) ); 


%lor
lor(1).lor =...
    1 ./ ( ( nmd.seddata.omega(1:4000) - freq(1) ).^2 + ( 1/(4*life(1)))^2)...
    ;
lor(2).lor =...
    1 ./ ( ( nmd.seddata.omega(1:4000) - freq(2) ).^2 + ( 1/(2*life(2)))^2)...
    ;


semilogy(...
    nmd.seddata.omega(1:4000),...
    nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),'.',...
    nmd.seddata.omega(250:375),...
    1.05*lor(1).lor(250:375)*(...
    max(nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)))/...
    max(lor(1).lor(250:375))),...
    nmd.seddata.omega(1:4000),...
    nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)),'.',...
    nmd.seddata.omega(1425:1550),...
    0.9*lor(2).lor(1425:1550)*(...
    max(nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)))/...
    max(lor(2).lor(1425:1550)))...
    )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

rng(11111);
%1
xc(1).KE =...
    (cos(freq(1)*t).^2 + 0.01*rand(1,length(t))).*exp(-t/life(1)) +...
    0.01*rand(1,length(t)).*exp(-t/life(1)*0.8);
xc(1).EE =...
    exp(-t/life(1)*0.98) + ...
    0.01*rand(1,length(t)).*exp(-t/life(1)*0.8);
%2
xc(2).KE =...
    (...
    (cos(freq(2)*t) ).^2 ...
    ).*...
    exp(-t/life(2)*1.02)+...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.9);
xc(2).KEPE =...
    (...
    (sin(freq(2)*t) ).^2 ...
    ).*...
    exp(-t/life(2)*0.98) +...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.9);

xc(2).EE =...
    xc(2).KE/max(xc(2).KE) + xc(2).KEPE/max(xc(2).KEPE) + ...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.95);

%--------------------------------------------------------------------------

%make saturate
xc(1).integral = 2*cumtrapz(xc(1).EE(:)/max(xc(1).EE(:)))*dt + ...
    0.1*rand(1,length(t))';
xc(1).integral(10000:end) = life(1) + 0.1*rand(1,length(xc(1).integral(10000:end)))';
xc(2).integral = 2*cumtrapz(xc(2).EE(:)/max(xc(2).EE(:)))*dt + ...
    0.1*rand(1,length(t))';
xc(2).integral(5000:end) = life(2) + 0.1*rand(1,length(xc(2).integral(5000:end)))';

%xcorr

subplot(2,1,1),...
plot(...
    t(1:2000),xc(1).KE(1:2000)/max(xc(1).KE(1:2000)),...
    t(1:2000),xc(1).EE(1:2000)/max(xc(1).EE(1:2000)),...
    t(1:2000),xc(2).KE(1:2000)/max(xc(2).KE(1:2000)),...
    t(1:2000),xc(2).EE(1:2000)/max(xc(2).EE(1:2000))...
    )
subplot(2,1,2),...
plot(...
    t(1:10000),...
    xc(1).integral(1:10000),...
    t(1:10000),...
    xc(2).integral(1:10000)...
    )

% m_lj_nmd_xcorr_compare_createfigure(...
%     nmd.seddata.omega(1:5000),...
%     [...
%     nmd.seddata.irrkpt.sedavg(1:5000,mode(1),kpt(1))...
%     smooth(...
%     nmd.seddata.irrkpt.sedavg(1:5000,mode(2),kpt(2))...
%     ,20)...
%     ],...
%     t(1:1500),...
%     [...
%     xc(1).KE(1:1500)'/max(xc(1).KE(1:1500)) ...
%     xc(1).EE(1:1500)'/max(xc(1).EE(1:1500)) ...
%     xc(2).KE(1:1500)'/max(xc(2).KE(1:1500)) ...
%     xc(2).EE(1:1500)'/max(xc(2).EE(1:1500))...
%     ]...
%     )







% %1
% t1f = 500; N1 = ceil(t1f/dt);
% t1 = linspace(0,2*t1f,N1);
% q(1).q = exp(-abs(t1 - t1f)/life(1)).*( cos(freq(1)*abs(t1 - t1f)) );
% q(1).qd = exp(-abs(t1 - t1f)/life(1)).*( sin(freq(1)*abs(t1 - t1f)) );
% plot(...
%     t1, q(1).q , t1 , q(1).qd...
%     )
% pause
% q(1).q = repmat(q(1).q,1,floor(length(t) / length(t1)));
% q(1).qd = repmat(q(1).qd,1,floor(length(t) / length(t1)));
% plot(...
%     t, q(1).q , t , q(1).qd...
%     )
% pause
% %2  
% t2f = 10; N2 = ceil(t2f/dt);
% t2 = linspace(0,2*t2f,N2);
% q(2).q = exp(-abs(t2 - t2f)/life(2)).*( cos(freq(2)*abs(t2 - t2f)) );
% q(2).qd = exp(-abs(t2 - t2f)/life(2)).*( sin(freq(2)*abs(t2 - t2f)) );
% plot(...
%     t2, q(2).q , t2 , q(2).qd...
%     )
% pause
% q(2).q = repmat(q(2).q,1,floor(length(t) / length(t2)));
% q(2).qd = repmat(q(2).qd,1,floor(length(t) / length(t2)));
% plot(...
%     t, q(2).q , t , q(2).qd...
%     )
% pause

% %--------------------------------------------------------------------------
% pause
% %--------------------------------------------------------------------------
% energy(1).V = q(1).q.^2; energy(1).T = q(1).qd.^2; 
% energy(1).E = energy(1).V/max(energy(1).V) + energy(1).T/max(energy(1).T) 
% energy(2).V = q(2).q.^2; energy(2).T = q(2).qd.^2; 
% energy(2).E = energy(2).V/max(energy(2).V) + energy(2).T/max(energy(2).T) 
% 
% EE1 = xcorr(energy(1).E - mean(energy(1).E),'coeff');
% TT1 = xcorr(energy(1).T/max(energy(1).T)  ,'coeff');
% TV1 = xcorr(energy(1).T,energy(1).V ,'coeff');
% plot(...
%     t , TT1(ceil(length(t):length(TT1))),...
%     t , EE1(ceil(length(t):length(EE1))),...
%     t , TV1(ceil(length(t):length(TV1)))...
%     )
% %--------------------------------------------------------------------------
% pause
% %--------------------------------------------------------------------------
% EE2 = xcorr(energy(2).E - mean(energy(2).E),'coeff');
% TT2 = xcorr(energy(2).T/max(energy(2).T) - mean(energy(2).T/max(energy(2).T))  ,'coeff');
% TV2 = xcorr(energy(2).T,energy(2).V ,'coeff');
% plot(...
%     t , TT2(ceil(length(t):length(TT2))),...
%     t , EE2(ceil(length(t):length(EE2))),...
%     t , TV2(ceil(length(t):length(TV2)))...
%     )
% %--------------------------------------------------------------------------
% pause
% %--------------------------------------------------------------------------
% 
% 
% 
% 
% pause
% 
% w = 0:0.0001:100;
% w0(1) = 10; w0(2) = 50;
% 
% 
% 
% lor1 = 1 ./ ( (w - w0(1)).^2 + 1);
% lor2 = 1 ./ ( (w - w0(2)).^2 + 1);
% 
% semilogy( w , lor1 + lor2 )
% 
% plot(1:length(lor1), real(fft(lor1+lor2)))


% exp(-t./life(1)).*exp(-1i*freq(1)*t).*...
%     exp(-1i*(freq(1)+freq(1)*0.05)*t)...


% str_nmd = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD/1/work/';
% nmd.nmdfit = load([str_nmd 'NMDfit_orig.mat']);
% nmd.sedfit = load([str_nmd 'SEDfit_orig.mat']);
% 
% str_nmdaf = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD_AF/1/work/';
% nmdaf.nmdfit = load([str_nmdaf 'NMDfit_orig.mat']);
% nmdaf.sedfit = load([str_nmdaf 'SEDfit_orig.mat']);
% str_xcorr = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/XCORR_AF/1/work/';
% xcorr.nmdfit = load([str_xcorr 'NMDfit.mat']);
% xcorr.sedfit = load([str_xcorr 'SEDfit.mat']);
% 
% loglog(...
%     nmdaf.sedfit.HLDfreq,nmdaf.sedfit.life,'.',...
%     xcorr.sedfit.HLDfreq,xcorr.sedfit.life,'.'...
%     )
% 
% pause
% 
% 
% nmd.nmdavg = load([str_nmd 'NMDavg_orig.mat']);
% nmd.sedavg = load([str_nmd 'SEDavg_orig.mat']);
% 
% nmdaf.nmdavg = load([str_nmdaf 'NMDavg_orig.mat']);
% nmdaf.sedavg = load([str_nmdaf 'SEDavg_orig.mat']);
% 
% xcorr.nmdavg = load([str_xcorr 'NMDavg.mat']);
% xcorr.sedavg = load([str_xcorr 'SEDavg.mat']);
% 
% for imode=1000:1:size(nmdaf.sedavg.sed(:,:),2)
% subplot(3,1,1),...
% semilogy(...
%     nmdaf.sedavg.omega(1:5000),nmd.sedavg.irrkpt.sedavg(1:5000,7,8)...
%     )
% subplot(3,1,2),...
% semilogy(...
%     nmdaf.sedavg.omega(1:2500),nmdaf.sedavg.sed(1:2500,imode)...
%     )
% subplot(3,1,3),...
%     plot(...
%     xcorr.sedavg.omega(1:200),xcorr.sedavg.sed(1:200,imode)...
%     )
% nmdaf.sedfit.HLDfreq(imode)
% nmdaf.sedfit.life(imode)
% imode
% pause
% end
% 
% %create
% 
% for ikpt=1:size(nmd.sedavg.irrkpt.sedavg,3)
%     for imode=1:size(nmd.sedavg.irrkpt.sedavg,2)
% 
% semilogy(...
%     nmdaf.sedavg.omega(1:5000),nmd.sedavg.irrkpt.sedavg(1:5000,imode,ikpt)...
%     )
% pause
% 
% imode
% ikpt
%     end
% end

% for imode=1000:1:size(nmdaf.sedavg.sed(:,:),2)
% subplot(3,1,1),...
% semilogy(...
%     nmdaf.sedavg.omega(1:5000),nmd.sedavg.irrkpt.sedavg(1:5000,7,8)...
%     )
% subplot(3,1,2),...
% semilogy(...
%     nmdaf.sedavg.omega(1:2500),nmdaf.sedavg.sed(1:2500,imode)...
%     )
% subplot(3,1,3),...
%     plot(...
%     xcorr.sedavg.omega(1:200),xcorr.sedavg.sed(1:200,imode)...
%     )
% nmdaf.sedfit.HLDfreq(imode)
% nmdaf.sedfit.life(imode)
% imode
% pause
% end



