clear

lj = m_lj;
c = m_constant;

str_nmd = '/home/jason/disorder2/lj/alloy/10K/0.0/10x/NMD/1/work/';

%nmd.nmdfit_o = load([str_nmd 'NMDfit_orig.mat']);
%nmd.sedfit_o = load([str_nmd 'SEDfit_orig.mat']);

nmd.nmddata_o = load([str_nmd 'NMDdata_messedup.mat']);
nmd.seddata_o = load([str_nmd 'SEDdata_messedup.mat']);

nmd.seddata_o = nmd_convert_data(nmd.nmddata_o,nmd.seddata_o);

nmd.nmddata = load([str_nmd 'NMDdata.mat']);
nmd.seddata = load([str_nmd 'SEDdata.mat']);

nmd.seddata = nmd_convert_data(nmd.nmddata,nmd.seddata);

sed.conv =...
    load('/home/jason/sed/data/LJ/sed_conv_10x_20K.dat');
sed.prim =...
    load('/home/jason/sed/data/LJ/sed_prim_10x_20K.dat');

%plot tau fs freq
loglog(...
    nmd.seddata.freq,nmd.seddata.life,'.',...
    nmd.seddata.freq,(1E2)*nmd.seddata.freq.^(-1.9),...
    nmd.seddata.freq,(2*pi)./nmd.seddata.freq...
    )
pause


loglog(...
    sed.conv(:,1),sed.conv(:,3),'.')

% loglog(...
%     [nmd.seddata.freq(1:12:end);nmd.seddata.freq(2:12:end)],...
%     [nmd.seddata.life(1:12:end);nmd.seddata.life(2:12:end)] ,'.',...
%     nmd.seddata.freq(3:12:end),nmd.seddata.life(3:12:end),'.',...
%     nmd.seddata.freq,(1E2)*nmd.seddata.freq.^(-1.75),...
%     nmd.seddata.freq,(2*pi)./nmd.seddata.freq...
%     )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------


[I,J] = find(...
    nmd.seddata.kpt(:,1)==1 & ...
    nmd.seddata.kpt(:,2)==0 & ...
    nmd.seddata.kpt(:,3)==0 )

loglog(...
    nmd.seddata.irrkpt.HLDfreq*lj.tau,nmd.seddata.irrkpt.life/lj.tau,'.',...
    nmd.seddata.freq,nmd.seddata.life,'.')

nmd.seddata.irrkpt.life(:,50)/lj.tau
nmd.seddata.life( I ) 

nmd.seddata.freq( I ) 
nmd.seddata.sedfreq( I ) 


%100
kpt(1) = 50; mode(1) = 3; kpt(2) = 50; mode(2) = 4;
semilogy(...
    nmd.seddata.omega(1:4000),nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),...
    nmd.seddata.omega(1:4000),nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2))...
    )
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%define mode properties from NMD
%--------------------------------------------------------------------------

dt = 8*0.002; tf = 5000; N = ceil(tf/dt);
t = linspace(0,2*tf,N);
%get lifetimes
life(1) = 0.5*nmd.seddata.irrkpt.life(3,50)/lj.tau;
freq(1) = nmd.seddata.sedfreq( I(3) );
life(2) = nmd.seddata.irrkpt.life(4,50)/lj.tau;
freq(2) = nmd.seddata.sedfreq( I(4) ); 
life(3) = nmd.seddata.irrkpt.life(4,50)/lj.tau;
freq(3) = nmd.seddata.sedfreq( I(4) ); 


%lor
lor(1).lor =...
    1 ./ ( ( nmd.seddata.omega(1:4000) - freq(1) ).^2 + ( 1/(4*life(1)))^2)...
    ;
lor(2).lor =...
    1 ./ ( ( nmd.seddata.omega(1:4000) - freq(2) ).^2 + ( 1/(2*life(2)))^2)...
    ;


semilogy(...
    nmd.seddata.omega(1:4000),...
    nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)),'.',...
    nmd.seddata.omega(250:367),...
    0.95*lor(1).lor(250:367)*(...
    max(nmd.seddata.irrkpt.sedavg(1:4000,mode(1),kpt(1)))/...
    max(lor(1).lor(250:367))),...
    nmd.seddata.omega(1:4000),...
    nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)),'.',...
    nmd.seddata.omega(1425:1537),...
    0.9*lor(2).lor(1425:1537)*(...
    max(nmd.seddata.irrkpt.sedavg(1:4000,mode(2),kpt(2)))/...
    max(lor(2).lor(1425:1537)))...
    )

% m_lj_nmd_xcorr_compare_sed_createfigure(...
%     X1, YMatrix1, X2, Y1, X3, Y2)

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

rng(11111);
%1
xc(1).KE =...
    (cos(freq(1)*t).^2 + 0.01*rand(1,length(t))).*exp(-t/life(1)) +...
    0.01*rand(1,length(t)).*exp(-t/life(1)*0.8);
xc(1).EE =...
    exp(-t/life(1)*0.98) + ...
    0.01*rand(1,length(t)).*exp(-t/life(1)*0.8);
%2
xc(2).KE =...
    (...
    (cos(freq(2)*t) ).^2 ...
    ).*...
    exp(-t/life(2)*1.02)+...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.9);
xc(2).KEPE =...
    (...
    (sin(freq(2)*t) ).^2 ...
    ).*...
    exp(-t/life(2)*0.98) +...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.9);

xc(2).EE =...
    xc(2).KE/max(xc(2).KE) + xc(2).KEPE/max(xc(2).KEPE) + ...
    0.01*rand(1,length(t)).*exp(-t/life(2)*0.95);

%--------------------------------------------------------------------------

%make saturate
xc(1).integral = 2*cumtrapz(xc(1).EE(:)/max(xc(1).EE(:)))*dt + ...
    0.1*rand(1,length(t))';
xc(1).integral(10000:end) = life(1) + 0.1*rand(1,length(xc(1).integral(10000:end)))';
xc(2).integral = 2*cumtrapz(xc(2).EE(:)/max(xc(2).EE(:)))*dt + ...
    0.1*rand(1,length(t))';
xc(2).integral(5000:end) = life(2) + 0.1*rand(1,length(xc(2).integral(5000:end)))';

%xcorr

subplot(2,1,1),...
plot(...
    t(1:2000),xc(1).KE(1:2000)/max(xc(1).KE(1:2000)),...
    t(1:2000),xc(1).EE(1:2000)/max(xc(1).EE(1:2000)),...
    t(1:2000),xc(2).KE(1:2000)/max(xc(2).KE(1:2000)),...
    t(1:2000),xc(2).EE(1:2000)/max(xc(2).EE(1:2000))...
    )
subplot(2,1,2),...
plot(...
    t(1:10000),...
    xc(1).integral(1:10000),...
    t(1:10000),...
    xc(2).integral(1:10000)...
    )

% m_lj_nmd_xcorr_compare_createfigure(...
%     nmd.seddata.omega(1:5000),...
%     [...
%     nmd.seddata.irrkpt.sedavg(1:5000,mode(1),kpt(1))...
%     smooth(...
%     nmd.seddata.irrkpt.sedavg(1:5000,mode(2),kpt(2))...
%     ,20)...
%     ],...
%     t(1:1500),...
%     [...
%     xc(1).KE(1:1500)'/max(xc(1).KE(1:1500)) ...
%     xc(1).EE(1:1500)'/max(xc(1).EE(1:1500)) ...
%     xc(2).KE(1:1500)'/max(xc(2).KE(1:1500)) ...
%     xc(2).EE(1:1500)'/max(xc(2).EE(1:1500))...
%     ]...
%     )








