clear
constant = m_constant;
size_big = 100000;

ald = m_lj_cond_alloy_ald_results_40K

plot(...
    1./[ald.size;size_big] , 1./[ald.cond(:,2);8] , '.',...
    1./[ald.size;size_big] , 1./[ald.cond(:,4);3.4] , '.'...
    )

[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),1)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),2)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),3)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),4)]...
    );
R
1./p(2)

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond_diff( size(ald.size,1) - 3 : size(ald.size,1),2)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond_diff( size(ald.size,1) - 3 : size(ald.size,1),3)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
    [ald.cond_diff( size(ald.size,1) - 3 : size(ald.size,1),4)]...
    );
R
1./p(2)