clear
constant = m_constant;
size_big = 100000;

gk = m_lj_cond_alloy_gk_results

plot(...
    1./[gk.size;size_big] , 1./[gk.cond(:,2);0.8] , '.',...
    1./[gk.size;size_big] , 1./[gk.cond(:,3);0.5] , '.',...
    1./[gk.size;size_big] , 1./[gk.cond(:,4);0.3] , '.'...
    )
[p R] = m_cond_extrap([gk.size], [gk.cond(:,2)]);
R
1./p(2)
[p R] = m_cond_extrap([gk.size], [gk.cond(:,3)]);
R
1./p(2)
[p R] = m_cond_extrap([gk.size], [gk.cond(:,4)]);
R
1./p(2)

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
% plot(...
%     1./[ald.size;size_big] , 1./[ald.cond(:,2);8] , '.',...
%     1./[ald.size;size_big] , 1./[ald.cond(:,4);3.4] , '.'...
%     )
% [p R] = m_cond_extrap(...
%     [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
%     [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),2)]...
%     );
% R
% 1./p(2)
% [p R] = m_cond_extrap(...
%     [ald.size( size(ald.size,1) - 3 : size(ald.size,1))  ],...
%     [ald.cond( size(ald.size,1) - 3 : size(ald.size,1),4)]...
%     );
% R
% 1./p(2)
