clear

ipt=1
VIRTUAL_MASS = 1.1;
freq_cutoff = 0;
dph_scaling = 0.5;
vg_scaling = 0.75;
constant = m_constant; lj = m_lj;
%vcnmd
str.nmd = '/home/jason/disorder2/lj/alloy/40K/0.5/14x/NMD/';
vcnmd(ipt).nmd = load([str.nmd 'nmd.mat']);
%vcald
str.alloy = '/home/jason/disorder2/lj/alloy/40K/0.5/14x/NMD/';
alloy(ipt).alloy = load([str.alloy 'ALLOY.mat']);
str.ald = '/home/jason/disorder2/lj/ald/m2/40K/14x/Data_fullBZ.xls';
vcald(ipt).ald = m_joe_read_data([str.ald]);
vcald(ipt).sedald = m_joe_ald2nmd( vcnmd(ipt).nmd , vcald(ipt).ald );

ald(ipt).cond =...
    m_ald_cond(...
    1./(1./vcald(ipt).sedald.life)*vcnmd(ipt).nmd.lj.tau,...
    vcald(ipt).sedald.vel(:,1)*vcnmd(ipt).nmd.lj.sigma/vcnmd(ipt).nmd.lj.tau,...
    vcnmd(ipt).nmd.x0.VOLUME*vcnmd(ipt).nmd.lj.sigma^3);

vcald(ipt).cond =...
    m_ald_cond(...
    1./(1./alloy(ipt).alloy.life +...
    1./vcald(ipt).sedald.life)*vcnmd(ipt).nmd.lj.tau,...
    vcald(ipt).sedald.vel(:,1)*vcnmd(ipt).nmd.lj.sigma/vcnmd(ipt).nmd.lj.tau,...
    vcnmd(ipt).nmd.x0.VOLUME*vcnmd(ipt).nmd.lj.sigma^3);

ald(ipt).cond

vcald(ipt).cond


loglog(...
    vcald(ipt).sedald.freq,...
    1./(1./alloy(ipt).alloy.life + 1./vcald(ipt).sedald.life),'.',...
    vcald(ipt).sedald.freq,(2*pi)./vcald(ipt).sedald.freq...
    )
pause
loglog(...
    vcald(ipt).sedald.freq,...
    1./(1./alloy(ipt).alloy.life + 1./vcald(ipt).sedald.life).*...
    vcald(ipt).sedald.vel(:,1),'.',...
    vcald(ipt).sedald.freq,...
    ones(length(vcald(ipt).sedald.freq),1)*...
    (1/3)*(vcnmd(1).nmd.x0.alat/2)*lj.sound_40K/sqrt(vcnmd(ipt).nmd.x0.vm)...
    )


%--------------------------------------------------------------------------
%ald
%--------------------------------------------------------------------------
%adjust for D_ph
vcald(ipt).sedald.Dphi =...
    1./(1./alloy(ipt).alloy.life + 1./vcald(ipt).sedald.life).*...
    (vcald(ipt).sedald.vel(:,1).^2);
vcald(ipt).sedald.Dphf = vcald(ipt).sedald.Dphi;
[Idiff Jdiff] =...
    find(...
    vcald(ipt).sedald.freq > freq_cutoff & ...
    vcald(ipt).sedald.Dphi < ...
    (1/3)*lj.sound_40K/sqrt(vcnmd(ipt).nmd.x0.vm)*...
    vcnmd(ipt).nmd.x0.alat*dph_scaling ...
    );
%swap values
vcald(ipt).sedald.Dphf(Idiff) = ...
    (1/3)*lj.sound_40K/sqrt(vcnmd(ipt).nmd.x0.vm)*...
    vcnmd(ipt).nmd.x0.alat*dph_scaling
old_cond =...
    (constant.kb/(vcnmd(ipt).nmd.x0.VOLUME*lj.sigma^3))*...
    sum(...
    vcald(ipt).sedald.Dphi*...
    lj.sigma^2/lj.tau...
    )
new_cond =...
    (constant.kb/(vcnmd(ipt).nmd.x0.VOLUME*lj.sigma^3))*...
    sum(...
    vcald(ipt).sedald.Dphf*...
    lj.sigma^2/lj.tau...
    )
%--------------------------------------------------------------------------
loglog(...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.Dphi,'.',...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.Dphf,'.'...
    )
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
