function m_nmd_joe_compare_createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Sep-2012 23:39:04

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches',...
    'OuterPosition',[0 0 4.37777777777778 3.93333333333333],...
    'FontSize',12);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 80]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Marker','.','LineStyle','none');

% Create xlabel
xlabel({'$\tau_{ald}$'},'Interpreter','latex','FontSize',15);

% Create ylabel
ylabel({'$\tau_{nmd}$'},'Interpreter','latex','FontSize',15);

