%function m_ald_taud_nmd_mix(str_ald,str_nmd_per,str_nmd_vc,str_alloy)
%--------------------------------------------------------------------------
%m_ald_taud(str_ald,str_nmd_perfect,str_nmd_vc,str_alloy)
% m_ald_taud(...
% '/home/jason/disorder/lj/ald/m1.1/10x/Data_fullBZ.xls',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/',...
% '/home/jason/disorder2/lj/alloy/10K/0.05/10x/nmd_vc/work/1/')
%--------------------------------------------------------------------------

lj = m_lj; constant = m_constant;

str_nmd_vc = '/home/jason/disorder2/lj/alloy/10K/0.05/10x/NMD/1/work/';
nmd(1).nmd=load(strcat(str_nmd_vc,'NMDdata.mat'));
sed(1).sed=load(strcat(str_nmd_vc,'SEDdata.mat'));
sed(1).sed = nmd_convert_data(nmd(1).nmd,sed(1).sed);

str_nmd_vc = '/home/jason/disorder2/lj/alloy/10K/0.15/10x/NMD/1/work/';
nmd(2).nmd=load(strcat(str_nmd_vc,'NMDdata.mat'));
sed(2).sed=load(strcat(str_nmd_vc,'SEDdata.mat'));
sed(2).sed = nmd_convert_data(nmd(2).nmd,sed(2).sed);

str_nmd_vc = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/NMD/1/work/';
nmd(3).nmd=load(strcat(str_nmd_vc,'NMDdata.mat'));
sed(3).sed=load(strcat(str_nmd_vc,'SEDdata.mat'));
sed(3).sed = nmd_convert_data(nmd(3).nmd,sed(3).sed);



m_nmd_modify_c05_gamma_createfigure(...
    sed(1).sed.freq,...
    sed(1).sed.life,...
    sed(2).sed.freq,...
    sed(2).sed.life,...
    sed(3).sed.freq,...
    sed(3).sed.life,...
    sed(3).sed.freq,...
    2*pi./sed(3).sed.freq,...
    sed(3).sed.freq,...
    1E4*(1./(sed(3).sed.freq.^4)),...
    sed(3).sed.freq,...
    1E3*(1./(sed(3).sed.freq.^2))...
    )




%end