
sed(1).sed =...
    load('/home/jason/disorder2/lj/amor/4x/XCORR_AF/5K/2^19_2^15/SEDfit.mat');
sed(2).sed =...
    load('/home/jason/disorder2/lj/amor/4x/XCORR_AF/5K/2^19_2^16/SEDfit.mat');
sed(3).sed =...
    load('/home/jason/disorder2/lj/amor/4x/XCORR_AF/5K/2^19_2^17/SEDfit.mat');
sed(4).sed =...
    load('/home/jason/disorder2/lj/amor/8x/XCORR_AF/2^19_2^16/SEDfit.mat');
sed(5).sed =...
    load('/home/jason/disorder2/lj/amor/8x/XCORR_AF/2^19_2^17/SEDfit.mat');



loglog(...
    sed(1).sed.HLDfreq,sed(1).sed.life,'.',...
    sed(2).sed.HLDfreq,sed(2).sed.life,'.',...
    sed(3).sed.HLDfreq,sed(3).sed.life,'.',...
    sed(4).sed.HLDfreq,2*pi./(sed(4).sed.HLDfreq)...
    )
pause
loglog(...
    sed(1).sed.HLDfreq,sed(1).sed.life,'.',...
    sed(4).sed.HLDfreq,sed(4).sed.life,'.',...
    sed(4).sed.HLDfreq,2*pi./(sed(4).sed.HLDfreq)...
    )

