clear

str.NMD = '/home/jason/disorder2/lj/amor/8x/XCORR_AF/2^19_2^16/';


NMD=load(strcat(str.NMD,'NMDavg.mat'));

SED=load(strcat(str.NMD,'SEDavg.mat'));

SEDavg = load('/home/jason/disorder2/lj/amor/8x/1/work/SEDavg.mat');


[tmp,str.main]=system('pwd');

XCORR_RANGE = 1000; XCORR_RANGE_1 = 1; XCORR_RANGE_2 = 1000;

%32 is good

imode(1)=13; imode(2) = 5500; avg(1) = 0.00295; avg(2) = 0.00125;
avg(1) = 0.00; %avg(2) = 0;

for im=1:1000

plot(...
    SED.omega(1:XCORR_RANGE),...
    SED.sed(1:XCORR_RANGE,im) ,...
    SED.omega(1:XCORR_RANGE),...
    cumtrapz((SED.sed(1:XCORR_RANGE,im))*SED.omega(1) + ...
    avg(1) ),...
    SED.omega(1:XCORR_RANGE),...
    SED.sed(1:XCORR_RANGE,imode(2)) ,...
    SED.omega(1:XCORR_RANGE),...
    cumtrapz((SED.sed(1:XCORR_RANGE,imode(2)))*SED.omega(1) + ...
    avg(2) ) ...
    )
pause
end

for im=1:1000
    im
semilogy(...
    SEDavg.omega(1:4000),SEDavg.sed(1:4000,im),...
    SEDavg.omega(1:4000),SEDavg.sed(1:4000,im)...
)
pause
end


imode(1)=13; imode(2) = 5500; avg(1) = 0.00295; avg(2) = 0.00125;
avg(1) = 0.0005; %avg(2) = 0;

SED.HLDfreq(imode(1))
SEDavg.HLDfreq(17)
SED.HLDfreq(imode(2))
SEDavg.HLDfreq(imode(2))

subplot(3,1,1),...
semilogy(...
    SEDavg.omega(1:5000),smooth(SEDavg.sed(1:5000,17),15),...
    SEDavg.omega(1:5000) + (SEDavg.HLDfreq(imode(2))-7.856),...
    smooth(SEDavg.sed(1:5000,750),20)...
)
subplot(3,1,2),...
plot(...
    SED.omega(1:XCORR_RANGE),...
    SED.sed(1:XCORR_RANGE,imode(1)) +0.0 ,...
    SED.omega(1:XCORR_RANGE),...
    SED.sed(1:XCORR_RANGE,imode(2)) +0.0...
    )
subplot(3,1,3),...
    plot(...
    SED.omega(1:XCORR_RANGE),...
    cumtrapz((SED.sed(1:XCORR_RANGE,imode(1)))*SED.omega(1) + ...
    avg(1) ),...
    SED.omega(1:XCORR_RANGE),...
    cumtrapz((SED.sed(1:XCORR_RANGE,imode(2)))*SED.omega(1) + ...
    avg(2) ) ...
    )

I = find((SED.sed(1:XCORR_RANGE,imode(1)) +avg(1) ) < 0);
sed_plot(1).sed = (SED.sed(1:XCORR_RANGE,imode(1)) +avg(1) );
sed_plot(1).sed(I) = 0;

I = find((SED.sed(1:XCORR_RANGE,imode(2)) +avg(2) +0.01 ) < 0);
sed_plot(2).sed = (SED.sed(1:XCORR_RANGE,imode(2)) +avg(2) +0.01 )
sed_plot(2).sed(I) = 0;

m_nmd_xcorr_fit_lj_plot_createfigure(...
    SEDavg.omega(1:5000),...
    smooth(SEDavg.sed(1:5000,17),15),...
    SEDavg.omega(1:5000) + (SEDavg.HLDfreq(imode(2))-7.856),...
    smooth(SEDavg.sed(1:5000,750),20),...
    SED.omega(1:XCORR_RANGE),...
    [...
    sed_plot(1).sed ...
    sed_plot(2).sed ...
    ],...
    [...
    (cumtrapz((SED.sed(1:XCORR_RANGE,imode(1)))*SED.omega(1) + ...
    avg(1) )) ...
    (cumtrapz((SED.sed(1:XCORR_RANGE,imode(2)))*SED.omega(1) + ...
    avg(2) )) ...
    ] ...
    )
    


