function m_pbte_cond_compare_createfigure(X1, YMatrix1, X2, Y1, X3, YMatrix2, X4, Y2)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1,X3,YMATRIX2,X4,Y2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  X4:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 13-Feb-2013 14:33:52

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'Units','inches',...
    'Position',[0.6 0.6 2.5 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.07 10]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',axes1,'Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 1]);
set(semilogy1(1),'MarkerSize',10,'DisplayName','LJ Ar c=0.0');
set(semilogy1(2),'DisplayName','LJ Ar c=0.5');
set(semilogy1(3),'LineWidth',2,'DisplayName','LJ Ar AF,HS','Marker','none',...
    'LineStyle','-');

% Create semilogy
semilogy(X2,Y1,'Parent',axes1,'Marker','square','LineStyle','none',...
    'Color',[1 0 0],...
    'DisplayName','Expt. Ref []');

% Create multiple lines using matrix input to semilogy
semilogy2 = semilogy(X3,YMatrix2,'Parent',axes1,'MarkerFaceColor',[1 0 0],...
    'Marker','diamond',...
    'LineStyle','none',...
    'Color',[1 0 0]);
set(semilogy2(1),'MarkerSize',10,...
    'DisplayName','Tian $PbTe_{1{-}c}Se_{c} c= 0.0$');
set(semilogy2(2),'DisplayName','Tian $PbTe_{1{-}c}Se_{c} c= 0.5$');

% Create semilogy
semilogy(X4,Y2,'Parent',axes1,'LineWidth',2,'Color',[1 0 0],...
    'DisplayName','PbTe AF,HS');

% Create xlabel
xlabel({'$T/T_{melt}$'},'Interpreter','latex');

% Create ylabel
ylabel({'$k$ (W/m-K)'},'Interpreter','latex');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','EdgeColor',[1 1 1],'YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'Units','inches',...
    'Position',[1.66666666666667 2.38194444444445 0.600000000000004 1.14027777777777],...
    'FontSize',8);

