clear
con = m_constant;

str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/c60/';
c60.old.freq = load([str '/oldtersoff/freq.gout']); 
c60.new.freq = load([str 'freq.gout']);

str='/home/jason/disorder/pcbm/allres/';
c60.dft.freq = load([str 'c60_vgauss']);
%c60.dft.freq(:,2) = c60.dft.freq(:,2)*con.c*2*pi; 

[c60.old.dosx c60.old.dosy] = m_dos(c60.old.freq(7:end),15,1,1); 
[c60.new.dosx c60.new.dosy] = m_dos(c60.new.freq(7:end),15,1,1);
[c60.dft.dosx c60.dft.dosy] = m_dos(c60.dft.freq(:,2),15,1,1);

% subplot(2,1,1),...
%     plot(...
%     c60.old.freq,c60.old.freq,c60.old.freq,c60.new.freq,'.')
% subplot(2,1,2),...
    plot(c60.old.dosx , c60.old.dosy , c60.new.dosx , c60.new.dosy,...
    c60.dft.dosx,c60.dft.dosy)
pause
clf

str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/pcbm28/';
pcbm28.freq = load([str '/freq.gout']); 
[pcbm28.dosx pcbm28.dosy] = m_dos(pcbm28.freq(7:end),15,1,1);

str='/home/jason/disorder/pcbm/allres/';
pcbm28.dft.freq = load([str '/pcbm28_vgauss']); 
[pcbm28.dft.dosx pcbm28.dft.dosy] = m_dos(pcbm28.dft.freq(:,2),15,1,1);

clf
plot(pcbm28.dosx , pcbm28.dosy , pcbm28.dft.dosx , pcbm28.dft.dosy)
pause

str='/home/jason/disorder/pcbm/allres/';
pcbm.dft.freq = load([str 'pbcm_vgauss']); 
[pcbm.dft.dosx pcbm.dft.dosy] = m_dos(pcbm.dft.freq(:,2),15,1,1);

str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/';
pcbm.freq = load([str '/freq.gout']); 
[pcbm.dosx pcbm.dosy] = m_dos(pcbm.freq(7:end),15,1,1);

clf
plot(pcbm.dosx , pcbm.dosy , pcbm.dft.dosx , pcbm.dft.dosy)
pause

clf
subplot(2,1,1),...
plot(...
    c60.new.dosx , c60.new.dosy,...
    pcbm28.dosx , pcbm28.dosy,...
    pcbm.dosx , pcbm.dosy...
    )
axis([0 3500 0 0.5])
subplot(2,1,2),...
plot(...
    c60.dft.dosx , c60.dft.dosy,...
    pcbm28.dft.dosx , pcbm28.dft.dosy,...
    pcbm.dft.dosx , pcbm.dft.dosy...
    )
axis([0 3500 0 0.5])
pause


%Di
pcbm.Di(1,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b0.01.gout');
pcbm.Di(2,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b0.1.gout');
pcbm.Di(3,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b1.gout');
pcbm.Di(4,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b10.gout');

pcbm.Di(1,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b0.01.gout');
pcbm.Di(2,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b0.1.gout');
pcbm.Di(3,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b1.gout');
pcbm.Di(4,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b10.gout');

pcbm.Di(1,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b0.01.gout');
pcbm.Di(2,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b0.1.gout');
pcbm.Di(3,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b1.gout');
pcbm.Di(4,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b10.gout');

pcbm.Di(1,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b0.01.gout');
pcbm.Di(2,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b0.1.gout');
pcbm.Di(3,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b1.gout');
pcbm.Di(4,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b10.gout');

clf
loglog(...
    pcbm.Di(1,1).Di(:,2),pcbm.Di(1,1).Di(:,3),'.',...
    pcbm.Di(2,1).Di(:,2),pcbm.Di(2,1).Di(:,3),'.',...
    pcbm.Di(3,1).Di(:,2),pcbm.Di(3,1).Di(:,3),'.',...
    pcbm.Di(4,1).Di(:,2),pcbm.Di(4,1).Di(:,3),'.'...
    )
pause
loglog(...
    pcbm.Di(1,2).Di(:,2),pcbm.Di(1,2).Di(:,3),'.',...
    pcbm.Di(2,2).Di(:,2),pcbm.Di(2,2).Di(:,3),'.',...
    pcbm.Di(3,2).Di(:,2),pcbm.Di(3,2).Di(:,3),'.',...
    pcbm.Di(4,2).Di(:,2),pcbm.Di(4,2).Di(:,3),'.'...
        )
pause
loglog(...
    pcbm.Di(1,3).Di(:,2),pcbm.Di(1,3).Di(:,3),'.',...
    pcbm.Di(2,3).Di(:,2),pcbm.Di(2,3).Di(:,3),'.',...
    pcbm.Di(3,3).Di(:,2),pcbm.Di(3,3).Di(:,3),'.',...
    pcbm.Di(4,3).Di(:,2),pcbm.Di(4,3).Di(:,3),'.'...
        )
pause
loglog(...
    pcbm.Di(1,4).Di(:,2),pcbm.Di(1,4).Di(:,3),'.',...
    pcbm.Di(2,4).Di(:,2),pcbm.Di(2,4).Di(:,3),'.',...
    pcbm.Di(3,4).Di(:,2),pcbm.Di(3,4).Di(:,3),'.',...
    pcbm.Di(4,4).Di(:,2),pcbm.Di(4,4).Di(:,3),'.'...
        )
pause



    
    
    
    