clear


str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/c60/';

c60.old.freq = load([str '/oldtersoff/freq.gout']); 

c60.new.freq = load([str 'freq.gout']);

[c60.old.dosx c60.old.dosy] = m_dos(c60.old.freq,10,1,1); 
[c60.new.dosx c60.new.dosy] = m_dos(c60.new.freq,10,1,1);

subplot(2,1,1),...
    plot(c60.old.freq,c60.old.freq,c60.old.freq,c60.new.freq,'.')
subplot(2,1,2),...
    plot(c60.old.dosx , c60.old.dosy , c60.new.dosx , c60.new.dosy)
pause
clf

str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/pcbm28/';
pcbm28.freq = load([str '/freq.gout']); 
[pcbm28.dosx pcbm28.dosy] = m_dos(pcbm28.freq,5,1,1);

str='/home/jason/disorder/pcbm/pcbm_pdb/isolated/';
pcbm.freq = load([str '/freq.gout']); 
[pcbm.dosx pcbm.dosy] = m_dos(pcbm.freq,5,1,1);

clf
plot(...
    c60.new.dosx , c60.new.dosy,...
    pcbm28.dosx , pcbm28.dosy,...
    pcbm.dosx , pcbm.dosy...
    )
pause
%Di
pcbm.Di(1,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b0.01.gout');
pcbm.Di(2,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b0.1.gout');
pcbm.Di(3,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b1.gout');
pcbm.Di(4,1).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/highT50000/','Di_b10.gout');

pcbm.Di(1,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b0.01.gout');
pcbm.Di(2,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b0.1.gout');
pcbm.Di(3,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b1.gout');
pcbm.Di(4,2).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/300K/','Di_b10.gout');

pcbm.Di(1,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b0.01.gout');
pcbm.Di(2,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b0.1.gout');
pcbm.Di(3,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b1.gout');
pcbm.Di(4,3).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/100K/','Di_b10.gout');

pcbm.Di(1,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b0.01.gout');
pcbm.Di(2,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b0.1.gout');
pcbm.Di(3,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b1.gout');
pcbm.Di(4,4).Di =...
    m_gulp_af_si_readDi('/home/jason/disorder/pcbm/pcbm_pdb/p1d1_1a1b1c/10K/','Di_b10.gout');

clf
loglog(...
    pcbm.Di(1,1).Di(:,2),pcbm.Di(1,1).Di(:,3),'.',...
    pcbm.Di(2,1).Di(:,2),pcbm.Di(2,1).Di(:,3),'.',...
    pcbm.Di(3,1).Di(:,2),pcbm.Di(3,1).Di(:,3),'.',...
    pcbm.Di(4,1).Di(:,2),pcbm.Di(4,1).Di(:,3),'.'...
    )
pause
loglog(...
    pcbm.Di(1,2).Di(:,2),pcbm.Di(1,2).Di(:,3),'.',...
    pcbm.Di(2,2).Di(:,2),pcbm.Di(2,2).Di(:,3),'.',...
    pcbm.Di(3,2).Di(:,2),pcbm.Di(3,2).Di(:,3),'.',...
    pcbm.Di(4,2).Di(:,2),pcbm.Di(4,2).Di(:,3),'.'...
        )
pause
loglog(...
    pcbm.Di(1,3).Di(:,2),pcbm.Di(1,3).Di(:,3),'.',...
    pcbm.Di(2,3).Di(:,2),pcbm.Di(2,3).Di(:,3),'.',...
    pcbm.Di(3,3).Di(:,2),pcbm.Di(3,3).Di(:,3),'.',...
    pcbm.Di(4,3).Di(:,2),pcbm.Di(4,3).Di(:,3),'.'...
        )
pause
loglog(...
    pcbm.Di(1,4).Di(:,2),pcbm.Di(1,4).Di(:,3),'.',...
    pcbm.Di(2,4).Di(:,2),pcbm.Di(2,4).Di(:,3),'.',...
    pcbm.Di(3,4).Di(:,2),pcbm.Di(3,4).Di(:,3),'.',...
    pcbm.Di(4,4).Di(:,2),pcbm.Di(4,4).Di(:,3),'.'...
        )
pause



    
    
    
    