clear

x.old =...
    m_x0_read('/home/jason/disorder/pcbm/pcbm_pdb/p2m1+m-s_2a2b2c_650_400/p2m1+m-s_2a2b2c_650_400.matlab');
plot3(x.old.x,x.old.y,x.old.z,'.')
pause
olps = m_pcbm_olps;
NUM_OBJECT = 8*12-32;
obj(1).index = [];  obj(2).index = [];  obj(3).index = [];
obj(1).num = 60;    obj(2).num = 28;    obj(3).num = 12;

%order
% obj_choice=...
%     [1
%     2
%     1
%     2
%     1
%     2
%     1
%     2
%     3
%     3];

for iobject = 1:NUM_OBJECT
    iobject
    if iobject==1
        ilow =1;
    else
        ilow =1+max([max(obj(1).index) max(obj(2).index) max(obj(3).index)]);
    end
    clf
    hold on
    for iobj=1:3
        if iobject==1
        ihigh = 1 + obj(iobj).num;
        else
        ihigh =...
            max([max(obj(1).index) max(obj(2).index) max(obj(3).index)]) +...
            obj(iobj).num;
        end
        if ihigh <= length(x.old.x)
        subplot(3,1,iobj),...
        plot3(...
            x.old.x(ilow:ihigh),...
            x.old.y(ilow:ihigh),...
            x.old.z(ilow:ihigh),'.'...
            )
        pause
        end
    end
obj_choice = input('input choice (1) c60 (2) pcbm28 (3) solvent: ');
    if obj_choice == 1
        obj(1).index =[obj(1).index ilow:ilow+obj(1).num-1];
    elseif obj_choice == 2
        obj(2).index =[obj(2).index ilow:ilow+obj(2).num-1];
    elseif obj_choice == 3
        obj(3).index =[obj(3).index ilow:ilow+obj(3).num-1];
    end

end

%bypass
% for iobject = 1:NUM_OBJECT
%     
%     if iobject==1
%         ilow =1;
%     else
%         ilow =1+max([max(obj(1).index) max(obj(2).index) max(obj(3).index)]);
%     end
%     
%     if iobject==1
%         ihigh = 1 + obj(iobj).num;
%     else
%         ihigh =...
%             max([max(obj(1).index) max(obj(2).index) max(obj(3).index)]) +...
%             obj(iobj).num;
%     end
%     
%     if obj_choice == 1
%         obj(1).index =[obj(1).index ilow:ilow+obj(1).num-1];
%     elseif obj_choice == 2
%         obj(2).index =[obj(2).index ilow:ilow+obj(2).num-1];
%     elseif obj_choice == 3
%         obj(3).index =[obj(3).index ilow:ilow+obj(3).num-1];
%     end
% end

clf 
new.CF.x = x.old.x(obj(1).index);
new.CF.y = x.old.y(obj(1).index);
new.CF.z= x.old.z(obj(1).index);
new.CF.type = repmat(olps.mask.c60,1,32);
plot3(...
    new.CF.x,new.CF.y,new.CF.z,'.')
pause

new.pcbm.x = x.old.x(obj(2).index);
new.pcbm.y = x.old.y(obj(2).index);
new.pcbm.z = x.old.z(obj(2).index);
new.pcbm.type = repmat(olps.mask.pcbm28,1,32);
plot3(...
    new.pcbm.x,new.pcbm.y,new.pcbm.z,'.')
pause

new.solvent.x = x.old.x(obj(3).index);
new.solvent.y = x.old.y(obj(3).index);
new.solvent.z = x.old.z(obj(3).index);
new.solvent.type = [];%repmat(olps.mask.solvent.oDCB,1,0);
plot3(...
    new.solvent.x,new.solvent.y,new.solvent.z,'.')
pause


%--------------------------------------------------------------------------
%all
%--------------------------------------------------------------------------
clf
plot3(...
    new.CF.x,new.CF.y,new.CF.z,'x',...
    new.pcbm.x,new.pcbm.y,new.pcbm.z,'o',...
    new.solvent.x,new.solvent.y,new.solvent.z,'*'...
    )
pause

new.x =...
    [new.CF.x;new.pcbm.x;new.solvent.x];
new.y =...
    [new.CF.y;new.pcbm.y;new.solvent.y];
new.z =...
    [new.CF.z;new.pcbm.z;new.solvent.z];
new.type=...
    [new.CF.type new.pcbm.type new.solvent.type];

%output full
output = [length(new.type) length(new.type) 10 10 10];
new.id = 1:length(new.type);
x =...
    [ new.id' new.type' new.x new.y new.z ];
dlmwrite(...
    '/home/jason/disorder/pcbm/pcbm_pdb/p2m1+m-s_2a2b2c_650_400.data',...
    output ,'-append','delimiter',' ');
dlmwrite(...
    '/home/jason/disorder/pcbm/pcbm_pdb/p2m1+m-s_2a2b2c_650_400.data',...
    x ,'-append','delimiter',' ');

[I.CF J.CF] = find( new.type==olps.type.CF);
[I.CA1 J.CA1] = find( new.type==olps.type.CA1);
[I.CA2 J.CA2] = find( new.type==olps.type.CA2);
[I.C J.C] = find( new.type==olps.type.C);
[I.CT1 J.CT1] = find( new.type==olps.type.CT1);
[I.CT2 J.CT2] = find( new.type==olps.type.CT2);
[I.CT3 J.CT3] = find( new.type==olps.type.CT3);
[I.O J.O] = find( new.type==olps.type.O);
[I.OS J.OS] = find( new.type==olps.type.OS);
[I.HA J.HA] = find( new.type==olps.type.HA);
[I.HC J.HC] = find( new.type==olps.type.HC);
[I.Cl J.Cl] = find( new.type==olps.type.Cl);

clf
plot3(...
    new.x(J.CA1),new.y(J.CA1),new.z(J.CA1),'r+',... %new.x(J.CF),new.y(J.CF),new.z(J.CF),'.',...
    new.x(J.CA2),new.y(J.CA2),new.z(J.CA2),'go',...
    new.x(J.C),new.y(J.C),new.z(J.C),'b*',...
    new.x(J.CT1),new.y(J.CT1),new.z(J.CT1),'cx',...
    new.x(J.CT2),new.y(J.CT2),new.z(J.CT2),'ms',...
    new.x(J.CT3),new.y(J.CT3),new.z(J.CT3),'rd',...
    new.x(J.O),new.y(J.O),new.z(J.O),'kv',...
    new.x(J.OS),new.y(J.OS),new.z(J.OS),'^',...
    new.x(J.HA),new.y(J.HA),new.z(J.HA),'>',...
    new.x(J.HC),new.y(J.HC),new.z(J.HC),'<',...
    new.x(J.Cl),new.y(J.Cl),new.z(J.Cl),'.'...
    )


% hold on
% plot3(...
%     new.x(J.HC),new.y(J.HC),new.z(J.HC),'o','MarkerSize',30 ...
%     )
% 
% 
% %output full
% output = [length(new.type) length(new.type) 10 10 10];
% new.id = 1:length(new.type);
% x =...
%     [ new.id' new.type' new.x new.y new.z ];
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/p2m1_1a1b1c.data',...
%     output ,'-append','delimiter',' ');
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/p2m1_1a1b1c.data',...
%     x ,'-append','delimiter',' ');


% %output single
% clf
% plot3(...
%     new.x(1:60),new.y(1:60),new.z(1:60),'.',...
%     new.x(241:240+28),new.y(241:240+28),new.z(241:240+28),'.'...
%     )
% pause
% iso.id =...
%     [new.id(1:60)';new.id(241:240+28)'];
% iso.m =...
%     [new.type(1:60)';new.type(241:240+28)'];
% iso.z =...
%     [new.z(1:60);new.z(241:240+28)];
% iso.x =...
%     [new.x(1:60);new.x(241:240+28)];
% iso.y =...
%     [new.y(1:60);new.y(241:240+28)];
% iso.x = iso.x +50; iso.y = iso.y +50; iso.z = iso.z +50;
% 
% plot3(...
%     iso.x,iso.y,iso.z,'.')
% pause
% output = [length(iso.m) length(iso.m) 100 100 100];
% x =...
%     [ iso.id iso.m iso.x iso.y iso.z ];
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/p1d1_1a1b1c.isolated.data',...
%     output ,'-append','delimiter',' ');
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/p1d1_1a1b1c.isolated.data',...
%     x ,'-append','delimiter',' ');
% 
% %output c60
% clf
% plot3(...
%     new.x(1:60),new.y(1:60),new.z(1:60),'.',...
%     new.x(241:240+28),new.y(241:240+28),new.z(241:240+28),'.'...
%     )
% pause
% c60.id =...
%     [new.id(1:60)'];
% c60.m =...
%     [new.type(1:60)'];
% c60.z =...
%     [new.z(1:60)];
% c60.x =...
%     [new.x(1:60)];
% c60.y =...
%     [new.y(1:60)];
% c60.x = c60.x +50; c60.y = c60.y +50; c60.z = c60.z +50;
% 
% plot3(...
%     c60.x,c60.y,c60.z,'.')
% pause
% output = [length(c60.m) length(c60.m) 100 100 100];
% x =...
%     [ c60.id c60.m c60.x c60.y c60.z ];
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/c60.data',...
%     output ,'-append','delimiter',' ');
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/c60.data',...
%     x ,'-append','delimiter',' ');
% 
% %output c60
% clf
% plot3(...
%     new.x(1:60),new.y(1:60),new.z(1:60),'.',...
%     new.x(241:240+28),new.y(241:240+28),new.z(241:240+28),'.'...
%     )
% pause
% pcbm28.id =...
%     [new.id(241:240+28)'];
% pcbm28.m =...
%     [new.type(241:240+28)'];
% pcbm28.z =...
%     [new.z(241:240+28)];
% pcbm28.x =...
%     [new.x(241:240+28)];
% pcbm28.y =...
%     [new.y(241:240+28)];
% pcbm28.x = pcbm28.x +50; pcbm28.y = pcbm28.y +50; pcbm28.z = pcbm28.z +50;
% 
% plot3(...
%     pcbm28.x,pcbm28.y,pcbm28.z,'.')
% pause
% output = [length(pcbm28.m) length(pcbm28.m) 100 100 100];
% x =...
%     [ pcbm28.id pcbm28.m pcbm28.x pcbm28.y pcbm28.z ];
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/pcbm28.data',...
%     output ,'-append','delimiter',' ');
% dlmwrite(...
%     '/home/jason/disorder/pcbm/pcbm_pdb/isolated/pcbm28.data',...
%     x ,'-append','delimiter',' ');
 
  