

AF(1).AF = load('/home/jason/sam/8020/AF.mat');

AF(2).AF = load('/home/jason/sam/6040/AF.mat');

AF(3).AF = load('/home/jason/disorder2/lj/alloy/10K/0.5/10x/work/AF_Di(wi)_1.dat');

subplot(2,1,1),...
loglog(...
    AF(1).AF.freq,AF(1).AF.Di,'.',...
    AF(3).AF(:,1),AF(3).AF(:,2),'.',...
    AF(1).AF.freq,1E3*AF(1).AF.freq.^(-2),...
    AF(1).AF.freq,2*pi./AF(1).AF.freq...
    )
subplot(2,1,2),...
loglog(...
    AF(2).AF.freq,AF(2).AF.Di,'.',...
    AF(3).AF(:,1),AF(3).AF(:,2),'.',...
    AF(1).AF.freq,1E3*AF(1).AF.freq.^(-2),...
    AF(1).AF.freq,2*pi./AF(1).AF.freq...
    )