clear

gk = m_si_cond_alloy_gk_results;
vc = m_si_cond_alloy_nmd_vc_results;
ald = m_si_cond_alloy_ald_results;

% semilogy(gk.conc,gk.extrap,'.',...
% ald.conc,ald.extrap,'.',...
% vc.conc,vc.extrap,'.')

m_si_gk_vc_ald_cond_compare_plot_createfigure(...
    gk.conc,...
    [gk.extrap ...
    ald.extrap ...
    vc.extrap]...
    )
