clear
ipt = 1;
freq_cutoff = 0;
dph_scaling = 0.5;
constant = m_constant; si = m_si;
vcnmd(ipt).nmd.alat = 5.43E-10;
vcnmd(ipt).nmd.Nx = 20;

sys_size = '20x';
%--------------------------------------------------------------------------
%load
%-------------------------------------------------------------------------- 
ipt = 1;
str_ald = ['/home/jason/disorder2/si/ald/conv/' sys_size '/Data_fullBZ.xls'];
str_alloy = ['/home/jason/disorder2/si/alloy/0.5/' sys_size '/'];
str_nmd = ['/home/jason/disorder2/si/alloy/0.5/' sys_size '/'];
nmd=load(strcat(str_nmd,'nmd.mat'));
ald = m_joe_read_data_si(str_ald);
alloy(ipt).alloy = load(strcat(str_alloy,'ALLOY.mat'));
vcald(ipt).sedald =...
    m_joe_ald2nmd_si(...
    nmd.NUM_KPTS, nmd.kptmodelist , nmd.NUM_MODES , ald );
vcald(ipt).sedald.cond =...
    m_ald_cond(...
    (1./( (1./(vcald(ipt).sedald.life/sqrt(nmd.x0.vm))) +...
    (1./alloy(ipt).alloy.life(:,1)) )),...
    vcald(ipt).sedald.vel(:,1)/sqrt(nmd.x0.vm),...
    nmd.x0.VOLUME*constant.ang2m^3)

loglog(...
    vcald(ipt).sedald.freq,...
    (1./( (1./(vcald(ipt).sedald.life/sqrt(nmd.x0.vm))) +...
    (1./alloy(ipt).alloy.life(:,1)) )),'.',...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.life,'.'...
    )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%ald
%--------------------------------------------------------------------------
%adjust for D_ph
vcald(ipt).sedald.Dphi =...
    1./(1./alloy(ipt).alloy.life + 1./vcald(ipt).sedald.life).*...
    (vcald(ipt).sedald.vel(:,1).^2);
vcald(ipt).sedald.Dphf = vcald(ipt).sedald.Dphi;
[Idiff Jdiff] =...
    find(...
    vcald(ipt).sedald.freq > freq_cutoff & ...
    vcald(ipt).sedald.Dphi < ...
    (1/3)*si.sound_used/sqrt(nmd.x0.vm)*vcnmd(ipt).nmd.alat*dph_scaling ...
    );
%swap values
vcald(ipt).sedald.Dphf(Idiff) = ...
    (1/3)*si.sound_used/sqrt(nmd.x0.vm)*vcnmd(ipt).nmd.alat*dph_scaling;
old_cond =...
    (constant.kb/(nmd.x0.VOLUME*constant.ang2m^3))*...
    sum(...
    vcald(ipt).sedald.Dphi...
    )
new_cond =...
    (constant.kb/(nmd.x0.VOLUME*constant.ang2m^3))*...
    sum(...
    vcald(ipt).sedald.Dphf...
    )
%--------------------------------------------------------------------------
loglog(...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.Dphi,'.',...
    vcald(ipt).sedald.freq,...
    vcald(ipt).sedald.Dphf,'.'...
    )
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

% loglog(...
%     vcnmd(ipt).sed.freq,...
%     vcnmd(ipt).sed.Dphi,'.',...
%     vcnmd(ipt).sed.freq,...
%     vcnmd(ipt).sed.Dphf,'.',...
%     vcald(ipt).sedald.freq,...
%     vcald(ipt).sedald.Dphi,'.',...
%     vcald(ipt).sedald.freq,...
%     vcald(ipt).sedald.Dphf,'.'...
%     )


