function m_si_cond_alloy_tau_intk_createfigure(X1, Y1, X2, YMatrix1, X3, YMatrix2, X4, YMatrix3, X5, YMatrix4, X6, Y2)
%CREATEFIGURE(X1,Y1,X2,YMATRIX1,X3,YMATRIX2,X4,YMATRIX3,X5,YMATRIX4,X6,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  X4:  vector of x data
%  YMATRIX3:  matrix of y data
%  X5:  vector of x data
%  YMATRIX4:  matrix of y data
%  X6:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 17-Oct-2012 20:31:20

% Create figure
figure1 = figure('XVisual',...
    '0xaa (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'Units','inches',...
    'Position',[0.705333333333334 2.97777777777778 3.41 2.3]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2000010000000 199990000000000]);
box(axes1,'on');
hold(axes1,'all');

% Create loglog
loglog(X1,Y1,'Parent',axes1,'Marker','.','LineStyle','none',...
    'DisplayName','ald');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X2,YMatrix1,'Parent',axes1,'LineStyle','none');
set(loglog1(1),'Marker','+','DisplayName','ald+taud c=0.001');
set(loglog1(2),'Marker','.','Color',[0 0.498039215686275 0],...
    'DisplayName','taud');

% Create multiple lines using matrix input to loglog
loglog2 = loglog(X3,YMatrix2,'Parent',axes1,'LineStyle','none',...
    'Color',[1 0 0]);
set(loglog2(1),'Marker','x','DisplayName','ald+taud c=0.5');
set(loglog2(2),'Marker','.','DisplayName','taud');

% Create multiple lines using matrix input to loglog
loglog3 = loglog(X4,YMatrix3,'Parent',axes1);
set(loglog3(1),'DisplayName','$\omega^{-2}$');
set(loglog3(2),'DisplayName','$\omega^{-4}$');

% Create ylabel
ylabel({'$\tau$ (s)'});

% Create axes
axes2 = axes('Parent',figure1,'XScale','log','XMinorTick','on',...
    'Units','inches',...
    'Position',[0.705333333333334 0.609888888888889 3.41 2.36788888888889]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[2000000000000 200000000000000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 1.1]);
box(axes2,'on');
hold(axes2,'all');

% Create multiple lines using matrix input to semilogx
semilogx1 = semilogx(X5,YMatrix4,'Parent',axes2);
set(semilogx1(1),'DisplayName','ald');
set(semilogx1(2),'DisplayName','ald+taud c=0.001');

% Create semilogx
semilogx(X6,Y2,'Parent',axes2,'DisplayName','ald+taud c=0.5');

% Create xlabel
xlabel({'$\omega (rads/s)'});

% Create ylabel
ylabel({'int $ k(\omega)%'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','inches',...
    'Position',[0.783246649543693 2.26414930555554 1.67222222222222 1.39722222222222]);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'Units','inches',...
    'Position',[2.36405513992796 0.722222222222219 1.67222222222222 0.569444444444444]);

