function m_si_gk_vc_ald_cond_compare_plot_createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Oct-2012 23:50:08

% Create figure
figure1 = figure('XVisual',...
    '0xa5 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'Units','inches',...
    'Position',[0.832 0.589111111111111 3.5 3.5]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1,'Parent',axes1,'MarkerSize',12,...
    'LineWidth',2,...
    'LineStyle','none');
set(semilogy1(1),'Marker','o','DisplayName','GK');
set(semilogy1(2),'Marker','diamond','DisplayName','ALD');
set(semilogy1(3),'Marker','square','DisplayName','NMD');

% Create xlabel
xlabel({'c'},'Interpreter','latex','FontSize',12);

% Create ylabel
ylabel({'$k$ (W/m-K)'},'Interpreter','latex','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[3.22638888888889 3.21666666666667 0.983333333333333 0.802777777777778]);

