cond = m_si_cond_alloy;

% subplot(2,1,1),...
    semilogy(...
    cond.garg(:,1),...
    cond.garg(:,2),...
    cond.schelling(:,1),...
    cond.schelling(:,2),...
    cond.landry(:,1),...
    cond.landry(:,2),...
    cond.conc,...
    cond.cond',...
    [0.05 0.15 0.5],...
    cond.cond_extrap(:)'...
    )
% subplot(2,1,2),...
%     semilogy(...
%     cond.garg(:,1),...
%     cond.garg(:,2)/max(cond.garg(:,2)),...
%     cond.schelling(:,1),...
%     cond.schelling(:,2)/max(cond.schelling(:,2)),...
%     cond.conc,...
%     cond.cond'/max(cond.cond')...
%     )