function galli = m_si_amor_galli_k_tf
galli.k =...
    [1.8
    2
    2
    1.8
    2
    1
    1.5
    4
    4
    4.8
    4
    ];
    
galli.tf = ...
    [0.1
    0.13
    0.2
    1.27
    0.52
    0.4
    0.5
    1.2
    1.6
    3.6
    80
    ];

galli.tf = galli.tf*1000*1E-9;

galli.moon.k=[...
    1.4
    1.5
    2.25...
    ];
galli.moon.tf=[...
    50*1E-9
    97*1E-9
    200*1E-9...
    ];

semilogx(...
    galli.tf(1), galli.k(1),'.',...
    galli.tf(2), galli.k(2),'.',...
    galli.tf(3), galli.k(3),'.',...
    galli.tf(4), galli.k(4),'.',...
    galli.tf(5), galli.k(5),'.',...
    galli.tf(6), galli.k(6),'.',...
    galli.tf(7), galli.k(7),'.',...
    galli.tf(8), galli.k(8),'.',...
    galli.tf(9), galli.k(9),'.',...
    galli.tf(10), galli.k(10),'.',...
    galli.tf(11), galli.k(11),'.'...
    )
xlabel('tf (nm)')
ylabel('k(tf) (W/m-K)')

legend(...
    'Wada and Kamijoh (1996)',...
    'Zink, Pietri, Hellman (2006)',...
    'Yang, Cahill, et al (2010)',...
    'Zink, Pietri, Hellman (2006)',...
    'Cahill, Katiyar, Abelson (1994)',...
    'Kuo, Li, Schmid (1992)',...
    'Moon, Hatano, et al (2002)',...
    'Wieczorek, Goldsmid, Paul (1989)',...
    'Yang, Cahill, et al (2010)',...
    'Wieczorek, Goldsmid, Paul (1989)',...
    'Liu, Feldman, et al (2009)')



% si.malen.k = ...
%     [
%     1.7
%     1.0
%     0.9
%     ];
%     
% si.malen.tf = ...
%     [
%     10^(-0.2)
%     10^(-1)
%     10^(-1.5)
%     ];
% 
% semilogx(...
%     si.malen.tf,si.malen.k,'.',...
%     si.galli.tf, si.galli.k,'.','MarkerSize',15)
% xlabel('tf (\mu m)')
% ylabel('k(tf) W/m-K')
% 
% axis(...
%     [...
%     min([si.galli.tf;si.malen.tf]) ...
%     max([si.galli.tf;si.malen.tf]) ...
%     0 ...
%     max([si.galli.k;si.malen.k])...
%     ]...
%     );
% 
% legend('malen','galli')

end