clear
constant = m_constant;
size_big = 100000;

ald = m_si_cond_alloy_ald_results
gk = m_si_cond_alloy_gk_results

semilogy(...
    gk.conc, gk.extrap , '.',...
    ald.conc, ald.extrap , '.',...
    ald.conc, ald.extrap_diff , '.',...
    ald.conc, ald.high_scatter , '.'...
    )

