
sio2.rdf_me =...
    load(...
    '/home/jason/disorder2/sio2/alan/576a/tile/anneal/emin/tmp.rdf.matlab');
sio2.rdf_me_all =...
    load(...
    '/home/jason/disorder2/sio2/alan/576a/tile/anneal/emin/rdf_nve/tmp_all.rdf.matlab');
sio2.rdf_me_all_2 =...
    load(...
    '/home/jason/disorder2/sio2/alan/576a/tile/anneal/emin/rdf_nve/rdf_nve.txt');
sio2.rdf(1).rdf =...
    load(...
    '/home/jason/Dropbox/ntpl-paper/disorder/used/lorch_neutron_1969_fig9.txt');

clf
%hold on
[I,J] = sort(sio2.rdf(1).rdf(:,1));
[I2,J2] = sort(sio2.rdf_me_all_2(:,1));
subplot(2,1,1),...
plot(...
    sio2.rdf(1).rdf(J(6:end),1),...
    sio2.rdf(1).rdf(J(6:end),2)./(sio2.rdf(1).rdf(J(6:end),1).^2)+0.2,...
    sio2.rdf_me_all_2(J2,1),smooth(sio2.rdf_me_all_2(J2,2),1)...
    )

% plot(...
%     sio2.rdf_me(:,2),sio2.rdf_me(:,3),'.',...
%     sio2.rdf_me(:,2),sio2.rdf_me(:,5),'.',...
%     sio2.rdf_me(:,2),sio2.rdf_me(:,7),'.'...
%     )
% plot(...
%     sio2.rdf_me_all(:,2),smooth(sio2.rdf_me_all(:,3),3)...
%     )
% pause
% clf

si.rdf(1).rdf =...
    load(...
    '/home/jason/Dropbox/ntpl-paper/disorder/used/barkema_high-quality_2000_fig4_expt.txt');
si.rdf(2).rdf =...
    load(...
    '/home/jason/Dropbox/ntpl-paper/disorder/used/barkema_high-quality_2000_fig4_model.txt');
si.rdf_me =...
    load(...
    '/home/jason/disorder2/si/amor/normand/perf4096/anneal_1100K/emin/rdf_nve/tmp_all.rdf.matlab');

subplot(2,1,2),...
plot(...
    si.rdf_me(:,2),si.rdf_me(:,3),...
    si.rdf(1).rdf(:,1),si.rdf(1).rdf(:,2)./(si.rdf(1).rdf(:,1).^2)*1.6...
    )



