
SED =...
    load('/home/jason/disorder2/si/amor/normand/perfect2/anneal_900K/SEDfit.mat')

loglog(...
    SED.HLDfreq,SED.life,'.',...
    SED.HLDfreq,1E12*2*pi./SED.HLDfreq,...
    SED.HLDfreq,1E27*(SED.HLDfreq.^(-2))...
    )




