clear
constant = m_constant;
size_big = 100000;

ald = m_si_cond_alloy_ald_results

plot(...
    1./[ald.size;size_big] , 1./[ald.cond(:,2);8] , '.',...
    1./[ald.size;size_big] , 1./[ald.cond(:,4);3.4] , '.'...
    )

[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 1 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 1 : size(ald.size,1),2)]...
    );
R
1./p(2)
[p R] = m_cond_extrap(...
    [ald.size( size(ald.size,1) - 1 : size(ald.size,1))  ],...
    [ald.cond( size(ald.size,1) - 1 : size(ald.size,1),4)]...
    );
R
1./p(2)
