
function SED = nmd_convert_data(NMD,SED)

%re-sort eigvec and transpose freq
for ikpt = 1:NMD.NUM_KPTS
    SED.freq(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
        =...
        SED.redkpt.freq(ikpt,:)';
    SED.sedfreq(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
        =...
        SED.redkpt.sedfreq(:,ikpt);
    SED.life(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
        =...
        SED.redkpt.life(:,ikpt)';
    SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
        =...
        SED.redkpt.groupvel(:,1,ikpt);
    SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,2)...
        =...
        SED.redkpt.groupvel(:,2,ikpt);
    SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,3)...
        =...
        SED.redkpt.groupvel(:,3,ikpt);
    SED.kpt( (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1:3) = ...
        repmat(NMD.kptmaster(ikpt,:),NMD.NUM_MODES,1);
    
    SED.MFP(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1)...
        =...
        SED.redkpt.life(:,ikpt).*...
        sqrt(...
        SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,1).^2 +...
        SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,2).^2 +...
        SED.groupvel(...
        (ikpt-1)*NMD.NUM_MODES+1:(ikpt)*NMD.NUM_MODES,3).^2 )    ;
end