
str.main = '/home/jason/lammps/LJ/alloy/10K/0.0/8x/NMD';

AF.eigvec =...
    load(strcat(str.main,'/AF_eigvec_1.dat'));
AF.x0 =...
    load(strcat(str.main,'/x0_0_1.data'));
AF.Di =...
    load(strcat(str.main,'/Di(wi)_1.dat'));
AF.freq =...
    load(strcat(str.main,'/AF_freq_1.dat'));



AF.NUM_ATOMS = AF.x0(1,1); AF.NUM_ATOMS_UCELL = AF.x0(1,2); 
AF.Lx = AF.x0(1,3); AF.Ly = AF.x0(1,4); AF.Lz = AF.x0(1,5);
AF.VOLUME = AF.Lx*AF.Ly*AF.Lz; AF.dr = (AF.VOLUME/AF.NUM_ATOMS)^(1/3);

AF.x0 = AF.x0(2:size(AF.x0,1),:);

for imode = 1:size(AF.eigvec,1)


AF.part(imode) =...
    1/sum(...
    (...
    AF.eigvec(1:3:size(AF.eigvec,1),imode).^2 ...
    +...
    AF.eigvec(2:3:size(AF.eigvec,1),imode).^2 ...
    +...
    AF.eigvec(3:3:size(AF.eigvec,1),imode).^2 ...
    ).^2 ...
    , 1);   
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------

end

[AF.DOSY AF.DOSX ]= hist(AF.freq,ceil(AF.NUM_ATOMS/50));

plot(...
    AF.freq     ,    AF.part/AF.NUM_ATOMS,'.',...
    ...
    AF.DOSX     ,    10*AF.DOSY/sum(AF.DOSY),...
    ...
    AF.freq     ,    AF.Di(:,2)/max(AF.Di(:,2)) ,'.'        )


