function LJAr_DOS_createfigure(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 25-Feb-2012 15:03:57

% Create figure
figure1 = figure('XVisual',...
    '0x94 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'Units','inches','TickLength',[0.02 0.04],...
    'Position',[0.755555555555556 0.561805555555555 3.58333333333333 3.54330709],...
    'LineWidth',2,...
    'FontSize',15,...
    'FontName','Arial');
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 35]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'DisplayName','crystal');

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,'DisplayName','amorphous');

% Create xlabel
xlabel({'$\omega_{i}$ (LJ)'},'Interpreter','latex','FontSize',15,...
    'FontName','Arial');

% Create ylabel
ylabel({'DOS (arb units)'},'Interpreter','latex','FontSize',15,...
    'FontName','Arial');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','EdgeColor',[1 1 1],'YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'Units','inches',...
    'Position',[0.897569444444464 3.34791666666669 0.869097222222207 0.640277777777778],...
    'FontSize',12,...
    'FontName','Bitstream Charter');

