
%compare all systems biggest size

af(1).broaden = [1 0.5 2 5];

%af
str.af = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/work';
af(1).di=load(strcat(str.af,'/AF_Di(wi)_1.dat'));
str.af = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/work/broaden0.5';
af(2).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/work/';
af(3).di=load(strcat(str.af,'/AF_Di(wi)_1.dat'));
str.af = '/home/jason/disorder2/lj/alloy/10K/0.5/10x/work/broaden5.0';
af(4).di=load(strcat(str.af,'/Di(wi)_1.dat'));


str.af = '/home/jason/disorder2/lj/amor/10x/work';
af(5).di=load(strcat(str.af,'/AF_Di(wi)_1.dat'));

loglog(...
    af(1).di(:,1),af(1).di(:,2),'.',...
    af(2).di(:,1),af(2).di(:,2),'.',...
    af(3).di(:,1),af(3).di(:,2),'.',...
    af(4).di(:,1),af(4).di(:,2),'.'...
    )

af(1).wijavg =...
    mean(...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1)...
    );
af(5).wijavg =...
    mean(...
    af(5).di(2:length(af(5).di),1) - af(5).di(1:length(af(5).di)-1,1)...
    );

subplot(2,1,1),...
semilogy(...
    af(1).di(1:length(af(1).di)-1,1),...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1),'g.'...
    )
line([0 max(af(1).di(:,1))], [af(1).wijavg af(1).wijavg] )
subplot(2,1,2),...
semilogy(...
    af(5).di(1:length(af(5).di)-1,1),...
    af(5).di(2:length(af(5).di),1) - af(5).di(1:length(af(5).di)-1,1),'g.'...
    )
line([0 max(af(5).di(:,1))], [af(5).wijavg af(5).wijavg] )


pause


af(1).kappa =...
    [...
    trapz(af(1).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(2).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(3).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(4).di(:,2))/trapz(af(1).di(:,2))...
    ];
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
%af
str.af = '/home/jason/disorder/lj/alloy/10K/0.15/10x/work';
af(1).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.15/10x/work/broaden0.5';
af(2).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.15/10x/work/';
af(3).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.15/10x/work/broaden5.0';
af(4).di=load(strcat(str.af,'/Di(wi)_1.dat'));

loglog(...
    af(1).di(:,1),af(1).di(:,2),'.',...
    af(2).di(:,1),af(2).di(:,2),'.',...
    af(3).di(:,1),af(3).di(:,2),'.',...
    af(4).di(:,1),af(4).di(:,2),'.'...
    )

af(2).wijavg =...
    mean(...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1)...
    );

semilogy(...
    af(1).di(1:length(af(1).di)-1,1),...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1),'g.'...
    )
line([0 max(af(1).di(:,1))], [af(2).wijavg af(2).wijavg] )

af(2).kappa =...
    [...
    trapz(af(1).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(2).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(3).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(4).di(:,2))/trapz(af(1).di(:,2))...
    ];
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
%af
str.af = '/home/jason/disorder/lj/alloy/10K/0.5/10x/work';
af(1).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.5/10x/work/broaden0.5';
af(2).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.5/10x/work/';
af(3).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/alloy/10K/0.5/10x/work/broaden5.0';
af(4).di=load(strcat(str.af,'/Di(wi)_1.dat'));

loglog(...
    af(1).di(:,1),af(1).di(:,2),'.',...
    af(2).di(:,1),af(2).di(:,2),'.',...
    af(3).di(:,1),af(3).di(:,2),'.',...
    af(4).di(:,1),af(4).di(:,2),'.'...
    )

af(3).wijavg =...
    mean(...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1)...
    );

af(3).wijavg

semilogy(...
    af(1).di(1:length(af(1).di)-1,1),...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1),'g.'...
    )
line([0 max(af(1).di(:,1))], [af(3).wijavg af(3).wijavg] )

af(3).kappa =...
    [...
    trapz(af(1).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(2).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(3).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(4).di(:,2))/trapz(af(1).di(:,2))...
    ];
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
%af
str.af = '/home/jason/disorder/lj/amor/10x/work/broaden1';
af(1).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/amor/10x/work/broaden0.5';
af(2).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/amor/10x/work/broaden2';
af(3).di=load(strcat(str.af,'/Di(wi)_1.dat'));
str.af = '/home/jason/disorder/lj/amor/10x/work/broaden5.0';
af(4).di=load(strcat(str.af,'/Di(wi)_1.dat'));

loglog(...
    af(1).di(:,1),af(1).di(:,2),'.',...
    af(2).di(:,1),af(2).di(:,2),'.',...
    af(3).di(:,1),af(3).di(:,2),'.',...
    af(4).di(:,1),af(4).di(:,2),'.'...
    )

af(4).wijavg =...
    mean(...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1)...
    );

af(4).wijavg

semilogy(...
    af(1).di(1:length(af(1).di)-1,1),...
    af(1).di(2:length(af(1).di),1) - af(1).di(1:length(af(1).di)-1,1),'g.'...
    )
line([0 max(af(1).di(:,1))], [af(4).wijavg af(4).wijavg] )

af(4).kappa =...
    [...
    trapz(af(1).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(2).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(3).di(:,2))/trapz(af(1).di(:,2))...
    trapz(af(4).di(:,2))/trapz(af(1).di(:,2))...
    ];

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%plot broaden vs kappa
plot(...
    af(1).broaden,af(1).kappa,'b.',...
    af(1).broaden,af(2).kappa,'go',...
    af(1).broaden,af(3).kappa,'r+',...
    af(1).broaden,af(4).kappa,'mx','MarkerSize',20 )



% plot(af(1).di(:,1),cumtrapz(af(1).di(:,2))/max(cumtrapz(af(1).di(:,2))),...
% af(2).di(:,1),cumtrapz(af(2).di(:,2))/max(cumtrapz(af(2).di(:,2))))
% plot(af(1).di(:,1),cumtrapz(af(1).di(:,2)),...
% af(2).di(:,1),cumtrapz(af(2).di(:,2)))



