
str.AF = '/home/jason/lammps/LJ/alloy/10K/0.5/12x/NMD/';
AF = load(strcat(str.AF,'AF_DSF.mat'));
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.5/12x/NMD/1/';
NMD=load(strcat(str.NMD,'NMDdata.mat'));
SED=load(strcat(str.NMD,'SEDdata.mat'));
%convert freq to cols
SED = nmd_convert_data(NMD,SED);
%convert to LJ units
SED.freq = SED.freq*NMD.LJ.tau;


for ikpt=1:size(squeeze(sum(SED.irrkpt.sedavg,2)),2)
    SED.irrkpt.sednorm(:,ikpt) =...
        squeeze(sum(SED.irrkpt.sedavg(:,:,ikpt),2));
    SED.irrkpt.sednorm(:,ikpt) =...
        SED.irrkpt.sednorm(:,ikpt)/max(SED.irrkpt.sednorm(:,ikpt));
end
    
mesh(...
    AF.kpt_norm,...
    SED.omega,...
    SED.irrkpt.sednorm...
    )

camup([0 1 0]);

ZMIN = 0.01;

axis(...
    [...
    min(AF.kpt_norm)...
    max(AF.kpt_norm)...
    min(AF.freq_unique)...
    max(AF.freq_unique)...
    ZMIN...
    max(max(SED.irrkpt.sednorm))])