
clear

str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.15/12x/NMD/1/';
NMD=load(strcat(str.NMD,'NMDdata.mat'));
SED=load(strcat(str.NMD,'SEDdata.mat'));
%convert freq to cols
SED = nmd_convert_data(NMD,SED);


%convert wavevector to wavelength
SED.wavelength(:,1) = (NMD.Nx./SED.kpt(:,1))*NMD.alat;
SED.wavelength(:,2) = (NMD.Nx./SED.kpt(:,2))*NMD.alat;
SED.wavelength(:,3) = (NMD.Nx./SED.kpt(:,3))*NMD.alat;

%calculate MFP
% SED.MFP(:,1) =...
%     (SED.life/NMD.LJ.tau).*...
%     sqrt(...
%     (SED.groupvel(:,1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 );

SED.MFP(:,1) =...
    (SED.life/NMD.LJ.tau).*...
    ((SED.groupvel(:,1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ) ;
SED.MFP(:,2) =...
    (SED.life/NMD.LJ.tau).*...
    ((SED.groupvel(:,2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ) ;
SED.MFP(:,3) =...
    (SED.life/NMD.LJ.tau).*...
    ((SED.groupvel(:,3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ) ;

%sort MFP in ascending order
[SED.Imfp SED.Jmfp] = sort(SED.MFP(:,1));

%find spectral cond
SED.cond(:,1) =...
    (NMD.constant.kb/NMD.VOLUME)*...
    SED.life(:,1).*SED.groupvel(:,1).^2 ;
SED.cond(:,2) =...
    (NMD.constant.kb/NMD.VOLUME)*...
    SED.life(:,1).*SED.groupvel(:,2).^2 ;
SED.cond(:,3) =...
    (NMD.constant.kb/NMD.VOLUME)*...
    SED.life(:,1).*SED.groupvel(:,3).^2 ;

%PLOT freq spectrum

SED.NUM_FREQ = 30;
SED.dFREQ = max(SED.freq*NMD.LJ.tau)/SED.NUM_FREQ;
SED.FREQ_RANGE = 0:SED.dFREQ:max(SED.freq*NMD.LJ.tau);
for ifreq = 1:size(SED.FREQ_RANGE,2)
    [I J] =... 
        find(...
        SED.freq*NMD.LJ.tau<=SED.FREQ_RANGE(ifreq)+SED.dFREQ &...
        SED.freq*NMD.LJ.tau>SED.FREQ_RANGE(ifreq)...
        );
    SED.cond_freq(ifreq) = sum(SED.cond(I));
end
semilogx(SED.FREQ_RANGE,SED.cond_freq,'.')
xlabel('w'); ylabel('k(w)');
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------


%PLOT MFP spectrum

SED.NUM_MFP = 50;
SED.dMFP = max(SED.MFP(:,1))/SED.NUM_MFP;
SED.MFP_RANGE = 0:SED.dMFP:max(SED.MFP(:,1));

for imfp = 1:size(SED.MFP_RANGE,2)
    [I J] =... 
        find(...
        SED.MFP(:,1)<=SED.MFP_RANGE(imfp)+SED.dMFP &...
        SED.MFP(:,1)>SED.MFP_RANGE(imfp)...
        );
    
    SED.cond_mfp(imfp) = sum(SED.cond(I));
end
semilogx(SED.MFP_RANGE,SED.cond_mfp)
hold on
for imfp = 1:size(SED.MFP_RANGE,2)
    [I J] =... 
        find(...
        SED.MFP(SED.Jmfp,1)<=SED.MFP_RANGE(imfp)+SED.dMFP &...
        SED.MFP(SED.Jmfp,1)>SED.MFP_RANGE(imfp)...
        );
    
    SED.cond_mfp_wave(imfp) = sum(SED.cond(I));
end
loglog(SED.MFP_RANGE,SED.cond_mfp_wave)
xlabel('MFP'); ylabel('k(MFP)');
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

clf

% loglog(...
%     SED.freq*NMD.LJ.tau,...
%     (SED.life/NMD.LJ.tau).*...
%     sqrt(...
%     (SED.groupvel(:,1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ...
%     ),'.')
% 
% 
% loglog(...
%     SED.freq*NMD.LJ.tau,...
%     (SED.life/NMD.LJ.tau).*...
%     sqrt(...
%     (SED.groupvel(:,1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(:,3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ...
%     ),...
%     '.',...
%     SED.freq((1:12:size(SED.groupvel,1)))*NMD.LJ.tau,...
%     (SED.life((1:12:size(SED.groupvel,1)))/NMD.LJ.tau).*...
%     sqrt(...
%     (SED.groupvel(1:12:size(SED.groupvel,1),1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(1:12:size(SED.groupvel,1),2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
%     (SED.groupvel(1:12:size(SED.groupvel,1),3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ...
%     )...
%     ,'.')

%MFP vs freq vs wavelength

loglog(...
    abs(...
    SED.wavelength...
    ),...
    abs(...
    SED.wavelength...
    ),...
    abs(...
    SED.wavelength...
    ),...
    (SED.life/NMD.LJ.tau).*...
    sqrt(...
    (SED.groupvel(:,1) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
    (SED.groupvel(:,2) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 +...
    (SED.groupvel(:,3) .* NMD.LJ.tau./NMD.LJ.sigma ).^2 ...
    ),...
    '.')
xlabel('wavelength'); ylabel('k(MFP)');
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%Find MFP > wavelength
[Iwave Jwave] =...
    find(...
    SED.MFP(:,1)...
    >...
    abs(SED.wavelength(:,1))...
    );
  
loglog(...
    SED.freq(Iwave)/NMD.LJ.tau,...
    SED.life(Iwave,:),'.')
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

sum(SED.cond(Iwave))

SED.conductivityx

cond_sed =...
    [...
    3.3812...
    0.9522...
    0.4254...
    0.3422...
    ];

cond_wave =...
    [...
    3.3285...
    0.8807...
    0.3508...
    0.2934...
    ];

plot(cond_sed,cond_wave./cond_sed,'.')
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
