
str.AF = '/home/jason/lammps/LJ/alloy/10K/0.05/8x/NMD_AF/';
AF(1).AF = load(strcat(str.AF,'AF_DSF.mat'));

str.AF = '/home/jason/lammps/LJ/alloy/10K/0.15/8x/NMD_AF/';
AF(2).AF = load(strcat(str.AF,'AF_DSF.mat'));

str.AF = '/home/jason/lammps/LJ/alloy/10K/0.5/8x/NMD_AF/';
AF(3).AF = load(strcat(str.AF,'AF_DSF.mat'));

%amorphous
str.AF = '/home/jason/lammps/LJ/amorphous/8x/AF/';
AF(4).AF = load(strcat(str.AF,'AF_DSF.mat'));

pause



SUBPLOT(3,1,1),...
plot(...
AF(1).AF.freq,AF(1).AF.DSF(:,1)/max(AF(1).AF.DSF(:,1)),'.',...
AF(1).AF.freq,AF(1).AF.DSF(:,11)/max(AF(1).AF.DSF(:,11)),'.',...
AF(1).AF.freq,AF(1).AF.DSF(:,21)/max(AF(1).AF.DSF(:,21)),'.',...
AF(1).AF.freq,AF(1).AF.DSF(:,51)/max(AF(1).AF.DSF(:,51)),'.' )

SUBPLOT(3,1,2),...
plot(...
AF(3).AF.freq,AF(3).AF.DSF(:,1)/max(AF(3).AF.DSF(:,1)),'.',...
AF(3).AF.freq,AF(3).AF.DSF(:,11)/max(AF(3).AF.DSF(:,11)),'.',...
AF(3).AF.freq,AF(3).AF.DSF(:,31)/max(AF(3).AF.DSF(:,31)),'.',...
AF(3).AF.freq,AF(3).AF.DSF(:,51)/max(AF(3).AF.DSF(:,51)),'.')

SUBPLOT(3,1,3),...
plot(...
AF(4).AF.freq,AF(4).AF.DSF(:,1)/max(AF(4).AF.DSF(:,1)),'.',...
AF(4).AF.freq,AF(4).AF.DSF(:,11)/max(AF(4).AF.DSF(:,11)),'.',...
AF(4).AF.freq,AF(4).AF.DSF(:,31)/max(AF(4).AF.DSF(:,31)),'.',...
AF(4).AF.freq,AF(4).AF.DSF(:,51)/max(AF(4).AF.DSF(:,51)),'.')


