clear

%--------------------------------------------------------------------------
iseed = 1;
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
LD.alloy_conc = 0.0;
%--------------------------------------------------------------------------

%MASSES
%--------------------------------------------------------------------------
LD.mass(1) = 1.0; LD.mass(2) = 3.0;
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
[tmp,str.main] = system('pwd'); str.main_write = str.main;
str.main = strcat('/home/jason/lammps/LJ/amorphous/4x/AF/');

AF.AF_amor = load(strcat(str.main,'AF_groupvel_1.mat'));


str.main = strcat('/home/jason/lammps/LJ/alloy/10K/0.15/8x/NMD/');

AF.AF_0 = load(strcat(str.main,'AF_groupvel_1.mat'));

NMD.NMD_0 = load(strcat(str.main,'/1/NMDdata.mat'));
SED.SED_0 = load(strcat(str.main,'/1/SEDdata.mat'));

SED.SED_0 = nmd_convert_data(NMD.NMD_0,SED.SED_0);

[SED.SED_0.Ifreq SED.SED_0.Jfreq] = sort(SED.SED_0.freq);

[AF.AF_0.Ifreq AF.AF_0.Jfreq] = sort(AF.AF_0.freq);

[AF.AF_amor.Ifreq AF.AF_amor.Jfreq] = sort(AF.AF_amor.freq);

%plot AF vs NMD
plot(...
    SED.SED_0.freq(SED.SED_0.Jfreq)*NMD.NMD_0.LJ.tau,...
    NMD.NMD_0.LJ.tau/NMD.NMD_0.LJ.sigma*sqrt(...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,1).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,2).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,3).^2 ),...
    '.',...
    AF.AF_0.freq(AF.AF_amor.Jfreq),...
    sqrt(...
    AF.AF_0.groupvel(AF.AF_amor.Jfreq,1).^2 + ...
    AF.AF_0.groupvel(AF.AF_amor.Jfreq,2).^2 + ...
    AF.AF_0.groupvel(AF.AF_amor.Jfreq,3).^2 ),...
    '.'...
    )
%plot difference
plot(...
    SED.SED_0.freq(SED.SED_0.Jfreq)*(NMD.NMD_0.LJ.tau)...
    ,...
    AF.AF_0.freq(AF.AF_0.Jfreq)...
    ,...
    '.')

plot(...
    abs(...
    NMD.NMD_0.LJ.tau/NMD.NMD_0.LJ.sigma*sqrt(...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,1).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,2).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,3).^2 )...
    -...
    sqrt(...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,1).^2 + ...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,2).^2 + ...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,3).^2 )...
    )...
    ,...
    '.')

plot(...
    NMD.NMD_0.LJ.tau/NMD.NMD_0.LJ.sigma*sqrt(...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,1).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,2).^2 + ...
    SED.SED_0.groupvel(SED.SED_0.Jfreq,3).^2 )...
    ,...
    sqrt(...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,1).^2 + ...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,2).^2 + ...
    AF.AF_0.groupvel(AF.AF_0.Jfreq,3).^2 )...
    ,...
    '.')




    
% save(...
%     strcat(str.main,'AF_groupvel_1.mat')...
%     , '-struct', 'AFsave');
% 
