
function [DOSX DOSY] = lj_DOS(freq, DOS_BIN, NUM_ATOMS)

[DOSY DOSX]= hist(freq,ceil(NUM_ATOMS/DOS_BIN));

end



% AF.eig_fftz(imode,1:size(KPT.kpt,1)) =...
%     sum(...
%     abs(...
%     bsxfun(...
%     @times , real(exp(spatialx + spatialy +spatialz)) ,...
%     AF.eigvec(3:3:size(AF.eigvec,1),imode) )  + ...
%     bsxfun(...
%     @times , imag(exp(spatialx + spatialy +spatialz)) ,...
%     AF.eigvec(3:3:size(AF.eigvec,1),imode) )...
%     )...
%     , 1);



