
clear

NMD.LJ.eps = 1.67E-21;              %aJ (1.67E-21 Joules) aJ=1E-18 J
NMD.LJ.sigma = 3.4E-10;                 %Angstroms 3.4E-10 meters
NMD.LJ.mass = 6.6326E-26;               %1E-28 kg (6.6326E-26 kg)
NMD.LJ.tau = sqrt((NMD.LJ.mass*(NMD.LJ.sigma^2))/NMD.LJ.eps);
NMD.constant.kb = 1.3806E-23;                    %aJ/k (1.3806E-23 J/K)
NMD.constant.hbar = 1.054E-34;                %J/s
NMD.constant.i = sqrt(-1);
NMD.constant.c = 29979245800.00019;      %cm/s
NMD.constant.s2ps = 1E-12;
NMD.constant.ang2m = 1E-10;
NMD.constant.eV2J = 1.60217646E-19;

c=0.15;

SED12x_0=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/12x/NMD/1/SEDdata.mat'));

SED12x_05=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.05/12x/NMD/1/SEDdata.mat'));

SED12x_15=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.15/12x/NMD/1/SEDdata.mat'));

SED12x_5=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.5/12x/NMD/1/SEDdata.mat'));


    
%-100 = 78
ikpt=10;
SED12x_0.irrkpt.kpt(ikpt,:)
semilogy(...
    SED12x_0.omega(:,:),sum(SED12x_0.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_05.omega(:,:),sum(SED12x_05.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_15.omega(:,:),sum(SED12x_15.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_5.omega(:,:),sum(SED12x_5.irrkpt.sedavg(:,:,ikpt),2),'.')
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
semilogy(...
    SED12x_0.omega(:,:),sum(SED12x_0.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_05.omega(:,:),sum(SED12x_05.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_15.omega(:,:),sum(SED12x_15.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_5.omega(:,:),SED12x_5.irrkpt.sedavg(:,:,ikpt),'.')
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
semilogy(...
    SED12x_0.omega(:,:),sum(SED12x_0.irrkpt.sedavg(:,:,ikpt),2),'.',...
    SED12x_05.omega(:,:),SED12x_05.irrkpt.sedavg(:,:,ikpt),'.')
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
plot(...
    SED12x_0.irrkpt.HLDfreq(:,:)*NMD.LJ.tau,SED12x_0.irrkpt.sedfreq,'.',...
    SED12x_05.irrkpt.HLDfreq(:,:)*NMD.LJ.tau,SED12x_05.irrkpt.sedfreq,'.',...
    SED12x_15.irrkpt.HLDfreq(:,:)*NMD.LJ.tau,SED12x_15.irrkpt.sedfreq,'.',...
    SED12x_5.irrkpt.HLDfreq(:,:)*NMD.LJ.tau,SED12x_5.irrkpt.sedfreq,'.')



