
clear

c=0.5;

SED12x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/12x/NMD/1/SEDdata.mat'));
SED10x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/10x/NMD/1/SEDdata.mat'));
SED8x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/8x/NMD/1/SEDdata.mat'));
SED6x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/6x/NMD/1/SEDdata.mat'));
SED4x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/4x/NMD/1/SEDdata.mat'));
SED4x=...
    load(...
    strcat(...
    '/home/jason/lammps/LJ/alloy/10K/0.0/4x/NMD/1/SEDdata.mat'));

%perfect
% conductivity =...
%     [SED12x.conductivityx SED10x.conductivityx SED8x.conductivityx...
%     SED6x.conductivityx SED4x.conductivityx];
% length = [1/12 1/10 1/8 1/6 1/4];
%alloy
conductivity =...
    [SED12x.conductivityx SED10x.conductivityx SED8x.conductivityx...
    SED6x.conductivityx];
length = [1/12 1/10 1/8 1/6];



linear_func = @(c,length)(c(1).*length + c(2));

weights(1:size(conductivity,2)) =1;

options =...
    optimset(...
    'MaxIter',20000,'MaxFunEvals',20000,'TolFun',1e-7,'TolX',1e-8); 
%Initial Guess
    c0 = [ -1 3.0 ]; 
%FIT
    lb(1:size(c0,2)) = -1000; ub(1:size(c0,2)) = 1000; 
    [c_fit] =...
        lsqcurvefit(linear_func,c0,length,conductivity,lb,ub,options);
%estimate error    
    length1 = length(2:size(length,2)); 
    conductivity1 = conductivity(2:size(length,2));
    [c_fit1] =...
        lsqcurvefit(linear_func,c0,length1,conductivity1,lb,ub,options);
    
    length2 = length(1:size(length,2)-1); 
    conductivity2 = conductivity(1:size(length,2)-1);
    [c_fit2] =...
        lsqcurvefit(linear_func,c0,length2,conductivity2,lb,ub,options);
    
    length3 = length(1:size(length,2)-2); 
    conductivity3 = conductivity(1:size(length,2)-2);
    [c_fit3] =...
        lsqcurvefit(linear_func,c0,length3,conductivity3,lb,ub,options);
    
    error = std([c_fit(2) c_fit1(2) c_fit2(2) c_fit3(2)]);
    
    plot(length, conductivity,'.',...
        [0 length],linear_func(c_fit,[0 length]))
    c_fit(2)
    error/c_fit(2)
    
    

% 
% 
% loglog(SED4x.irrkpt.sedfreq(1,:),SED4x.irrkpt.life(1,:),'.',...
%     SED8x.irrkpt.sedfreq(1,:),SED8x.irrkpt.life(1,:),'.',...
%     SED10x.irrkpt.sedfreq(1,:),SED10x.irrkpt.life(1,:),'.')




% plot([0 1/10 1/8 1/4],[3.8 3.5233 3.5591 3.27])


%alloy amorphous
alloy(1,:) = [0.0 0.05 0.15 0.5];
alloy(2,:) = [3.5694 0.9834 0.4979 0.3906];
plot(alloy(1,:),alloy(2,:),'.',alloy(1,:),0.0849*ones(1,4))



