%--------------------------------------------------------------------------
%0.0
%--------------------------------------------------------------------------
%10x
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.0/10x/NMD/1';
NMD(1).NMD=load(strcat(str.NMD,'/NMDdata.mat'));
SED(1).SED=load(strcat(str.NMD,'/SEDdata.mat'));
SED(1).SED = nmd_convert_data(NMD(1).NMD,SED(1).SED);

%plot sed life
idata=1;
loglog(...
    SED(idata).SED.sedfreq,...
    SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(idata).SED.sedfreq,...
    10E2*SED(idata).SED.sedfreq.^(-1.8)...
    )
%MFP_cond
num_mfp = 100;
min_mfp = 1.0; %nm
max_mfp = max(SED(1).SED.MFP*1E9)*1.5;
dmfp = (max_mfp - min_mfp)/num_mfp;

for imfp = 1:num_mfp
    I1 = find( SED(1).SED.MFP*1E9 < min_mfp + (imfp-1)*dmfp );
    SED(1).SED.MFP_cond(imfp,1) = min_mfp + imfp*dmfp;
    SED(1).SED.MFP_cond(imfp,2) =...
        sum(...
        (NMD(1).NMD.constant.kb/NMD(1).NMD.VOLUME)*...
        SED(1).SED.life(I1).*...
        SED(1).SED.groupvel(I1,1).^2 ...
        );
end
plot(SED(1).SED.MFP_cond(:,1),SED(1).SED.MFP_cond(:,2))
%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

%--------------------------------------------------------------------------
%0.05
%--------------------------------------------------------------------------
%10x
%xcorr
idata=2;
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.05/10x/NMD_AF/1';
NMDX(2).NMD=load(strcat(str.NMD,'/NMDfit.mat'));
SEDX(2).SED=load(strcat(str.NMD,'/SEDfit.mat'));
%nmd
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.05/10x/NMD/1';
NMD(2).NMD=load(strcat(str.NMD,'/NMDdata.mat'));
SED(2).SED=load(strcat(str.NMD,'/SEDdata.mat'));
SED(2).SED = nmd_convert_data(NMD(2).NMD,SED(2).SED);
%af
str.AF = '/home/jason/lammps/LJ/alloy/10K/0.05/10x/XCORR_AF';
AF(2).AF.Di = load(strcat(str.AF,'/Di(wi)_1.dat')); 
AF(2).AF.freq = load(strcat(str.AF,'/AF_freq_1.dat')); 

AF(2).AF.groupvel =...
(2/3)*(0.5462/0.5604)*(0.5462/0.7182)*max(SED(1).SED.groupvel(:,1)) +...
(1/3)*(0.7182/0.7370)*max(SED(1).SED.groupvel(:,1)) ;

AF(2).AF.groupvel = AF(2).AF.groupvel*1.0;
AF(2).AF.groupvel_scale = AF(2).AF.groupvel*2.0;

%plot sed life
loglog(...
    SED(idata).SED.sedfreq,...
    SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(idata).SED.sedfreq,...
    3E2*SED(idata).SED.sedfreq.^(-2),...
    SED(idata).SED.sedfreq,...
    1E4*SED(idata).SED.sedfreq.^(-4)...
    )
%filter
I(idata).I =...
    find(SEDX(idata).SED.life > 12.0 & SEDX(idata).SED.sedfreq >10.0);
SEDX(idata).SED.life(I(idata).I) = 0;
%plot AF life
loglog(...
    SEDX(idata).SED.sedfreq,...
    SEDX(idata).SED.life,'.',...
    SEDX(idata).SED.sedfreq,...
    3E2*SEDX(idata).SED.sedfreq.^(-2),...
    SEDX(idata).SED.sedfreq,...
    1E4*SEDX(idata).SED.sedfreq.^(-4)...
    )

[SEDX(idata).SED.cond SEDX(idata).SED.MFP SEDX(idata).SED.MFP_cond] =...
    xcorr_cond( NMD(idata).NMD , SEDX(idata).SED , AF(idata).AF ) ;
%plot in nm
loglog(...
    SEDX(idata).SED.HLDfreq/NMD(idata).NMD.LJ.tau,...
    SEDX(idata).SED.MFP*1E9,'.')
%pause
plot(SEDX(idata).SED.MFP_cond(:,1),SEDX(idata).SED.MFP_cond(:,2))
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%0.15
%--------------------------------------------------------------------------
%10x
idata=3;
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.15/10x/NMD_AF/1';
NMDX(3).NMD=load(strcat(str.NMD,'/NMDfit.mat'));
SEDX(3).SED=load(strcat(str.NMD,'/SEDfit.mat'));
%nmd
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.15/10x/NMD/1';
NMD(3).NMD=load(strcat(str.NMD,'/NMDdata.mat'));
SED(3).SED=load(strcat(str.NMD,'/SEDdata.mat'));
SED(3).SED = nmd_convert_data(NMD(3).NMD,SED(3).SED);
%af
str.AF = '/home/jason/lammps/LJ/alloy/10K/0.15/10x/XCORR_AF';
AF(3).AF.Di = load(strcat(str.AF,'/Di(wi)_1.dat')); 
AF(3).AF.freq = load(strcat(str.AF,'/AF_freq_1.dat')); 

AF(3).AF.groupvel =...
(2/3)*(0.5187/0.5604)*(0.5187/0.6822)*max(SED(1).SED.groupvel(:,1)) +...
(1/3)*(0.6822/0.7370)*max(SED(1).SED.groupvel(:,1)) ;

AF(3).AF.groupvel = AF(3).AF.groupvel*0.8;
AF(3).AF.groupvel_scale = AF(3).AF.groupvel*2.53;

%plot sed life
loglog(...
    SED(idata).SED.sedfreq,...
    SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(idata).SED.sedfreq,...
    3E2*SED(idata).SED.sedfreq.^(-2),...
    SED(idata).SED.sedfreq,...
    1E4*SED(idata).SED.sedfreq.^(-4)...
    )
%filter
I(idata).I =...
    find(SEDX(idata).SED.life > 20.0 & SEDX(idata).SED.sedfreq >5.5);
SEDX(idata).SED.life(I(idata).I) = 0;
%plot AF life
loglog(...
    SEDX(idata).SED.sedfreq,...
    SEDX(idata).SED.life,'.',...
    SEDX(idata).SED.sedfreq,...
    3E2*SEDX(idata).SED.sedfreq.^(-2),...
    SEDX(idata).SED.sedfreq,...
    1E4*SEDX(idata).SED.sedfreq.^(-4)...
    )

[SEDX(idata).SED.cond SEDX(idata).SED.MFP SEDX(idata).SED.MFP_cond] =...
    xcorr_cond( NMD(idata).NMD , SEDX(idata).SED , AF(idata).AF ) ;
%plot in nm
loglog(...
    SEDX(idata).SED.HLDfreq/NMD(idata).NMD.LJ.tau,...
    SEDX(idata).SED.MFP*1E9,'.')
%pause
plot(SEDX(idata).SED.MFP_cond(:,1),SEDX(idata).SED.MFP_cond(:,2))
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%0.5
%--------------------------------------------------------------------------
%10x
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.5/10x/NMD_AF/1';
NMDX(4).NMD=load(strcat(str.NMD,'/NMDfit.mat'));
SEDX(4).SED=load(strcat(str.NMD,'/SEDfit.mat'));
%nmd
str.NMD = '/home/jason/lammps/LJ/alloy/10K/0.5/10x/NMD/1';
NMD(4).NMD=load(strcat(str.NMD,'/NMDdata.mat'));
SED(4).SED=load(strcat(str.NMD,'/SEDdata.mat'));
SED(4).SED = nmd_convert_data(NMD(4).NMD,SED(4).SED);
%af
str.AF = '/home/jason/lammps/LJ/alloy/10K/0.5/10x/XCORR_AF';
AF(4).AF.Di = load(strcat(str.AF,'/Di(wi)_1.dat')); 
AF(4).AF.freq = load(strcat(str.AF,'/AF_freq_1.dat')); 

AF(4).AF.groupvel =...
(2/3)*(0.4282/0.5604)*(0.4282/0.5633)*max(SED(1).SED.groupvel(:,1)) +...
(1/3)*(0.5633/0.7370)*max(SED(1).SED.groupvel(:,1)) ;

AF(4).AF.groupvel = AF(4).AF.groupvel*1.0;
AF(4).AF.groupvel_scale = AF(4).AF.groupvel*1.5;

%plot sed life
idata=4;
loglog(...
    SED(idata).SED.sedfreq,...
    SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(idata).SED.sedfreq,...
    3E2*SED(idata).SED.sedfreq.^(-2),...
    SED(idata).SED.sedfreq,...
    1E4*SED(idata).SED.sedfreq.^(-4)...
    )
%filter
I(idata).I =...
    find(SEDX(idata).SED.life > 15 & SEDX(idata).SED.sedfreq > 5.4 );
SEDX(idata).SED.life(I(idata).I) = 0;
I(idata).I =...
    find(SEDX(idata).SED.life > 120 );
SEDX(idata).SED.life(I(idata).I) = 0;
%plot AF life
loglog(...
    SEDX(idata).SED.sedfreq,...
    SEDX(idata).SED.life,'.',...
    SEDX(idata).SED.sedfreq,...
    3E2*SEDX(idata).SED.sedfreq.^(-2),...
    SEDX(idata).SED.sedfreq,...
    1E4*SEDX(idata).SED.sedfreq.^(-4)...
    )

[SEDX(idata).SED.cond SEDX(idata).SED.MFP SEDX(idata).SED.MFP_cond] =...
    xcorr_cond( NMD(idata).NMD , SEDX(idata).SED , AF(idata).AF ) ;
%plot in nm
loglog(...
    SEDX(idata).SED.HLDfreq/NMD(idata).NMD.LJ.tau,...
    SEDX(idata).SED.MFP*1E9,'.')
%pause
plot(SEDX(idata).SED.MFP_cond(:,1),SEDX(idata).SED.MFP_cond(:,2))
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%amor
%--------------------------------------------------------------------------
%10x
idata=5;
str.NMD = '/home/jason/lammps/LJ/amorphous/10x/XCORR_AF/1';
NMDX(5).NMD=load(strcat(str.NMD,'/NMDfit.mat'));
SEDX(5).SED=load(strcat(str.NMD,'/SEDfit.mat'));
%af
str.AF = '/home/jason/lammps/LJ/amorphous/10x/prepare';
AF(5).AF.Di = load(strcat(str.AF,'/Di(wi)_1.dat')); 
AF(5).AF.freq = load(strcat(str.AF,'/AF_freq_1.dat')); 

AF(5).AF.groupvel =...
(0.4411/0.7370)*max(SED(1).SED.groupvel(:,1));

AF(5).AF.groupvel_scale = AF(5).AF.groupvel*1.0;

[SEDX(idata).SED.cond SEDX(idata).SED.MFP SEDX(idata).SED.MFP_cond] =...
    xcorr_cond( NMD(1).NMD , SEDX(idata).SED , AF(idata).AF ) ;
%plot in nm
loglog(...
    SEDX(idata).SED.HLDfreq/NMD(1).NMD.LJ.tau,...
    SEDX(idata).SED.MFP*1E9,'.')
%pause
plot(SEDX(idata).SED.MFP_cond(:,1),SEDX(idata).SED.MFP_cond(:,2))
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------


%plot Di
loglog(...
    AF(2).AF.freq,AF(2).AF.Di(:,2),'.',...
    AF(3).AF.freq,AF(3).AF.Di(:,2),'.',...
    AF(4).AF.freq,AF(4).AF.Di(:,2),'.',...
    AF(5).AF.freq,AF(5).AF.Di(:,2),'.'...
    )
%--------------------------------------------------------------------------
%pause
%--------------------------------------------------------------------------
%plot xcorr life

%plot VC results
loglog(...
    SED(1).SED.sedfreq,...
    SED(1).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(2).SED.freq*NMD(1).NMD.LJ.tau,...
    SED(2).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(3).SED.freq*NMD(1).NMD.LJ.tau,...
    SED(3).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SED(1).SED.sedfreq,...
    3E2*SED(1).SED.sedfreq.^(-2),...
    SED(1).SED.sedfreq,...
    1E4*SED(1).SED.sedfreq.^(-4)...
    )

% xcorr_alloy_vc_life_createfigure(...
%     X1, YMatrix1, X2, Y1, X3, Y2...
%     )

%plot gamma pt results
loglog(...
    SEDX(2).SED.HLDfreq,SEDX(2).SED.life,'.',...
    SEDX(3).SED.HLDfreq,SEDX(3).SED.life,'.',...
    SEDX(4).SED.HLDfreq,SEDX(4).SED.life,'.',...
    SEDX(5).SED.HLDfreq,SEDX(5).SED.life,'.',...
    SED(1).SED.sedfreq,...
    3E2*SED(1).SED.sedfreq.^(-2),...
    SED(1).SED.sedfreq,...
    1E4*SED(1).SED.sedfreq.^(-4)...
    )

%plot amorphous results
loglog(...
    SED(1).SED.sedfreq,...
    SED(1).SED.life/NMD(1).NMD.LJ.tau,'.',...
    SEDX(5).SED.HLDfreq,SEDX(5).SED.life,'.'...
    )
%plot gamma period vs life
loglog(...
    2*pi./SED(1).SED.sedfreq,...
    SED(1).SED.life/NMD(1).NMD.LJ.tau,'.',...
    2*pi./SED(1).SED.sedfreq,2*pi./SED(1).SED.sedfreq,...
    2*pi./SEDX(2).SED.HLDfreq,SEDX(2).SED.life,'.',...
    2*pi./SEDX(2).SED.HLDfreq,2*pi./SEDX(2).SED.HLDfreq,...
    2*pi./SEDX(3).SED.HLDfreq,SEDX(3).SED.life,'.',...
    2*pi./SEDX(3).SED.HLDfreq,2*pi./SEDX(3).SED.HLDfreq...
    )
%plot VC period vs life
% loglog(...
%     2*pi./SED(1).SED.sedfreq,...
%     SED(1).SED.life/NMD(1).NMD.LJ.tau,'.',...
%     2*pi./SED(1).SED.sedfreq,...
%     2*pi./SED(1).SED.sedfreq,...
%     2*pi./SED(2).SED.freq/NMD(1).NMD.LJ.tau,...
%     SED(2).SED.life/NMD(1).NMD.LJ.tau,'.',...
%     2*pi./SED(2).SED.freq/NMD(1).NMD.LJ.tau,...
%     2*pi./SED(2).SED.freq/NMD(1).NMD.LJ.tau...
%     )

%plot v_AF vs
loglog(...
    SEDX(2).SED.HLDfreq,...
    sqrt(AF(2).AF.Di(:,2)./SEDX(2).SED.life'),'.',...
    SEDX(2).SED.HLDfreq,...
    ones(size(SEDX(2).SED.HLDfreq,2),1).*AF(2).AF.groupvel*NMD(2).NMD.LJ.tau/NMD(2).NMD.LJ.sigma...
    )

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------
% %plot sed life
% idata = 2;
% loglog(...
%     SED(idata).SED.sedfreq,...
%     SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
%     SEDX(idata).SED.HLDfreq,...
%     SEDX(idata).SED.life,'.',...
%     SED(idata).SED.sedfreq,...
%     3E2*SED(idata).SED.sedfreq.^(-2),...
%     SED(idata).SED.sedfreq,...
%     1E4*SED(idata).SED.sedfreq.^(-4)...
%     )
% 
% %plot period vs life
% idata = 1;
% loglog(...
%     2*pi./SED(idata).SED.sedfreq,...
%     SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
%     2*pi./SED(idata).SED.sedfreq,...
%     2*pi./SED(idata).SED.sedfreq...
%     )
% 
% idata = 2;
% loglog(...
%     2*pi./SED(idata).SED.sedfreq,...
%     SED(idata).SED.life/NMD(1).NMD.LJ.tau,'.',...
%     2*pi./SEDX(idata).SED.HLDfreq,...
%     SEDX(idata).SED.life*NMD(1).NMD.LJ.tau/NMD(1).NMD.constant.s2ps,'.',...
%     2*pi./SED(idata).SED.sedfreq,...
%     2*pi./SED(idata).SED.sedfreq...
%     )
% 
% %plot AF vel vs VC
% idata = 3;
% loglog(...
%     SED(idata).SED.sedfreq,...
%     SED(idata).SED.groupvel(:,1)*NMD(1).NMD.LJ.tau/NMD(1).NMD.LJ.sigma,'.',...
%     SEDX(idata).SED.HLDfreq,...
%     sqrt(AF(idata).AF.Di(:,2)./SEDX(idata).SED.life'),'.'...
%     )
% 
% %plot Sound Speed vs AF vel
% idata = 2;
% loglog(...
%     SEDX(idata).SED.HLDfreq,...
%     sqrt(AF(idata).AF.Di(:,2)./SEDX(idata).SED.life'),'.',...
%     SEDX(idata).SED.HLDfreq,...
%     ones(size(SEDX(idata).SED.HLDfreq,2),1).*AF(2).AF.groupvel*NMD(1).NMD.LJ.tau/NMD(1).NMD.LJ.sigma...
%     )
    

%--------------------------------------------------------------------------
pause
%--------------------------------------------------------------------------

semilogx(...
    1.3*SED(1).SED.MFP_cond(1:length(SEDX(3).SED.MFP_cond)-34,1),...
    SED(1).SED.MFP_cond(1:length(SEDX(3).SED.MFP_cond)-34,2)/...
    max(SED(1).SED.MFP_cond(1:length(SEDX(3).SED.MFP_cond)-34,2)),...
    0.75*SEDX(2).SED.MFP_cond(3:length(SEDX(2).SED.MFP_cond),1),...
    SEDX(2).SED.MFP_cond(3:length(SEDX(2).SED.MFP_cond),2)/...
    max(SEDX(2).SED.MFP_cond(:,2)),...
    0.75*SEDX(3).SED.MFP_cond(2:length(SEDX(3).SED.MFP_cond),1),...
    SEDX(3).SED.MFP_cond(2:length(SEDX(3).SED.MFP_cond),2)/...
    max(SEDX(3).SED.MFP_cond(:,2)),...
    SEDX(4).SED.MFP_cond(2:length(SEDX(3).SED.MFP_cond),1),...
    SEDX(4).SED.MFP_cond(2:length(SEDX(3).SED.MFP_cond),2)/...
    max(SEDX(4).SED.MFP_cond(:,2)),...
    SEDX(5).SED.MFP_cond(:,1),...
    SEDX(5).SED.MFP_cond(:,2)/max(SEDX(5).SED.MFP_cond(:,2))...
    )
    
%xcorr_alloy_cum_cond_createfigure(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5)

