function xcorr_alloy_vc_life_createfigure(X1, YMatrix1, X2, Y1, X3, Y2)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1,X3,Y2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 07-Jul-2012 17:13:07

% Create figure
figure1 = figure('XVisual',...
    '0x94 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'Units','inches',...
    'Position',[0.8 0.733333333333334 3.81866666666667 3.28638888888889],...
    'LineWidth',2,...
    'FontSize',15);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.86295352281829 28.3152370635773]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.160720134631964 100.368502401409]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Parent',axes1,'MarkerSize',15,'LineWidth',2);
set(loglog1(1),'Marker','.','LineStyle','none','DisplayName','c=0.0',...
    'LineWidth',0.5);
set(loglog1(2),'DisplayName','$\omega^{-2}$','MarkerSize',6);
set(loglog1(3),'DisplayName','$\omega^{-4}$');

% Create loglog
loglog(X2,Y1,'Parent',axes1,'MarkerSize',15,'Marker','.','LineStyle','none',...
    'DisplayName','c=0.05');

% Create loglog
loglog(X3,Y2,'Parent',axes1,'MarkerSize',15,'Marker','.','LineStyle','none',...
    'DisplayName','c=0.15');

% Create xlabel
xlabel({'$\omega$ (LJ units)'},'Interpreter','latex','FontSize',20);

% Create ylabel
ylabel({'$\tau$ (LJ units)'},'Interpreter','latex','FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','Units','inches',...
    'Position',[0.937500000000001 0.810416666666668 1.27222222222222 1.57222222222222],...
    'LineWidth',2);

