function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Mar-2012 21:25:31

% Create figure
figure1 = figure('XVisual',...
    '0x94 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1,'XMinorTick','on','Units','inches',...
    'Position',[0.755555555555556 0.561805555555555 3.58333333333333 3.54330709],...
    'LineWidth',2,...
    'FontSize',15,...
    'FontName','Arial');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'MarkerSize',10,'Marker','o','LineStyle','none',...
    'DisplayName','alloy $m_r=3$');
set(plot1(2),'LineWidth',2,'DisplayName','amorphous $m=1$');

% Create xlabel
xlabel({'$\omega_{i}$ (LJ)'},'Interpreter','latex','FontSize',15,...
    'FontName','Arial');

% Create ylabel
ylabel({'$k_{vib}$ (W/m-K)'},'Interpreter','latex','FontSize',15,...
    'FontName','Arial');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','EdgeColor',[1 1 1],'YColor',[1 1 1],...
    'XColor',[1 1 1],...
    'Units','inches',...
    'Position',[2.34444444444444 3.31458333333335 1.88680555555557 0.684722222222222],...
    'FontSize',12);

